// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
export class CommerceClient{
  constructor({api,toast,playerId,refresh}={}){this.api=api;this.toast=toast;this.playerId=playerId;this.refresh=refresh;this.pending=new Map();this.nativeProducts=new Map();this.catalog=new Map();globalThis.NyrathenNativeStoreResult=value=>this.onNative(value);}
  nativeKind(){if(globalThis.NyrathenStore?.request)return'android';if(globalThis.webkit?.messageHandlers?.nyrathenStore)return'ios';return'dev';}
  async state(){const data=await this.api('/api/store');this.catalog=new Map((data?.store||[]).map(p=>[p.id,p]));return data;}
  event(event,productId=null){return this.api('/api/store/event','POST',{event,productId}).catch(()=>{});}
  native(payload){const requestId=globalThis.crypto?.randomUUID?.()||`shop-${Date.now()}-${Math.random()}`,message={...payload,requestId,accountId:this.playerId?.()||''};return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(requestId);reject(new Error('Store antwortet nicht.'));},60000);this.pending.set(requestId,{resolve,reject,timer});try{if(globalThis.NyrathenStore?.request)globalThis.NyrathenStore.request(JSON.stringify(message));else if(globalThis.webkit?.messageHandlers?.nyrathenStore)globalThis.webkit.messageHandlers.nyrathenStore.postMessage(message);else throw new Error('Einkäufe sind nur im signierten iOS-/Android-Build verfügbar.');}catch(e){clearTimeout(timer);this.pending.delete(requestId);reject(e);}});}
  onNative(value){let data=value;try{if(typeof value==='string')data=JSON.parse(value);}catch{}if(!data?.requestId)return;const p=this.pending.get(data.requestId);if(!p)return;clearTimeout(p.timer);this.pending.delete(data.requestId);if(data.ok===false)p.reject(new Error(data.error||'Store-Kauf fehlgeschlagen.'));else p.resolve(data);}
  async prices(productIds){try{const result=await this.native({type:'products',productIds});for(const p of result.products||[])this.nativeProducts.set(p.id,p);return this.nativeProducts;}catch{return this.nativeProducts;}}
  async purchase(productId){await this.event('purchase_start',productId);try{const native=await this.native({type:'purchase',productId}),provider=native.provider;if(!native.receipt||!provider)throw new Error('Store-Beleg fehlt.');const grant=await this.api('/api/store/verify','POST',{provider,productId,receipt:native.receipt});await this.native({type:'finalize',provider,transactionId:native.transactionId||grant.transactionId,receipt:native.receipt,productId,consumable:grant.consumable===true}).catch(()=>{});this.toast?.(grant.commerce?.shards!=null?`Kauf bestätigt · ${grant.commerce.shards} Nyr-Splitter`:'Kauf bestätigt.');this.refresh?.();return grant;}catch(error){await this.event('purchase_failed',productId);throw error;}}
  async redeemTransactions(transactions,{recordRestore=true}={}){if(!this.catalog.size)await this.state().catch(()=>{});const rows=[];for(const tx of transactions||[]){try{if(!tx?.provider||!tx?.productId||!tx?.receipt)continue;const grant=await this.api('/api/store/verify','POST',{provider:tx.provider,productId:tx.productId,receipt:tx.receipt});rows.push(grant);const consumable=grant.consumable===true||this.catalog.get(tx.productId)?.consumable===true;await this.native({type:'finalize',provider:tx.provider,transactionId:tx.transactionId||grant.transactionId,receipt:tx.receipt,productId:tx.productId,consumable}).catch(()=>{});}catch{}}if(recordRestore)await this.event('purchase_restore');if(rows.length)this.refresh?.();return rows;}
  async recoverPending(){if(this.nativeKind()==='dev')return[];if(this.recoveryPromise)return this.recoveryPromise;this.recoveryPromise=(async()=>{try{const result=await this.native({type:'recover'});return await this.redeemTransactions(result.transactions||[],{recordRestore:false});}catch{return[];}finally{this.recoveryPromise=null;}})();return this.recoveryPromise;}
  async restore(){if(!this.catalog.size)await this.state().catch(()=>{});const result=await this.native({type:'restore'});return this.redeemTransactions(result.transactions||[],{recordRestore:true});}
  spend(offerId){return this.api('/api/store/spend','POST',{offerId,requestId:globalThis.crypto?.randomUUID?.()||String(Date.now())});}
  wishlist(productId,enabled){return this.api('/api/store/wishlist','POST',{productId,enabled});}
}
