// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import { CLASSES, ENEMY_TYPES, RARITIES, VERSION, dist, clamp, xpNeeded } from '../shared/data.mjs';
import { cleanName } from '../shared/engine.mjs';
import { AdventureEngine, cleanAdventureProfile } from '../shared/adventure.mjs';
import { SystemScreens } from './systems.mjs';
import { EQUIP_SLOTS, SLOT_LABELS, STAT_LABELS, STAT_CAPS, DUNGEONS, isBoss } from '../shared/realm-data.mjs';
import { Renderer } from './renderer.mjs';
import { InputController } from './input.mjs';
import { GameNetwork } from './network.mjs';
import { makeInvitation, parseInvitation, normalizeRegion } from './protocol.mjs';
import { cleanDisplaySettings, compareEquipment } from './presentation.mjs';
import { GameAudio } from './audio.mjs';
import { CommerceClient } from './commerce.mjs';
import { vaultCapacity } from '../shared/monetization-data.mjs';
const $=s=>document.querySelector(s);
startLocalization();
const htmlEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function getStorage(k,f){try{const s=localStorage.getItem(k);return s?JSON.parse(s):f;}catch{return f;}}
function putStorage(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}}
function removeStorage(k){try{localStorage.removeItem(k);}catch{}}
const SAVE_KEY='nyrathen.save.v3',WORLD_KEY='nyrathen.worlds.v2',SETTINGS_KEY='nyrathen.settings.v2',DIAGNOSTICS_KEY='nyrathen.diagnostics.v1',COMMUNITY_TERMS_KEY='nyrathen.community.v1';
let saveBundle=getStorage(SAVE_KEY,null);let saved=saveBundle?.profile||getStorage('nyrathen.offline.v2',getStorage('nyrathen.offline.v1',null));if(saved)saved=cleanAdventureProfile(saved);
let settings=cleanDisplaySettings({reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,...getStorage(SETTINGS_KEY,{})});
let invitation=null;try{if(location.hash.startsWith('#join='))invitation=parseInvitation(location.href);}catch{}
const HOSTING_MODE=document.querySelector('meta[name="nyrathen-hosting"]')?.content||'integrated';
let advertisedServer=document.querySelector('meta[name="nyrathen-public-server"]')?.content?.trim()||'';
let advertisedServers=(document.querySelector('meta[name="nyrathen-public-servers"]')?.content||'').split(',').map(x=>x.trim()).filter(Boolean);
const legalUrls=Object.freeze({privacy:document.querySelector('meta[name=\"nyrathen-privacy-url\"]')?.content?.trim()||'',terms:document.querySelector('meta[name=\"nyrathen-terms-url\"]')?.content?.trim()||'',support:document.querySelector('meta[name=\"nyrathen-support-url\"]')?.content?.trim()||'',deleteAccount:document.querySelector('meta[name=\"nyrathen-delete-account-url\"]')?.content?.trim()||''});
const legalHref=(key,label)=>legalUrls[key]?`<a class="secondary-button legal-link" href="${htmlEscape(legalUrls[key])}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`:'';
try{const queryServer=new URLSearchParams(location.search).get('server');advertisedServers=[queryServer||advertisedServer,...advertisedServers].filter(Boolean).map(GameNetwork.validBase).filter((v,i,a)=>a.indexOf(v)===i);advertisedServer=advertisedServers[0]||'';}catch{advertisedServer='';advertisedServers=[];}
let selectedClass=saved?.classId||'weaver',mode='menu',playerId='preview',state=null,engine=null,modalKind='',selectedItem=null,lastBagSignature='',lastQuickSignature='',lastChatSignature='',lastEventSeen=0,deathSeen=false,onlineConfig=null,communityAcceptedSession=false;
let lastRender=0,renderDT=0;
let lastFrame=performance.now(),accumulator=0,lastUI=0,lastSave=0,lastInputSend=0,lastFPS=performance.now(),frameCount=0,fps=0,storageWarning=false;
const errors=(Array.isArray(getStorage(DIAGNOSTICS_KEY,[]))?getStorage(DIAGNOSTICS_KEY,[]):[]).slice(-20),renderer=new Renderer($('#world'),$('#minimap')),audio=new GameAudio(),modal=$('#modal'),content=$('#modal-content');
const input=new InputController($('#world'),renderer,a=>sendAction(a));
const network=new GameNetwork(s=>{state=s;playerId=network.id||playerId;},(status,message)=>{
  if(status==='connected'){$('#network-banner').classList.add('hidden');$('#reconnect-btn').disabled=false;}
  if(['disconnected','reconnecting'].includes(status)&&mode==='online'){input.reset();$('#reconnect-btn').disabled=status==='reconnecting';$('#network-message').textContent=message||'Verbindung unterbrochen. Deine Figur bleibt 15 Sekunden verwundbar.';$('#network-banner').classList.remove('hidden');}
});
let screens;
const commerce=new CommerceClient({api:(path,method='GET',data)=>network.api(path,method,data),toast,playerId:()=>playerId,refresh:()=>{if(screens&&modalKind==='systems'&&screens.section==='shop')screens.show('shop');}});
screens=new SystemScreens({own:()=>ownPlayer(),state:()=>state,mode:()=>mode,modalKind:()=>modalKind,escape:htmlEscape,renderer,drawItems,portrait:drawPortrait,modal:showModal,close:closeModal,action:sendAction,toast,party:showParty,chat:showChat,api:(p,m,d)=>network.api(p,m,d),authenticate:GameNetwork.authenticate,join:connectSession,base:()=>network.base,backup:backupSolo,restore:restoreSolo,textFile,shop:commerce,logout:()=>{removeStorage('nyrathen.token.'+network.base);menu();}});
function deliverFile(name,text,mime){
  if(typeof window.NyrathenFiles?.saveFile==='function'){window.NyrathenFiles.saveFile(name,text,mime);return;}
  if(window.webkit?.messageHandlers?.nyrathenFiles){window.webkit.messageHandlers.nyrathenFiles.postMessage({name,text,mime});return;}
  const url=URL.createObjectURL(new Blob([text],{type:mime})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);
}
function textFile(name,text){deliverFile(name,text,'text/plain');}
function backupSolo(){saveOffline();download('Nyrathen-Solo-Sicherung.json',{version:3,profile:engine.profile(playerId),worlds:engine.exportWorlds()});}
async function restoreSolo(file){
  if(!file)return;
  try{
    if(file.size>8000000)throw new Error('Sicherung ist zu groß.');const raw=JSON.parse(await file.text());
    if(raw.version!==3||!raw.profile||raw.worlds?.version!==2||!Array.isArray(raw.worlds.worlds))throw new Error('Keine passende Nyrathen-Sicherung.');
    const profile=cleanAdventureProfile(raw.profile),candidate=new AdventureEngine({savedWorld:raw.worlds});candidate.addPlayer('local',profile.name,profile.classId,profile);candidate.snapshot('local');showModal('restore-confirm','Solo-Spielstand ersetzen?',`<p>Die Sicherung enthält ${profile.account.characters.length} Figuren. Dein aktueller lokaler Solo-Spielstand wird ersetzt. Onlinekonten werden nicht verändert.</p><button id="confirm-restore" class="primary-button">Sicherung wiederherstellen</button><button id="cancel-restore" class="secondary-button">Abbrechen</button>`);
    $('#cancel-restore').onclick=()=>screens.show('account');$('#confirm-restore').onclick=()=>{
      engine=candidate;playerId='local';state=engine.snapshot(playerId);saved=engine.profile(playerId);selectedClass=saved.classId;mode='offline';saveOffline();enterHUD();toast('Solo-Sicherung wiederhergestellt.');
    };
  }catch(error){if($('#restore-status'))$('#restore-status').textContent=error.message;else toast(error.message);}
}
async function connectSession(config){
  const r=await network.connect(config);onlineConfig={...config,token:r.token};putStorage('nyrathen.token.'+config.base,r.token);putStorage('nyrathen.online.config',{base:config.base,room:config.room});mode='online';playerId=r.playerId;state=r.snapshot;enterHUD();
  commerce.recoverPending().then(rows=>{if(rows.length)toast(`${rows.length} unvollständige Store-Transaktion${rows.length===1?'':'en'} sicher wiederhergestellt.`,true);}).catch(()=>{});
  return r;
}
function ownPlayer(){return state?.players.find(p=>p.id===playerId);}
function toast(text,rare=false){const d=document.createElement('div');d.className='toast'+(rare?' rare':'');d.textContent=text;$('#toast-stack').append(d);while($('#toast-stack').children.length>3)$('#toast-stack').firstElementChild.remove();setTimeout(()=>d.remove(),3500);}
function download(name,value){deliverFile(name,JSON.stringify(value,null,2),'application/json');}
function diagnostics(){download('Nyrathen-Fehlerbericht.json',{version:VERSION,date:new Date().toISOString(),mode,hostingMode:HOSTING_MODE,runtime:{native:HOSTING_MODE==='native',online:navigator.onLine},fps,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},userAgent:navigator.userAgent,online:navigator.onLine,errors,connection:mode==='online'?{...network.metrics,snapshotAgeMs:Date.now()-network.lastSnapshotAt}:null,world:state?{id:state.world.id,players:state.players.length,enemies:state.enemies.length,bullets:state.bullets.length}:null});}
function rememberError(e){const record={at:new Date().toISOString(),message:e?.message||String(e),stack:String(e?.stack||'').slice(0,2500)};errors.push(record);if(errors.length>20)errors.shift();putStorage(DIAGNOSTICS_KEY,errors);return record;}
function crash(e){const record=rememberError(e);$('#fatal-message').textContent=record.message;$('#fatal').classList.remove('hidden');$('#boot-status').classList.add('hidden');input.enabled=false;}
window.addEventListener('error',e=>crash(e.error||e.message));window.addEventListener('unhandledrejection',e=>crash(e.reason));$('#reload-btn').onclick=()=>location.reload();$('#error-log-btn').onclick=diagnostics;
function drawPortrait(canvas,id){const g=canvas.getContext('2d');g.clearRect(0,0,canvas.width,canvas.height);g.imageSmoothingEnabled=false;const sprite=renderer.sprite(id),h=canvas.height-3,w=h*sprite.width/sprite.height;g.drawImage(sprite,(canvas.width-w)/2,2,w,h);}
function drawItems(root=document){for(const canvas of root.querySelectorAll('canvas[data-slot]')){const g=canvas.getContext('2d');g.clearRect(0,0,canvas.width,canvas.height);g.imageSmoothingEnabled=false;g.drawImage(renderer.art.item(canvas.dataset.slot,Number(canvas.dataset.tier)||0,Number(canvas.dataset.rarity)||0,canvas.dataset.itemClass||'all'),0,0,canvas.width,canvas.height);}}
function chooseClass(id){if(!CLASSES[id])return;selectedClass=id;const ids=Object.keys(CLASSES),entry=CLASSES[id];document.querySelectorAll('.class-card').forEach(b=>{b.classList.toggle('selected',b.dataset.class===id);b.setAttribute('aria-pressed',String(b.dataset.class===id));drawPortrait(b.querySelector('canvas'),b.dataset.class);const label=b.querySelector('span');if(label)label.textContent=translateLocaleText(CLASSES[b.dataset.class]?.name||b.dataset.class);});drawPortrait($('#selected-class-portrait'),id);$('#selected-class-name').textContent=translateLocaleText(entry.name);$('#selected-class-role').textContent=translateLocaleText(entry.ability||'KLASSE').toUpperCase();$('#selected-class-index').textContent=String(ids.indexOf(id)+1).padStart(2,'0');$('#class-detail').textContent=translateLocaleText(entry.abilityHint||entry.ability);$('#save-note').textContent=translateLocaleText(saved?(saved.classId===id?'Deine Solo-Figur wird fortgesetzt. Tresor und Ruhm bleiben erhalten.':'Andere Klasse: Ein freier Charakterplatz wird genutzt. Deine Figuren bleiben erhalten.'):'Eigener Spielserver · kein Pay-to-Win · permanenter Charaktertod');}

function communityAccepted(){const value=getStorage(COMMUNITY_TERMS_KEY,null);return communityAcceptedSession||(value?.version===1&&value?.accepted===true);}
function communityRulesMarkup(review=false){return `<p><strong>Online-Spiel und Kommunikation sind nur mit Zustimmung zu diesen Community-Regeln möglich.</strong></p><ul class="legal-list"><li>Keine Belästigung, Hassrede, Drohungen, sexuelle Ausbeutung, personenbezogene Daten anderer oder gezielte Einschüchterung.</li><li>Kein Spam, Betrug, Identitätsvortäuschung, Cheating, Exploit-Missbrauch oder Handel mit Zugangsdaten.</li><li>Nutze Blockieren und Melden bei problematischem Verhalten. Serverbetreiber dürfen Inhalte einschränken, Chats stummschalten oder Konten sperren.</li><li>Öffentliche und Gruppen-Chats sind von anderen Spielern sichtbar. Teile dort keine Passwörter oder privaten Daten.</li></ul>${review?'<p class="modal-note">Diese Regeln gelten für alle Onlinefunktionen. Die Annahme kann lokal zurückgesetzt werden; für erneutes Online-Spiel ist dann eine neue Zustimmung erforderlich.</p><button id="community-back" class="primary-button">Zurück</button>':`<label class="toggle-row"><span>Ich akzeptiere die Community-Regeln und halte mich daran.</span><input id="community-rules-accept" type="checkbox"></label><button id="community-rules-continue" class="primary-button" disabled>Akzeptieren & Onlinebereich öffnen</button><button id="community-rules-cancel" class="secondary-button">Abbrechen</button>`}`;}
function showCommunityRules(next=showOnline,review=false){showModal('community-rules','Community-Regeln',communityRulesMarkup(review));if(review){$('#community-back').onclick=next;return;}const check=$('#community-rules-accept'),button=$('#community-rules-continue');check.onchange=()=>{button.disabled=!check.checked;};button.onclick=()=>{communityAcceptedSession=true;putStorage(COMMUNITY_TERMS_KEY,{version:1,accepted:true,acceptedAt:new Date().toISOString()});next();};$('#community-rules-cancel').onclick=()=>{closeModal();};}
function showLegal(){const links=legalHref('privacy','Datenschutzerklärung öffnen')+legalHref('terms','Nutzungsbedingungen öffnen')+legalHref('support','Support öffnen')+legalHref('deleteAccount','Externe Kontolöschung öffnen');showModal('legal','Datenschutz & Community',`<h3>Datenschutz in der App</h3><p>Nyrathen benötigt für den Spielbetrieb einen lokalen Spielstand und bei Onlinebetrieb Serverdaten wie Konto-/Gastkennung, Figurenfortschritt, soziale Verknüpfungen, Moderationsmeldungen und technische Sitzungsdaten. Es sind keine Werbe- oder Analyse-SDKs eingebaut.</p><p class="modal-note">Der jeweilige Serverbetreiber ist für seine Serverdaten verantwortlich. Konten können in der App gelöscht werden; lokale Solo-Daten lassen sich in den Einstellungen löschen.</p>${links||'<p class="modal-note">Die finalen öffentlichen Rechts- und Support-URLs werden im signierten Store-Build eingebettet.</p>'}<h3>Community</h3><p>Onlinekommunikation unterliegt den Community-Regeln. Blockieren und Melden sind direkt in der App verfügbar.</p><button id="review-community-rules" class="secondary-button">Community-Regeln anzeigen</button><button id="legal-back" class="primary-button">Zurück</button>`);$('#review-community-rules').onclick=()=>showCommunityRules(showLegal,true);$('#legal-back').onclick=showSettings;}

function showModal(kind,title,markup){modalKind=kind;modal.dataset.kind=kind;$('#modal-title').textContent=title;$('#modal-eyebrow').textContent='NYRATHEN · '+(mode==='online'?'DIE WELT LÄUFT WEITER':mode==='offline'?'SOLO PAUSIERT':'REALMS');content.innerHTML=markup;input.reset();input.enabled=false;if(!modal.open)modal.showModal();if(mode==='online')network.releaseInput();drawItems(content);}
function closeModal(){modalKind='';if(modal.open)modal.close();input.reset();}
$('#modal-close').onclick=()=>{if(modalKind==='trade')sendAction({type:'tradeCancel'});closeModal();};modal.addEventListener('cancel',()=>{if(modalKind==='trade')sendAction({type:'tradeCancel'});});modal.addEventListener('close',()=>{if(modal.open)return;modalKind='';input.reset();});modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){if(modalKind==='trade')sendAction({type:'tradeCancel'});closeModal();}}});
function saveOffline(){if(mode!=='offline'||!engine)return;saved=engine.profile(playerId);const bundle={version:3,profile:saved,worlds:engine.exportWorlds()};const ok=putStorage(SAVE_KEY,bundle);if(ok)saveBundle=bundle;if(!ok&&!storageWarning){storageWarning=true;toast('Browserspeicher gesperrt oder voll: Exportiere eine Solo-Sicherung unter Konto.');}}

function enterHUD(){closeModal();$('#menu-screen').classList.add('hidden');$('#hud').classList.remove('hidden');$('#network-banner').classList.add('hidden');deathSeen=false;lastEventSeen=state.events?.at(-1)?.seq||0;renderer.lastEvent=lastEventSeen;lastQuickSignature='';lastBagSignature='';lastChatSignature='';input.reset();input.auto=false;$('#auto-btn').classList.remove('on');$('#auto-btn').setAttribute('aria-pressed','false');drawPortrait($('#hud-avatar'),ownPlayer().classId);renderer.resize();audio.unlock();updateUI();}
function startOffline(){
  network.disconnect();const name=cleanName($('#player-name').value),profile=saved?{...saved,name}:{name,classId:selectedClass};
  engine=new AdventureEngine({savedWorld:saveBundle?.worlds||getStorage(WORLD_KEY,null)});playerId='local';const p=engine.addPlayer(playerId,name,profile.classId,profile);
  if(saved&&selectedClass!==p.classId){
    if(p.dead||engine.world(p).kind==='nexus'){const existing=p.account.characters.find(c=>c.profile.classId===selectedClass&&!c.profile.dead);if(existing)engine.action(playerId,{type:'characterSwitch',characterId:existing.id});else engine.action(playerId,{type:'characterCreate',classId:selectedClass,name});}
    else toast('Deine aktive Figur wird fortgesetzt. Klassenwechsel ist im Riftwacht möglich.');
  }
  state=engine.snapshot(playerId);mode='offline';accumulator=0;enterHUD();saveOffline();
}

function menu(){saveOffline();network.disconnect();closeModal();mode='menu';playerId='preview';$('#hud').classList.add('hidden');$('#menu-screen').classList.remove('hidden');engine=new AdventureEngine();engine.addPlayer(playerId,'Wanderer',selectedClass);state=engine.snapshot(playerId);chooseClass(selectedClass);renderer.resize();}
function contextKind(){const p=ownPlayer();if(!p)return null;if(p.dead)return{type:'rebirth',label:'Eine neue Seele'};const l=state.loot.find(l=>l.kind==='item'&&l.owner===p.id&&dist(l,p)<90);if(l)return{type:'interact',label:l.item.name+' aufnehmen'};
  const portal=state.portals.find(q=>dist(p,q)<115);if(portal)return{type:'portal',portalId:portal.id,label:portal.name+' betreten'};
  if(state.world.kind==='nexus'){for(const service of [{x:650,y:1160,section:'guild',label:'Gildenhalle'},{x:1100,y:1160,section:'forge',label:'Schmiede'},{x:420,y:1140,section:'quests',label:'Auftragstafel'},{x:1330,y:1140,section:'pets',label:'Gefährtengarten'}])if(dist(p,service)<115)return{type:'systemUI',section:service.section,label:service.label+' öffnen'};if(dist(p,{x:500,y:790})<145)return{type:'vaultUI',label:'Tresor öffnen · 16 sichere Plätze'};if(dist(p,{x:1260,y:790})<145)return{type:'refill',label:'Heil- und Manatränke auffüllen'};return{type:'atlasUI',label:'Eine Welt auswählen'};}return null;
}
async function sendAction(a){
  if(a.type==='interact'){const c=contextKind();if(c){if(c.type==='systemUI'){screens.show(c.section);return true;}if(c.type==='vaultUI'){showInventory(null,'vault');return true;}if(c.type==='atlasUI'){showAtlas();return true;}a=c;}}
  if(!['offline','online'].includes(mode))return false;
  let ok=false;if(mode==='offline'){ok=engine.action(playerId,a);state=engine.snapshot(playerId);saveOffline();}else ok=await network.action(a);
  if(ok&&['characterCreate','characterSwitch'].includes(a.type)){selectedClass=ownPlayer().classId;drawPortrait($('#hud-avatar'),selectedClass);deathSeen=false;}
  if(a.type==='rebirth'&&ok){deathSeen=false;closeModal();drawPortrait($('#hud-avatar'),ownPlayer().classId);}
  if(a.type==='realm'&&ok)closeModal();
  if(ok&&['equip','consume','deposit','withdraw','dropItem','salvage','refill','forge'].includes(a.type)){if(mode==='online')setTimeout(()=>{if(['inventory','vault'].includes(modalKind))renderInventory(modalKind);},160);else if(['inventory','vault'].includes(modalKind))renderInventory(modalKind);}
  if(!ok&&mode==='online')toast('Aktion nicht möglich. Prüfe Reichweite, Abklingzeit oder Verbindung.');
  return ok;
}
function itemMarkup(item,selected=false,extra=''){
  if(!item)return'<div class="item-cell empty"><span>LEER</span></div>';
  return `<button class="item-cell ${selected?'selected':''}" data-item="${htmlEscape(item.id)}" ${extra} style="border-color:${RARITIES[item.rarity]?.color||'#9ba88d'}"><canvas width="32" height="32" data-slot="${item.slot}" data-item-class="${htmlEscape(item.classId||'all')}" data-tier="${item.tier||0}" data-rarity="${item.rarity}"></canvas><span>${htmlEscape(item.name)}</span><small>${item.slot==='potion'?'STAT':item.rarity===3?'REL':`T${item.tier||0}`}</small></button>`;
}
function showInventory(itemId=null,kind='inventory'){selectedItem=itemId;renderInventory(kind,true);}
function renderInventory(kind=modalKind,open=false){
  const p=ownPlayer();if(!p)return;const pool=kind==='vault'?p.vault:p.inventory;
  const item=[...p.inventory,...p.vault,...Object.values(p.equipment)].filter(Boolean).find(i=>i.id===selectedItem),inBag=p.inventory.some(v=>v.id===selectedItem),inVault=p.vault.some(v=>v.id===selectedItem),nearVault=state.world.kind==='nexus'&&dist(p,{x:500,y:790})<145;
  const comparison=compareEquipment(item,p);
  const compareMarkup=comparison?`<div class="equipment-comparison ${comparison.delta>0?'upgrade':comparison.delta<0?'downgrade':''}"><span>${comparison.same?'ANGELEGT':'VERGLEICH ZUM ANGELEGTEN GEGENSTAND'}</span><b>${comparison.same?'Aktiv':(comparison.delta>0?'+':'')+comparison.delta+' Gegenstandswert'}</b><small>${htmlEscape(comparison.currentName)}${comparison.compatible?'':' · Nicht für diese Klasse'}</small></div>`:'';
  const detail=item?`<h3>${htmlEscape(item.name)}</h3><p>${SLOT_LABELS[item.slot]} · ${RARITIES[item.rarity].name} · ${item.classId==='all'?'Alle Klassen':CLASSES[item.classId]?.name||p.classId}</p><p>${item.slot==='potion'?STAT_LABELS[item.statKey]+' +1 dauerhaft; beim Tod verloren.':`Gegenstandswert +${item.stat} · Tier ${item.tier||0}`}</p>${compareMarkup}<div class="item-actions">${inBag?(item.slot==='potion'?'<button data-act="consume">Trinken</button>':`<button data-act="equip" ${comparison&&!comparison.compatible?'disabled':''}>Anlegen</button>`):''}${inBag&&nearVault?'<button data-act="deposit">Im Tresor sichern</button>':''}${inVault&&nearVault?'<button data-act="withdraw">Ins Gepäck nehmen</button>':''}${inBag&&state.world.kind==='nexus'?'<button data-act="salvage">Zerlegen</button>':''}${inBag?'<button data-act="dropItem">Fallen lassen</button>':''}</div>`:'<p>Wähle einen Gegenstand. Beim Tod gehen Ausrüstung und Gepäck verloren. Der Tresor bleibt erhalten.</p>';
  const markup=`<div class="inventory-top"><span>STUFE ${p.level} · ${CLASSES[p.classId].name}</span><span>◆ ${p.bank} gesichert · ${p.runCoins} im Lauf</span><span>✦ ${p.characterFame} Charakterruhm</span></div><div class="equipment-grid">${EQUIP_SLOTS.map(s=>itemMarkup(p.equipment[s],p.equipment[s]?.id===selectedItem)).join('')}</div><div class="subheading">${kind==='vault'?'TRESOR · '+p.vault.length+' / '+vaultCapacity(p.account):'GEPÄCK · '+p.inventory.length+' / 8'}</div><div class="item-grid">${Array.from({length:kind==='vault'?vaultCapacity(p.account):8},(_,i)=>itemMarkup(pool[i],pool[i]?.id===selectedItem)).join('')}</div>${kind==='vault'?'<p class="modal-note">Sichere Gegenstände aus deinem Gepäck über die Auswahl unten. Ein- und Auslagern ist nur direkt am Tresor im Riftwacht möglich.</p><div class="subheading">DEIN GEPÄCK</div><div class="item-grid">'+Array.from({length:8},(_,i)=>itemMarkup(p.inventory[i],p.inventory[i]?.id===selectedItem)).join('')+'</div>':''}<div class="item-detail">${detail}</div><div class="modal-stats">${Object.keys(STAT_CAPS).map(k=>`<div><b>${p.bonuses[k]} / ${STAT_CAPS[k]}</b><small>${STAT_LABELS[k].toUpperCase()}</small></div>`).join('')}</div>${state.world.kind==='nexus'?'<button id="refill-button" class="secondary-button">Heil- und Manatränke kostenlos auffüllen</button>':''}`;
  if(open||!modal.open)showModal(kind,kind==='vault'?'Dein Tresor':'Ausrüstung & Gepäck',markup);else{content.innerHTML=markup;drawItems(content);}
  for(const b of content.querySelectorAll('[data-item]'))b.onclick=()=>{selectedItem=b.dataset.item;renderInventory(kind);};
  for(const b of content.querySelectorAll('[data-act]'))b.onclick=()=>sendAction({type:b.dataset.act,itemId:selectedItem});$('#refill-button')?.addEventListener('click',()=>sendAction({type:'refill'}));
  lastBagSignature=JSON.stringify([p.inventory,p.equipment,p.vault,p.bonuses,p.potions,p.manaPotions,p.bank]);
}
function showDeath(){const p=ownPlayer();deathSeen=true;showModal('death','Dieses Leben ist vorbei.',`<p>Dein Charakter, seine Ausrüstung, das Gepäck und die getrunkenen Stat-Tränke sind verloren. Tresor, gesicherte Riftmarken und Kontoruhm bleiben.</p><div class="inventory-top"><span>STUFE ${p.deathRecord?.level||1}</span><span>✦ ${p.deathRecord?.fame||0} RUHM GESICHERT</span><span>${htmlEscape(p.deathRecord?.killer||'Kreatur')}</span></div><label class="field"><span>DEINE NÄCHSTE KLASSE</span><select id="rebirth-class">${Object.entries(CLASSES).map(([id,c])=>`<option value="${id}" ${id===p.classId?'selected':''}>${c.name}</option>`).join('')}</select></label><button id="rebirth-btn" class="primary-button">Neue Figur im Riftwacht beginnen</button>`);$('#rebirth-btn').onclick=()=>sendAction({type:'rebirth',classId:$('#rebirth-class').value});}
function showAtlas(){const p=ownPlayer();showModal('atlas','Welten & Realms',`<p>Du bist in <strong>${htmlEscape(state.world.name)}</strong>. ${state.world.kind==='nexus'?'Wähle ein gemeinsames Realm. Alle Spieler dieses Realms teilen Gegner, Bosse und Portale.':'Kehre zur Riftwacht zurück, um ein anderes Realm zu betreten.'}</p><div class="realm-grid">${state.realms.map(r=>`<div class="realm-card"><div class="eyebrow">OFFENES REALM</div><h3>Smaragd-${r.id==='realm-1'?'01':'02'}</h3><p>${r.players} / ${r.max} Spieler · ${r.closing?'SCHLIESST':'OFFEN'}</p><button data-realm="${r.id}" ${state.world.kind!=='nexus'||r.closing||p.dead?'disabled':''}>Realm betreten</button></div>`).join('')}</div>${state.world.kind==='realm'?'<div class="subheading">LEUCHTFEUER · 10 SEKUNDEN ABKLINGZEIT</div><div class="item-actions">'+['Küstenlicht','Waldlicht','Hochlandlicht'].map(n=>`<button data-beacon="${n}" ${p.teleportCd>0?'disabled':''}>${n}</button>`).join('')+'</div>':''}<button id="atlas-codex" class="secondary-button">Alle vierzehn Dungeons und Schlüssel ansehen</button><div class="subheading">DUNGEONS</div><p class="modal-note">Gezeitenhöhle, Dornenhain und Vergessene Krypta öffnen sich durch besiegte Gegner. Beim Abschluss des Realm-Fortschritts führt der gemeinsame Weg in die Aschenzitadelle. Die Levelangaben sind Empfehlungen, keine Zugangssperren.</p><button id="atlas-nexus" class="secondary-button" ${state.world.kind==='nexus'?'disabled':''}>Sofort zurück zur Riftwacht</button>`);
  $('#atlas-codex').onclick=()=>screens.show('dungeons');
  for(const b of content.querySelectorAll('[data-realm]'))b.onclick=()=>sendAction({type:'realm',target:b.dataset.realm});for(const b of content.querySelectorAll('[data-beacon]'))b.onclick=async()=>{if(await sendAction({type:'beacon',label:b.dataset.beacon}))closeModal();};$('#atlas-nexus').onclick=async()=>{if(await sendAction({type:'nexus'}))closeModal();};
}
function showParty(){const p=ownPlayer();showModal('party','Spieler & Gruppe',`<p>${state.players.filter(p=>p.connected).length} Spieler in ${htmlEscape(state.world.name)} · ${state.population} in dieser Region.</p>${state.party?`<div class="eyebrow">DEINE GRUPPE · ${state.party.members.length} / 8</div><div class="party-code">${state.party.id}</div><p class="modal-note">Teile den Gruppencode. Er ist keine Anmeldung und kein geheimer Kontoschlüssel.</p><button id="leave-party" class="secondary-button">Gruppe verlassen</button>`:'<button id="create-party" class="primary-button">Gruppe erstellen</button><label class="field"><span>MIT GRUPPENCODE BEITRETEN</span><input id="party-code" maxlength="12" placeholder="P0001" autocapitalize="characters"></label><button id="join-party" class="secondary-button">Gruppe beitreten</button>'}<div class="subheading">SPIELER IN DEINER WELT</div><div class="player-list">${state.players.map(q=>`<div class="player-row"><canvas width="30" height="36" data-player-class="${q.classId}"></canvas><div class="player-info"><strong>${htmlEscape(q.name)}${q.id===playerId?' · DU':''}</strong><small>${CLASSES[q.classId].name} · Stufe ${q.level} · ${q.dead?'GEFALLEN':Math.ceil(q.hp)+' / '+q.maxHP+' LP'}</small></div>${q.id!==playerId&&state.world.kind==='nexus'&&!q.dead?`<button data-trade-with="${q.id}">Handeln</button>`:''}${q.id!==playerId?`<button data-friend-with="${q.id}" ${state.friends?.contacts?.some(f=>f.id===q.id)||state.friends?.outgoing?.some(f=>f.id===q.id)?'disabled':''}>${state.friends?.contacts?.some(f=>f.id===q.id)?'Freund':state.friends?.outgoing?.some(f=>f.id===q.id)?'Angefragt':'Freund +'}</button><button data-teleport="${q.id}" ${state.world.kind!=='realm'||q.dead||p.teleportCd>0?'disabled':''}>Teleport</button>`:''}</div>`).join('')}</div>${state.party?'<div class="subheading">GRUPPENMITGLIEDER</div><p class="modal-note">'+state.party.members.map(q=>`${htmlEscape(q.name)} · ${htmlEscape(q.worldId)}${q.dead?' · gefallen':''}`).join('<br>')+'</p>':''}<p class="modal-note">Teleport funktioniert zwischen lebenden Spielern im selben Realm, nicht in Dungeons. Abklingzeit: 10 Sekunden. Gruppenchat ist privat für die aktuelle Gruppe. Handel findet ausschließlich zwischen nahen Spielern im Riftwacht statt.</p>`);
  for(const b of content.querySelectorAll('[data-trade-with]'))b.onclick=async()=>{if(await sendAction({type:'tradeInvite',playerId:b.dataset.tradeWith}))screens.showTrade();};
  for(const b of content.querySelectorAll('[data-friend-with]'))b.onclick=async()=>{if(await sendAction({type:'friendRequest',playerId:b.dataset.friendWith}))showParty();};
  for(const c of content.querySelectorAll('[data-player-class]'))drawPortrait(c,c.dataset.playerClass);
  const refresh=async a=>{if(await sendAction(a))setTimeout(()=>{if(modalKind==='party')showParty();},180);};
  $('#create-party')?.addEventListener('click',()=>refresh({type:'partyCreate'}));$('#leave-party')?.addEventListener('click',()=>refresh({type:'partyLeave'}));$('#join-party')?.addEventListener('click',()=>refresh({type:'partyJoin',code:$('#party-code').value}));
  for(const b of content.querySelectorAll('[data-teleport]'))b.onclick=async()=>{if(await sendAction({type:'teleport',playerId:b.dataset.teleport}))closeModal();};
}
function chatMarkup(){return state.chat.map(m=>`<div class="chat-line ${m.system?'system':''}"><b>${htmlEscape(m.name)}${m.directTo?' [DIREKT]':m.guildId?' [GILDE]':m.partyId?' [GRUPPE]':''}:</b> ${htmlEscape(m.text)}</div>`).join('');}
function showChat(channel='realm',targetId=''){if(typeof channel!=='string')channel='realm';const friends=state.friends?.contacts||[],hasFriends=friends.length>0;showModal('chat','Gemeinsam unterwegs',`<div id="chat-history" class="chat-history">${chatMarkup()||'<p>Noch keine Nachrichten.</p>'}</div><label class="field"><span>KANAL</span><select id="chat-channel"><option value="realm">Realm</option>${state.party?'<option value="party">Gruppe</option>':''}${state.guild?'<option value="guild">Gilde</option>':''}${hasFriends?'<option value="friend">Direkt an Freund</option>':''}</select></label>${hasFriends?`<label class="field" id="chat-target-field"><span>FREUND</span><select id="chat-target">${friends.map(f=>`<option value="${f.id}" ${f.online?'':'disabled'}>${htmlEscape(f.name)}${f.online?'':' · offline'}</option>`).join('')}</select></label>`:''}<form id="chat-form" class="chat-form"><input id="chat-input" maxlength="180" autocomplete="off" placeholder="Nachricht …" aria-label="Nachricht"><button type="submit">Senden</button></form><p class="modal-note">Realm-, Gruppen- und Gildenchat sind auf ihren Kanal begrenzt. Direkte Nachrichten erreichen nur den ausgewählten Freund in derselben Serverregion. Chat wird nicht dauerhaft gespeichert.</p>`);const channelNode=$('#chat-channel'),target=$('#chat-target'),targetField=$('#chat-target-field');const updateTarget=()=>{if(targetField)targetField.classList.toggle('hidden',channelNode.value!=='friend');};channelNode.value=hasFriends&&channel==='friend'?'friend':channel;if(target&&targetId&&[...target.options].some(o=>o.value===targetId&&!o.disabled))target.value=targetId;updateTarget();channelNode.onchange=updateTarget;$('#chat-form').onsubmit=async e=>{e.preventDefault();const text=$('#chat-input').value,selected=channelNode.value,payload={type:'chat',text,channel:selected};if(selected==='friend')payload.playerId=target?.value||'';if(await sendAction(payload))$('#chat-input').value='';};$('#chat-input').focus();}
function applySettings(){settings=cleanDisplaySettings(settings);audio.enabled=settings.sound;audio.volume=settings.volume;renderer.lowQuality=settings.quality==='low';renderer.reducedMotion=settings.reducedMotion;renderer.zoom=settings.zoom;renderer.allyOpacity=settings.allyOpacity;renderer.damageNumbers=settings.damageNumbers;renderer.objectives=settings.objectives;renderer.resize();putStorage(SETTINGS_KEY,settings);}
function showSettings(){
  showModal('settings','Einstellungen',`<label class="field"><span>SPRACHE / LANGUAGE</span><select id="language-setting">${NYR_SUPPORTED_LOCALES.map(locale=>`<option value="${locale}" ${getLocale()===locale?'selected':''}>${localeDisplayName(locale)}</option>`).join('')}</select></label><label class="toggle-row"><span>Spielsound</span><input id="sound-setting" type="checkbox" ${settings.sound?'checked':''}></label>
  <label class="field"><span>LAUTSTÄRKE</span><input id="volume-setting" type="range" min="0" max="100" value="${Math.round(settings.volume*100)}"></label>
  <label class="toggle-row"><span>Weniger Bewegung</span><input id="motion-setting" type="checkbox" ${settings.reducedMotion?'checked':''}></label>
  <label class="toggle-row"><span>Schadenszahlen</span><input id="numbers-setting" type="checkbox" ${settings.damageNumbers?'checked':''}></label>
  <label class="toggle-row"><span>Zielmarkierung am Bildrand</span><input id="objectives-setting" type="checkbox" ${settings.objectives?'checked':''}></label>
  <div class="settings-columns"><label class="field"><span>GRAFIK</span><select id="quality-setting"><option value="high" ${settings.quality==='high'?'selected':''}>Hohe Auflösung</option><option value="low" ${settings.quality==='low'?'selected':''}>Akkuschonend · 30 Bilder/s</option></select></label>
  <label class="field"><span>KAMERA-ZOOM</span><select id="zoom-setting">${[.8,1,1.2,1.4].map(v=>`<option value="${v}" ${settings.zoom===v?'selected':''}>${v*100}%</option>`).join('')}</select></label>
  <label class="field"><span>ANDERE SPIELER</span><select id="opacity-setting">${[[1,'Deckend'],[.65,'65% sichtbar'],[.35,'35% sichtbar']].map(([v,name])=>`<option value="${v}" ${settings.allyOpacity===v?'selected':''}>${name}</option>`).join('')}</select></label></div>
  <p class="modal-note">Gegner und gegnerische Projektile bleiben immer vollständig sichtbar.</p>
  <p class="modal-note">${mode==='online'?'Online pausiert kein Fenster die Welt. Bei Verbindungsverlust bleibt die Figur zunächst 15 Sekunden verwundbar. Kehre vor dem Beenden zur Riftwacht zurück.':'Solo pausiert die Welt, wenn ein Menü geöffnet ist. Lokale Speicherung benötigt freigegebenen Browserspeicher.'}</p>
  ${mode!=='menu'?'<button id="resume-button" class="primary-button">Zurück zum Spiel</button><button id="main-menu-button" class="secondary-button">Zum Hauptmenü</button>':''}
  ${mode==='online'?'<button id="connection-button" class="secondary-button">Verbindung & Einladung</button><button id="safety-button" class="secondary-button">Spieler blockieren oder melden</button>':''}
  
  <p class="modal-note"><strong>Nyrathen ist ein eigenständiges Originalspiel.</strong> Keine Verbindung, Autorisierung oder Zugehörigkeit zu anderen Spielen oder Publishern.</p>
  <p class="modal-note">Release-Diagnose: ${navigator.onLine?'Netzwerk online':'Netzwerk offline'} · ${HOSTING_MODE==='native'?'Native App-Runtime':'Entwicklungs-Runtime'} · ${errors.length} gespeicherte Fehler.</p>
  <button id="legal-button" class="secondary-button">Datenschutz & Community-Regeln</button><button id="diagnostics-button" class="secondary-button">Fehlerbericht speichern</button>${errors.length?'<button id="clear-errors-button" class="secondary-button">Fehlerhistorie löschen</button>':''}<button id="reset-button" class="secondary-button">Solo-Spielstand löschen</button><p class="modal-note">Entwicklungsstand ${VERSION} · eigener Server · optionale Cosmetics & Account-Komfort über Apple/Google.</p>`);
  const binding=[['sound-setting','sound','checked'],['motion-setting','reducedMotion','checked'],['numbers-setting','damageNumbers','checked'],['objectives-setting','objectives','checked'],['quality-setting','quality','value'],['zoom-setting','zoom','value'],['opacity-setting','allyOpacity','value']];
  for(const [id,key,prop]of binding)$('#'+id).onchange=e=>{settings[key]=['zoom','allyOpacity'].includes(key)?Number(e.target[prop]):e.target[prop];applySettings();if(settings.sound)audio.unlock();};
  $('#volume-setting').oninput=e=>{settings.volume=Number(e.target.value)/100;applySettings();};
  $('#language-setting').onchange=e=>setLocale(e.target.value);
  $('#resume-button')?.addEventListener('click',closeModal);$('#main-menu-button')?.addEventListener('click',menu);$('#connection-button')?.addEventListener('click',showConnection);$('#safety-button')?.addEventListener('click',showSafety);$('#legal-button').onclick=showLegal;$('#diagnostics-button').onclick=diagnostics;$('#clear-errors-button')?.addEventListener('click',()=>{errors.length=0;removeStorage(DIAGNOSTICS_KEY);showSettings();});
  $('#reset-button').onclick=()=>{showModal('delete','Solo-Spielstand löschen?',`<p>Die Solo-Figuren, ihr Tresor und die lokale Welt werden dauerhaft gelöscht. Online-Daten bleiben unverändert.</p><button id="confirm-delete" class="primary-button">Dauerhaft löschen</button><button id="cancel-delete" class="secondary-button">Abbrechen</button>`);$('#confirm-delete').onclick=()=>{for(const key of [SAVE_KEY,WORLD_KEY,'nyrathen.offline.v1','nyrathen.offline.v2'])removeStorage(key);saved=null;saveBundle=null;selectedClass='weaver';if(mode==='offline')mode='menu';menu();};$('#cancel-delete').onclick=showSettings;};
}
function showConnection(){
  const invite=makeInvitation(network.base,network.room);
  showModal('connection','Dein gemeinsames Realm',`<div class="connection-grid"><div><small>ANTWORTZEIT</small><strong>${network.metrics.rtt} ms</strong></div><div><small>WIEDERVERBUNDEN</small><strong>${network.metrics.reconnects}×</strong></div><div><small>REGION</small><strong>${htmlEscape(network.room)}</strong></div></div><p class="modal-note">Empfangene Spieldaten: ${(network.metrics.wireBytes/1024/1024).toFixed(2)} MB · ${network.metrics.deltaFrames} Differenzpakete · ${network.metrics.fullFrames} Vollzustände. Ohne HTTP/TLS-Overhead.</p><p>Dieser Link enthält nur Server und Region, niemals deinen Zugangsschlüssel. Mitspieler starten im Riftwacht.</p><label class="field"><span>EINLADUNG</span><input id="share-link" readonly value="${htmlEscape(invite)}"></label><button id="copy-invite" class="primary-button">Einladungslink kopieren</button><p id="share-status" role="status"></p><p class="modal-note">Lokal im WLAN ist der Server nur dort erreichbar. Für Internet-Spieler wird eine öffentliche HTTPS-Adresse benötigt.</p>`);
  $('#copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText(invite);$('#share-status').textContent='Einladung kopiert.';}catch{$('#share-link').focus();$('#share-link').select();$('#share-status').textContent='Link markiert. Über das Textmenü kopieren.';}};
}


function showSafety(){
  if(mode!=='online')return;
  const blocked=new Map((state.safety?.blocked||[]).map(p=>[p.id,p.name]));
  const candidates=new Map(state.players.filter(p=>p.id!==playerId).map(p=>[p.id,p.name]));
  for(const [id,name] of blocked)candidates.set(id,name);
  showModal('safety','Spieler & Sicherheit',`<p>Blockierte Konten können dir keine Chatnachrichten oder Handelsanfragen senden. Figuren und Geschosse bleiben sichtbar; Kämpfe werden dadurch nicht verändert.</p>${state.safety?.chatMutedUntil?`<p class="account-status">Dein Chat ist bis ${htmlEscape(new Date(state.safety.chatMutedUntil).toLocaleString(localeTag()))} eingeschränkt: ${htmlEscape(state.safety.chatMuteReason)}</p>`:''}<div class="safety-list">${[...candidates].map(([id,name])=>`<div class="safety-row"><strong>${htmlEscape(name)}</strong><span>${blocked.has(id)?'BLOCKIERT':'SICHTBAR'}</span><div><button data-block-player="${htmlEscape(id)}" data-enable="${blocked.has(id)?'false':'true'}">${blocked.has(id)?'Freigeben':'Blockieren'}</button><button data-report-player="${htmlEscape(id)}">Melden</button></div></div>`).join('')||'<p class="empty-state">Keine anderen Spieler in dieser Welt und keine blockierten Konten.</p>'}</div><p id="safety-status" role="status"></p><p class="modal-note">Eine Meldung geht nur an den Betreiber dieses Servers. Der Server übernimmt höchstens die letzte sichtbare Nachricht als Beleg, keine Passwörter. Meldungen werden höchstens 30 Tage und maximal 2.000 Einträge aufbewahrt. Eine Bearbeitung durch den Betreiber ist nicht automatisch garantiert.</p>`);
  for(const button of content.querySelectorAll('[data-block-player]'))button.onclick=async()=>{
    button.disabled=true;
    try{const result=await network.api('/api/safety/block','POST',{playerId:button.dataset.blockPlayer,enabled:button.dataset.enable==='true'});if(modalKind==='safety'){state.safety=result;showSafety();}}catch(error){if($('#safety-status'))$('#safety-status').textContent=error.message;button.disabled=false;}
  };
  for(const button of content.querySelectorAll('[data-report-player]'))button.onclick=()=>{
    const id=button.dataset.reportPlayer;showModal('report','Spieler melden',`<p>Du meldest <strong>${htmlEscape(candidates.get(id))}</strong> an den Serverbetreiber. Bitte wähle den zutreffenden Grund.</p><label class="field"><span>GRUND</span><select id="report-reason"><option value="harassment">Belästigung</option><option value="spam">Spam</option><option value="cheating">Verdacht auf Cheating</option><option value="other">Anderes Problem</option></select></label><button id="submit-report" class="primary-button">Meldung verbindlich senden</button><button id="cancel-report" class="secondary-button">Abbrechen</button><p id="report-status" role="status"></p>`);
    $('#cancel-report').onclick=showSafety;$('#submit-report').onclick=async()=>{
      const submit=$('#submit-report');submit.disabled=true;
      try{const report=await network.api('/api/safety/report','POST',{playerId:id,reason:$('#report-reason').value});if(modalKind==='report'){$('#report-status').textContent=(report.duplicate?'Diese Meldung liegt bereits vor. ':'Meldung gespeichert. ')+'Referenz: '+report.reference;submit.textContent='Gespeichert';}}
      catch(error){if($('#report-status'))$('#report-status').textContent=error.message;submit.disabled=false;}
    };
  };
}

function showOnline(){
  if(!communityAccepted()){showCommunityRules(showOnline);return;}
  const remembered=invitation||getStorage('nyrathen.online.config',{});let here='';try{if(HOSTING_MODE==='integrated'&&['http:','https:'].includes(location.protocol))here=GameNetwork.validBase(location.origin);}catch{}
  const defaultBase=remembered.base||advertisedServer||here;const serverHint=defaultBase?'Ein Server ist für diesen Build voreingestellt; „Server prüfen“ zeigt seinen Live-Status.':'Dieser App-Build enthält keinen Multiplayer-Server. Trage die öffentliche HTTPS-Adresse eines Nyrathen-Servers ein.';
  showModal('online','Gemeinsam im Realm',`<p>Verbinde dich und deine Mitspieler mit <strong>demselben Server und derselben Region</strong>. Danach trefft ihr euch im Riftwacht.</p><label class="field"><span>SERVERADRESSE</span><input id="server-url" type="url" placeholder="https://dein-server.example" value="${htmlEscape(defaultBase)}" autocapitalize="off" spellcheck="false"></label><label class="field"><span>REGION</span><input id="room-code" value="${htmlEscape(remembered.room||'PUBLIC')}" maxlength="12" autocapitalize="characters" spellcheck="false"></label><p class="modal-note">64 Verbindungen pro Region; 40 Plätze je Realm. ${serverHint} Ein neuer Gast erhält eine eigene Figur, die auf diesem Server gespeichert wird. Bestehende Gäste behalten ihre bisherige Klasse.</p><button id="probe-server" class="secondary-button">Server prüfen</button><div id="server-report" aria-live="polite"></div><details class="invite-details"><summary>Einladungslink einfügen</summary><label class="field"><span>LINK DES MITSPIELERS</span><input id="invite-input" type="url" placeholder="https://…/#join=PUBLIC"></label><button id="apply-invite" class="secondary-button">Einladung übernehmen</button></details><button id="connect-button" class="primary-button"><span>Riftwacht betreten</span><b>↗</b></button><p id="connect-error" class="form-error"></p><button id="account-login-btn" class="secondary-button">Mit bestehendem Konto anmelden</button><button id="forget-token" class="secondary-button">Lokalen Gastzugang für diesen Server vergessen</button>`);
  $('#apply-invite').onclick=()=>{try{const value=parseInvitation($('#invite-input').value);$('#server-url').value=value.base;$('#room-code').value=value.room;$('#connect-error').textContent='Einladung übernommen. Zum Beitreten „Riftwacht betreten“ wählen.';}catch(error){$('#connect-error').textContent=error.message;}};
  $('#probe-server').onclick=async()=>{
    const button=$('#probe-server'),report=$('#server-report');button.disabled=true;report.textContent='Server wird geprüft …';
    try{
      const base=GameNetwork.validBase($('#server-url').value.trim()),start=performance.now();
      const response=await fetch(base+'/health',{signal:GameNetwork.timeout(6000),credentials:'omit'});const health=await response.json();
      if(!response.ok||!health.ok)throw new Error('Server ist nicht spielbereit.');if(health.protocol!==2)throw new Error('Spielversion nicht kompatibel.');
      const latency=Math.round(performance.now()-start);report.textContent=`Bereit · Version ${health.version} · ${latency} ms · ${health.players||0} verbunden`;
      const r=await fetch(base+'/api/realms',{signal:GameNetwork.timeout(6000),credentials:'omit'});if(r.ok){const data=await r.json();for(const region of data.regions||[]){const b=document.createElement('button');b.className='region-choice';b.textContent=region.name+' · '+region.players+'/'+region.max;b.onclick=()=>{$('#room-code').value=normalizeRegion(region.name);};report.append(b);}}
    }catch(error){report.textContent=error.message||'Server nicht erreichbar.';}finally{button.disabled=false;}
  };
  $('#connect-button').onclick=async()=>{
    const b=$('#connect-button'),err=$('#connect-error');b.disabled=true;err.textContent='';
    try{const base=GameNetwork.validBase($('#server-url').value.trim()),room=$('#room-code').value.trim().toUpperCase();if(!/^[A-Z0-9]{3,12}$/.test(room))throw new Error('Region: 3–12 Buchstaben oder Ziffern.');const config={base,bases:advertisedServers.filter(x=>x!==base),room,name:cleanName($('#player-name').value),classId:selectedClass,token:getStorage('nyrathen.token.'+base,'')};const r=await network.connect(config);if(!modal.open||modalKind!=='online'){network.disconnect();return;}onlineConfig={...config,token:r.token};putStorage('nyrathen.token.'+base,r.token);putStorage('nyrathen.online.config',{base,room});mode='online';playerId=r.playerId;state=r.snapshot;enterHUD();}
    catch(e){network.disconnect();if($('#connect-error'))$('#connect-error').textContent=e.message||'Verbindung fehlgeschlagen.';b.disabled=false;}
  };
  $('#account-login-btn').onclick=()=>{try{const base=GameNetwork.validBase($('#server-url').value.trim()),room=$('#room-code').value.trim().toUpperCase();if(!/^[A-Z0-9]{3,12}$/.test(room))throw new Error('Ungültiger Regioncode.');screens.login({base,room,name:cleanName($('#player-name').value),classId:selectedClass});}catch(e){$('#connect-error').textContent=e.message;}};
  $('#forget-token').onclick=()=>{let base;try{base=GameNetwork.validBase($('#server-url').value.trim());}catch(e){$('#connect-error').textContent=e.message;return;}showModal('forget','Gastzugang vergessen?',`<p>Ein unregistrierter Gast ist ohne diesen Zugangsschlüssel nicht wiederherstellbar. Registrierte Konten können sich mit Kontoname und Passwort erneut anmelden. Die Serverdaten werden nicht gelöscht.</p><button id="confirm-forget" class="primary-button">Lokalen Zugang vergessen</button><button id="cancel-forget" class="secondary-button">Abbrechen</button>`);$('#confirm-forget').onclick=()=>{removeStorage('nyrathen.token.'+base);showOnline();};$('#cancel-forget').onclick=showOnline;};
}
function updateQuick(p){
  const signature=JSON.stringify([p.inventory,p.equipment,p.bonuses,p.level,p.damage,p.defense,p.speed,p.interval,p.maxHP,p.maxMP,p.vitality,p.wisdom]);if(signature===lastQuickSignature)return;lastQuickSignature=signature;
  const quick=item=>item?`<button data-open-item="${htmlEscape(item.id)}" aria-label="${htmlEscape(item.name)}"><canvas width="30" height="30" data-slot="${item.slot}" data-item-class="${htmlEscape(item.classId||'all')}" data-tier="${item.tier||0}" data-rarity="${item.rarity}"></canvas><small>${item.slot==='potion'?'':item.rarity===3?'REL':'T'+(item.tier||0)}</small></button>`:'<button data-open-item="" aria-label="Gepäck öffnen"><span style="opacity:.3">·</span></button>';
  $('#quick-equipment').innerHTML=EQUIP_SLOTS.map(k=>quick(p.equipment[k])).join('');$('#quick-bag').innerHTML=Array.from({length:8},(_,i)=>quick(p.inventory[i])).join('');$('#bag-count').textContent=p.inventory.length+' / 8';
  $('#stats-grid').innerHTML=Object.keys(STAT_CAPS).map(k=>`<div class="stat-cell ${p.bonuses[k]>=STAT_CAPS[k]?'maxed':''}"><b>${Math.round(({atk:p.damage,def:p.defense,spd:p.speed,dex:1/p.interval,vit:p.vitality,wis:p.wisdom,life:p.maxHP,mana:p.maxMP})[k]||0)}</b><small>${k.toUpperCase()} <span>${p.bonuses[k]}/${STAT_CAPS[k]}</span></small></div>`).join('');drawItems($('#sidebar'));for(const b of document.querySelectorAll('[data-open-item]'))b.onclick=()=>showInventory(b.dataset.openItem);
}
function updateUI(){
  const p=ownPlayer();if(!p||mode==='menu')return;
  $('#hud-name').textContent=p.name;$('#hud-class').textContent=CLASSES[p.classId].name.toUpperCase();$('#level-badge').textContent=p.level;
  $('#health-fill').style.width=clamp(p.hp/p.maxHP,0,1)*100+'%';$('#health-text').textContent=Math.ceil(p.hp)+' / '+p.maxHP;
  $('#mana-fill').style.width=clamp(p.mp/p.maxMP,0,1)*100+'%';$('#mana-text').textContent=Math.floor(p.mp)+' / '+p.maxMP;
  $('#xp-fill').style.width=(p.level===20?100:clamp(p.xp/xpNeeded(p.level),0,1)*100)+'%';$('#bank-coins').textContent=p.bank;$('#premium-shards').textContent=p.account?.commerce?.shards||0;$('#mobile-bank-coins').textContent=p.bank;$('#mobile-premium-shards').textContent=p.account?.commerce?.shards||0;$('#fame-count').textContent=p.fame;
  $('#potion-count').textContent=p.potions;$('#mana-potion-count').textContent=p.manaPotions;
  $('#zone-title').textContent=state.world.name.toUpperCase();const modText=state.world.kind==='dungeon'&&state.world.modifiers?.length?' · '+state.world.modifiers.map(id=>state.progression?.dungeonModifiers?.[id]?.name||id).join(' · '):'';$('#wave-label').textContent=(state.world.kind==='nexus'?'DIE GEMEINSAME ZUFLUCHT':state.world.kind==='realm'?(state.world.closingIn?'SCHLIESST IN '+Math.ceil(state.world.closingIn)+' s':'KÜSTE · WALD · HOCHLAND'):DUNGEONS[state.world.theme].subtitle.toUpperCase())+modText;
  $('#mode-label').textContent=mode==='online'?network.room:'SOLO';$('#party-count').textContent=state.players.filter(q=>q.connected).length+' SPIELER';
  $('#safe-badge').classList.toggle('hidden',!p.safe||p.dead);$('#safe-text').textContent=state.world.kind==='nexus'?'RIFTWACHT · HEILUNG & SICHERHEIT':'LEUCHTFEUER · SICHERE ZONE';
  const boss=state.enemies.filter(e=>isBoss(e.kind)&&dist(e,p)<850).sort((a,b)=>dist(a,p)-dist(b,p))[0];$('#boss-panel').classList.toggle('hidden',!boss);if(boss){$('#boss-name').textContent=ENEMY_TYPES[boss.kind].name;$('#boss-phase').textContent='PHASE '+boss.phase;$('#boss-fill').style.width=clamp(boss.hp/boss.maxHP,0,1)*100+'%';}
  const nexus=state.world.kind==='nexus',realm=state.world.kind==='realm';const liveMark=state.world.liveEvent?' · ROTATION':'';const echoMark=state.world.echo?' · ECHOPFAD':'';if(!nexus&&!realm)$('#zone-title').textContent=(state.world.name+echoMark+liveMark).toUpperCase();$('#quest-title').textContent=nexus?'Wähle deinen Weg':realm?'Befreie das Realm':state.world.completed?'Dungeon bezwungen':'Finde den Hüter';
  $('#quest-description').textContent=nexus?'Betritt ein Portal oder wähle ein Realm über die Karte.':realm?'Besiege Kreaturen und Ereignisbosse. Der Abschluss öffnet die Zitadelle.':state.world.completed?'Nimm deine persönliche Beute und kehre zur Riftwacht zurück.':'Folge den verbundenen Kammern bis zum Boss.';
  $('#quest-fill').style.width=(nexus?0:realm?clamp(state.world.score/state.world.scoreTarget,0,1)*100:state.world.completed?100:30)+'%';$('#quest-progress').textContent=nexus?'SICHERE ZONE':realm?Math.min(state.world.score,state.world.scoreTarget)+' / '+state.world.scoreTarget:'PERMADEATH AKTIV';
  $('#ability-cd').classList.toggle('hidden',p.abilityCd<=0);$('#ability-cd').textContent=Math.ceil(p.abilityCd);$('#ability-icon').textContent={warden:'▰',warrior:'⚑',ranger:'➶',weaver:'✦',cleric:'✚',shade:'◈',paladin:'☀',assassin:'♜',necromancer:'☠',huntress:'⌗',mystic:'◉',trickster:'◇',sorcerer:'ϟ',ninja:'✥',samurai:'╳',bard:'♪',summoner:'♟',kensei:'⟫',druid:'♧'}[p.classId];$('#ability-btn').title=CLASSES[p.classId].ability;$('#ability-btn').setAttribute('aria-label',CLASSES[p.classId].ability);
  const timerDefs=[['FÄHIGKEIT',p.abilityCd],['SCHILD',p.shield],['RASEREI',p.berserk],['ERMÄCHTIGT',p.empowered],['EILE',p.haste],['INSPIRIERT',p.inspired],['WILDGESTALT',p.formTimer],['UNSICHTBAR',p.invisible]];const timers=timerDefs.filter(([,v])=>Number(v)>0);const timerNode=$('#status-timers');timerNode.classList.toggle('hidden',!timers.length);timerNode.innerHTML=timers.map(([name,v])=>`<span class="status-chip">${name} · ${Number(v).toFixed(v<10?1:0)}s</span>`).join('');
  $('#ability-btn').disabled=p.dead||p.safe||p.abilityCd>0||p.mp<CLASSES[p.classId].cost;$('#heal-btn').disabled=p.dead||p.potions<=0||p.hp>=p.maxHP;$('#dash-btn').disabled=p.dead||p.manaPotions<=0||p.mp>=p.maxMP;$('#nexus-btn').disabled=p.dead||nexus;
  const ctx=contextKind();$('#context-action').classList.toggle('hidden',!ctx);$('#context-text').textContent=ctx?.label||'';updateQuick(p);
  screens.update();
  if(p.dead&&!deathSeen)showDeath();if(!p.dead)deathSeen=false;
  if(['inventory','vault'].includes(modalKind)&&lastBagSignature!==JSON.stringify([p.inventory,p.equipment,p.vault,p.bonuses,p.potions,p.manaPotions,p.bank]))renderInventory(modalKind);
  const chatSig=JSON.stringify(state.chat);if(chatSig!==lastChatSignature){lastChatSignature=chatSig;$('#chat-lines').innerHTML=state.chat.slice(-3).map(m=>`<div class="chat-line ${m.system?'system':''}"><b>${htmlEscape(m.name)}:</b> ${htmlEscape(m.text)}</div>`).join('');if(modalKind==='chat'&&$('#chat-history')){$('#chat-history').innerHTML=chatMarkup();$('#chat-history').scrollTop=$('#chat-history').scrollHeight;}}
  for(const e of state.events){if(e.seq<=lastEventSeen)continue;lastEventSeen=e.seq;if(e.playerId&&e.playerId!==playerId)continue;audio.play(e.type);if(e.type==='notice'||e.type==='travel')toast(e.text);if(e.type==='level')toast('Stufe '+e.level+' erreicht.',true);if(e.type==='loot')toast(e.text,true);if(e.type==='shiny')toast('✦ SCHIMMERFUND · '+(e.text||'Seltene Beute'),true);if(e.type==='bank'&&e.amount)toast(e.amount+' Riftmarken gesichert.',true);if(e.type==='victory')toast('Dungeon bezwungen. Deine Beute wartet.',true);}
}
$('#play-offline').onclick=()=>startOffline();$('#play-online').onclick=showOnline;$('#menu-settings').onclick=showSettings;$('#hud-settings').onclick=showSettings;$('#mobile-settings').onclick=showSettings;
$('#inventory-btn').onclick=()=>showInventory();$('#side-vault').onclick=()=>showInventory(null,'vault');$('#side-shop').onclick=()=>screens.show('shop');$('#journal-btn').onclick=()=>screens.show('characters');$('#side-journal').onclick=()=>screens.show('characters');$('#party-btn').onclick=showParty;$('#side-party').onclick=showParty;$('#atlas-btn').onclick=showAtlas;$('#chat-btn').onclick=showChat;
$('#heal-btn').onclick=()=>sendAction({type:'heal'});$('#dash-btn').onclick=()=>sendAction({type:'mana'});$('#ability-btn').onclick=()=>sendAction({type:'ability'});$('#nexus-btn').onclick=()=>sendAction({type:'nexus'});$('#context-btn').onclick=()=>sendAction({type:'interact'});
$('#auto-btn').onclick=()=>{input.auto=!input.auto;$('#auto-btn').classList.toggle('on',input.auto);$('#auto-btn').setAttribute('aria-pressed',String(input.auto));toast(input.auto?'Automatisches Zielen aktiv.':'Manuelles Zielen aktiv.');};
$('#reconnect-btn').onclick=async()=>{if(!onlineConfig)return;$('#reconnect-btn').disabled=true;try{const r=await network.connect(onlineConfig);state=r.snapshot;playerId=r.playerId;}catch(e){$('#network-message').textContent=e.message;}finally{$('#reconnect-btn').disabled=false;}};
window.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]')||e.repeat)return;if(mode==='menu')return;const k=e.key.toLowerCase();if(k==='escape'&&!modal.open)showSettings();if(modal.open)return;if(k==='c')screens.show('characters');if(k==='j')screens.show('quests');if(k==='l')screens.show('guild');if(k==='t')screens.showTrade();if(k==='i')showInventory();if(k==='p')showParty();if(k==='m')showAtlas();if(k==='enter'){e.preventDefault();showChat();}});
window.addEventListener('resize',()=>renderer.resize());window.addEventListener('pagehide',()=>{saveOffline();input.reset();if(mode==='online')network.releaseInput();});
document.addEventListener('visibilitychange',()=>{input.reset();if(document.hidden){saveOffline();audio.suspend();if(mode==='online')network.releaseInput();}else{lastFrame=performance.now();accumulator=0;if(settings.sound)audio.unlock();}});
window.NyrathenHost={resume:()=>{lastFrame=performance.now();accumulator=0;input.reset();},back:()=>{if(modal.open){closeModal();return true;}if(mode!=='menu'){showSettings();return true;}return false;},pause:()=>{saveOffline();input.reset();audio.suspend();if(mode==='online')network.releaseInput();}};
Object.defineProperty(window,'__nyrathen',{value:Object.freeze({state:()=>state?JSON.parse(JSON.stringify(state)):null,mode:()=>mode,fps:()=>fps,version:VERSION}),writable:false});
function frame(now){try{
  const dt=Math.min(.1,Math.max(0,(now-lastFrame)/1000));lastFrame=now;frameCount++;if(now-lastFPS>1000){fps=Math.round(frameCount*1000/(now-lastFPS));frameCount=0;lastFPS=now;}
  input.enabled=['offline','online'].includes(mode)&&(mode!=='online'||network.connected)&&!modal.open&&!document.hidden;const controls=input.read(ownPlayer());
  if(mode==='offline'&&!modal.open&&!document.hidden){accumulator=Math.min(.15,accumulator+dt);while(accumulator>=.05){engine.setInput(playerId,controls);engine.step(.05);accumulator-=.05;}state=engine.snapshot(playerId);}else accumulator=0;
  if(mode==='online'&&now-lastInputSend>65){lastInputSend=now;network.sendInput(controls);}
  renderDT+=dt;if(!renderer.lowQuality||now-lastRender>=1000/30){renderer.draw(state,playerId,renderDT,{menu:mode==='menu'});lastRender=now;renderDT=0;}if(now-lastUI>100){lastUI=now;updateUI();}if(now-lastSave>5000){lastSave=now;saveOffline();}
}catch(e){crash(e);return;}requestAnimationFrame(frame);}
try{
  $('#class-cards').innerHTML=Object.entries(CLASSES).map(([id,c])=>`<button class="class-card" data-class="${id}" aria-pressed="false"><canvas width="40" height="48"></canvas><span>${translateLocaleText(c.name)}</span></button>`).join('');for(const b of document.querySelectorAll('.class-card'))b.onclick=()=>chooseClass(b.dataset.class);
  $('#player-name').value=saved?.name||'Wanderer';applySettings();menu();$('#boot-status').classList.add('hidden');requestAnimationFrame(frame);
}catch(e){crash(e);}
