// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
// The panels use the same live state and authoritative actions as gameplay.
import { CLASSES, ENEMY_TYPES, RARITIES } from '../shared/data.mjs';
import { DUNGEONS, EQUIP_SLOTS } from '../shared/realm-data.mjs';
import { PETS, CONTRACTS, DUNGEON_KEYS, CHARACTER_SLOTS_MAX, CHARACTER_SLOT_COST, MASTERY_FAME_THRESHOLDS, masteryRank } from '../shared/adventure-data.mjs';
import { SYSTEM_UNLOCKS, accountXPForLevel, PET_RARITIES, PET_EGGS, PET_FOOD, ENCHANTMENTS, DUNGEON_MODIFIERS, ASCENSION_STATS, SEASON, SEASON_MISSIONS, seasonPassLevel, CRUCIBLE_MODES, FORGE_RECIPES, COSMETICS, itemQualityName, JOURNEY_STEPS, enchantRank } from '../shared/endgame-data.mjs';
import { PREMIUM_CURRENCY, SHOP_SEASON_ID, SHOP_TABS } from '../shared/monetization-data.mjs';
export class SystemScreens {
  constructor(context){this.c=context;this.section='characters';this.lastTrade='';this.lastGuild='';this.notifiedTrade='';this.accountInfo=null;this.shopTab='featured';this.shopPreview=null;}
  node(selector){return document.querySelector(selector);}
  esc(value){return this.c.escape(value);}
  draw(){this.c.drawItems(this.node('#modal-content'));for(const canvas of document.querySelectorAll('[data-class-portrait]'))this.c.portrait(canvas,canvas.dataset.classPortrait);for(const canvas of document.querySelectorAll('[data-pet-portrait]')){const g=canvas.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(this.c.renderer.art.pet(canvas.dataset.petPortrait),0,0,canvas.width,canvas.height);}}
  shell(title,markup){
    const p=this.c.own(),tabs=[['characters','Charaktere'],['progression','Fortschritt'],['season','Saison'],['quests','Aufträge'],['pets','Gefährten'],['mastery','Meisterschaft'],['enchanter','Verzauberer'],['storage','Lager'],['ranking','Rangliste'],['friends','Freunde'],['guild','Gilde'],['forge','Schmiede'],['dungeons','Dungeons'],['bestiary','Bestiarium'],...(this.c.mode()==='online'?[['shop','Schwarzer Tresen']]:[]),['account','Konto']];
    this.c.modal('systems',title,`<div class="systems-shell system-${this.section}"><div class="systems-tabs">${tabs.map(([id,label])=>`<button data-system="${id}" class="${this.section===id?'selected':''}">${label}</button>`).join('')}</div><div class="systems-summary"><span>◆ ${p.bank} RIFTMARKEN</span><span>◇ ${p.account?.commerce?.shards||0} ${PREMIUM_CURRENCY.toUpperCase()}</span><span>✦ ${p.fame} RUHM</span><span>${this.c.state().world.kind==='nexus'?'RIFTWACHT · SICHER':'IM REALM · WACH BLEIBEN'}</span></div><div class="system-body">${markup}</div></div>`);
    for(const b of document.querySelectorAll('[data-system]'))b.onclick=()=>this.show(b.dataset.system);this.draw();
  }
  async run(action,refresh=true){const ok=await this.c.action(action);if(ok&&refresh&&this.c.modalKind()==='systems')this.show(this.section);return ok;}
  show(section='characters'){if(!this.c.own())return;this.section=section;({characters:()=>this.characters(),progression:()=>this.progression(),season:()=>this.season(),quests:()=>this.quests(),pets:()=>this.pets(),mastery:()=>this.mastery(),enchanter:()=>this.enchanter(),storage:()=>this.storage(),ranking:()=>this.ranking(),friends:()=>this.friends(),guild:()=>this.guild(),forge:()=>this.forge(),dungeons:()=>this.dungeons(),bestiary:()=>this.bestiary(),shop:()=>this.shop(),account:()=>this.account()}[section]||(()=>this.characters()))();}
  characters(){
    const p=this.c.own(),a=p.account,allowed=p.dead||this.c.state().world.kind==='nexus';
    const slots=a.characterSlots||4,slotCost=CHARACTER_SLOT_COST(slots);
    this.shell('Deine Charaktere',`<p class="modal-note">${slots} freigeschaltete Charakterplätze teilen Tresor, Riftmarken, Ruhm und Gefährten. Ausrüstung und Level gehören zur jeweiligen Figur. Wechsel nur im Riftwacht oder nach dem Tod.</p><div class="character-roster">${a.characters.map(c=>`<article class="roster-card ${c.active?'active':''}"><canvas width="56" height="68" data-class-portrait="${c.classId}"></canvas><div><h3>${this.esc(c.name)}</h3><p>${CLASSES[c.classId].name} · Stufe ${c.level}</p><small>${c.seasonal?'SAISON · ':''}${c.crucibleMode?'PRÜFUNG · ':''}${c.dead?'GEFALLEN':c.active?'AKTIVE FIGUR':'IM RIFTWACHT'}</small></div><div class="roster-actions"><button data-switch="${c.id}" ${c.active||!allowed?'disabled':''}>${c.active?'Aktiv':'Auswählen'}</button>${!c.active?`<button data-delete-character="${c.id}" ${!allowed?'disabled':''} aria-label="${this.esc(c.name)} löschen">Löschen</button>`:''}</div></article>`).join('')}</div>${a.characters.length<slots?`<form id="new-character-form" class="new-character-form"><h3>Freier Platz ${a.characters.length+1} / ${slots}</h3><label class="field"><span>NAME</span><input id="new-character-name" value="${this.esc(p.name)}" maxlength="20" required></label><label class="field"><span>KLASSE</span><select id="new-character-class">${Object.entries(CLASSES).map(([id,c])=>`<option value="${id}">${c.name}</option>`).join('')}</select></label><label class="field checkbox-field"><span>SAISONFIGUR</span><input id="new-character-seasonal" type="checkbox"><small>Getrennter Saisonfortschritt und saisonales Lager.</small></label><button class="primary-button" type="submit" ${!allowed?'disabled':''}>Neue Figur erschaffen</button></form>`:`<p class="modal-note">Alle ${slots} freigeschalteten Plätze sind belegt. Nur inaktive Figuren können gelöscht werden.</p>${slots<CHARACTER_SLOTS_MAX?`<button id="buy-character-slot" class="secondary-button" ${!allowed||p.bank<slotCost?'disabled':''}>Weiteren Charakterplatz freischalten · ◆ ${slotCost}</button>`:'<p class="modal-note">Maximal acht Charakterplätze freigeschaltet.</p>'}`}`);
    for(const b of document.querySelectorAll('[data-switch]'))b.onclick=()=>this.run({type:'characterSwitch',characterId:b.dataset.switch});
    for(const b of document.querySelectorAll('[data-delete-character]'))b.onclick=()=>{
      const id=b.dataset.deleteCharacter;this.c.modal('confirm-character','Figur endgültig löschen?',`<p>Die Figur und ihre getragenen Gegenstände werden gelöscht. Der gemeinsame Tresor bleibt erhalten.</p><button id="confirm-character-delete" class="primary-button">Endgültig löschen</button><button id="cancel-character-delete" class="secondary-button">Abbrechen</button>`);
      this.node('#confirm-character-delete').onclick=async()=>{await this.run({type:'characterDelete',characterId:id,confirm:'DELETE'},false);this.show('characters');};this.node('#cancel-character-delete').onclick=()=>this.show('characters');
    };
    this.node('#new-character-form')?.addEventListener('submit',async e=>{e.preventDefault();await this.run({type:'characterCreate',classId:this.node('#new-character-class').value,name:this.node('#new-character-name').value,seasonal:this.node('#new-character-seasonal')?.checked===true});});
    this.node('#buy-character-slot')?.addEventListener('click',()=>this.run({type:'characterSlotPurchase'}));
  }
  progression(){
    const p=this.c.own(),a=p.account,level=a.accountLevel||1,next=accountXPForLevel(Math.min(50,level+1)),prev=accountXPForLevel(level),pct=level>=50?100:Math.max(0,Math.min(100,(a.accountXP-prev)/Math.max(1,next-prev)*100));
    const unlocks=Object.entries(SYSTEM_UNLOCKS).map(([id,need])=>`<article class="progression-row ${level>=need?'complete':''}"><strong>${{pets:'Gefährtenhof',enchanter:'Verzauberer',forge:'Schlackenschmiede',crucible:'Prüfungen'}[id]}</strong><span>${level>=need?'FREIGESCHALTET':'KONTOSTUFE '+need}</span></article>`).join('');
    const asc=Object.entries(CLASSES).map(([id,c])=>{const total=Object.values(a.ascension?.[id]||{}).reduce((n,v)=>n+v,0);return `<article class="mastery-card"><canvas width="38" height="48" data-class-portrait="${id}"></canvas><div><strong>${this.esc(c.name)}</strong><small>Erhebung ${total} / 40</small><div class="mastery-meter"><i style="width:${total/40*100}%"></i></div></div></article>`;}).join('');
    const titles=a.cosmetics?.titles||['Reisender'],skins=a.cosmetics?.skins||['default'],weaponStyles=a.cosmetics?.weaponStyles||['default'],petStyles=a.cosmetics?.petStyles||['default'];
    const journey=JOURNEY_STEPS.map(step=>{const raw=step.key==='ascensionTotal'?(a.ascensionTotal||0):(a.totals?.[step.key]||0),n=Math.min(step.goal,raw),claimed=(a.journeyClaims||[]).includes(step.id);return `<article class="contract-card ${claimed?'complete':''}"><div><h3>${this.esc(step.name)}</h3><p>${this.esc(step.description)}</p><div class="contract-meter"><i style="width:${n/step.goal*100}%"></i></div><small>${n} / ${step.goal}${step.reward.coins?' · ◆ '+step.reward.coins:''}${step.reward.fame?' · ✦ '+step.reward.fame:''}</small></div><button data-journey="${step.id}" ${claimed||n<step.goal||p.dead||this.c.state().world.kind!=='nexus'?'disabled':''}>${claimed?'Erhalten':'Abholen'}</button></article>`;}).join('');
    this.shell('Kontofortschritt',`<div class="mastery-total"><strong>STUFE ${level} / 50</strong><small>${a.accountXP} KONTO-EP · ${a.ascensionTotal||0} ERHEBUNGEN</small></div><div class="mastery-meter"><i style="width:${pct}%"></i></div><div class="subheading">DEINE REISE</div><p class="modal-note">Kurze kontoweite Ziele führen durch die wichtigsten Systeme. Belohnungen werden nur im Riftwacht abgeholt.</p><div class="contract-list">${journey}</div><div class="subheading">SYSTEMFREISCHALTUNGEN</div><div class="progression-list">${unlocks}</div><div class="subheading">ENDGAME-ERHEBUNGEN</div><p class="modal-note">Ab Stufe 20 erhöht jeder abgeschlossene Dungeon den zugeordneten Klassenwert dauerhaft bis Rang 5. Dieser Fortschritt ist getrennt von der kosmetischen Meisterschaft.</p><div class="mastery-grid">${asc}</div><div class="subheading">SAMMLUNG</div><label class="field"><span>TITEL</span><select id="cosmetic-title">${titles.map(v=>`<option value="${v}" ${v===a.cosmetics.activeTitle?'selected':''}>${this.esc(v)}</option>`).join('')}</select></label><label class="field"><span>ERSCHEINUNGSBILD</span><select id="cosmetic-skin">${skins.map(v=>`<option value="${v}" ${v===a.cosmetics.activeSkin?'selected':''}>${this.esc(v)}</option>`).join('')}</select></label><div class="cosmetic-loadout-row"><label class="field"><span>WAFFENSTIL</span><select id="cosmetic-weapon">${weaponStyles.map(v=>`<option value="${v}" ${v===a.cosmetics.activeWeaponStyle?'selected':''}>${this.esc(v)}</option>`).join('')}</select></label><label class="field"><span>GEFÄHRTENSTIL</span><select id="cosmetic-pet">${petStyles.map(v=>`<option value="${v}" ${v===a.cosmetics.activePetStyle?'selected':''}>${this.esc(v)}</option>`).join('')}</select></label></div><button id="apply-cosmetics" class="secondary-button">Loadout verwenden</button>`);
    for(const b of document.querySelectorAll('[data-journey]'))b.onclick=()=>this.run({type:'claimJourney',stepId:b.dataset.journey});
    this.node('#apply-cosmetics')?.addEventListener('click',async()=>{await this.run({type:'cosmetic',kind:'title',value:this.node('#cosmetic-title').value},false);await this.run({type:'cosmetic',kind:'skin',value:this.node('#cosmetic-skin').value},false);await this.run({type:'cosmetic',kind:'weaponStyle',value:this.node('#cosmetic-weapon').value},false);await this.run({type:'cosmetic',kind:'petStyle',value:this.node('#cosmetic-pet').value});});
  }
  season(){
    const p=this.c.own(),a=p.account,s=a.season||{xp:0,claims:[],passClaims:[],premiumClaims:[]},pass=seasonPassLevel(s.xp),seasonal=p.seasonal&&p.seasonId===SEASON.id,atHome=!p.dead&&this.c.state().world.kind==='nexus',premium=a.commerce?.seasonPremium?.includes(SHOP_SEASON_ID)===true;
    const missions=SEASON_MISSIONS.map(m=>{const n=Math.min(m.goal,a.totals[m.key]||0),claimed=s.claims.includes(m.id);return `<article class="contract-card ${claimed?'complete':''}"><div><h3>${m.name}</h3><p>${n} / ${m.goal}</p><div class="contract-meter"><i style="width:${n/m.goal*100}%"></i></div><small>+${m.xp} Saison-EP</small></div><button data-season-mission="${m.id}" ${!seasonal||claimed||n<m.goal?'disabled':''}>${claimed?'Erhalten':'Abholen'}</button></article>`;}).join('');
    const levels=Array.from({length:SEASON.maxPass},(_,i)=>i+1).map(l=>`<div class="pass-pair"><button data-pass-level="${l}" class="pass-level ${l<=pass?'ready':''} ${s.passClaims.includes(l)?'claimed':''}" ${!seasonal||l>pass||s.passClaims.includes(l)?'disabled':''}><b>${l}</b><small>FREI · ${s.passClaims.includes(l)?'✓':'BEUTE'}</small></button><button data-premium-level="${l}" class="pass-level premium ${l<=pass?'ready':''} ${s.premiumClaims?.includes(l)?'claimed':''}" ${!seasonal||!premium||l>pass||s.premiumClaims?.includes(l)?'disabled':''}><b>◇</b><small>${premium?(s.premiumClaims?.includes(l)?'✓':'PREMIUM'):'GESPERRT'}</small></button></div>`).join('');
    const crucible=Object.entries(CRUCIBLE_MODES).map(([id,c])=>`<article class="pet-card"><h3>${c.name}</h3><p>${c.description}</p><button data-crucible="${id}" ${!seasonal||!atHome||p.crucibleMode||!a.unlocks?.crucible?'disabled':''}>${p.crucibleMode===id?'Aktiv':'Aktivieren'}</button></article>`).join('');
    this.shell('Saison · '+SEASON.name,`<p class="modal-note">Saisonfiguren besitzen einen eigenen Missionspfad und ein saisonales Lager. Prüfungen sind freiwillige, dauerhafte Herausforderungen bis zum Tod der Figur.</p><div class="systems-summary"><span>${seasonal?'SAISONFIGUR':'REGULÄRE FIGUR'}</span><span>PASS ${pass} / ${SEASON.maxPass}</span><span>${s.xp} SAISON-EP</span></div><div class="subheading">MISSIONSPFAD</div><div class="contract-list">${missions}</div><div class="subheading">SAISONPFAD · ${premium?'PREMIUM AKTIV':'FREI'}</div>${premium?'':`<p class="modal-note">Der kostenlose Pfad bleibt vollständig spielbar. Premium schaltet nur zusätzliche Cosmetics und Nyr-Splitter frei.</p><button id="season-shop" class="secondary-button">Schleierpass im Schwarzen Tresen ansehen</button>`}<div class="pass-grid">${levels}</div><div class="subheading">PRÜFUNGEN</div><div class="pet-grid">${crucible}</div>`);
    for(const b of document.querySelectorAll('[data-season-mission]'))b.onclick=()=>this.run({type:'claimSeasonMission',missionId:b.dataset.seasonMission});for(const b of document.querySelectorAll('[data-pass-level]'))b.onclick=()=>this.run({type:'claimSeasonPass',level:Number(b.dataset.passLevel)});for(const b of document.querySelectorAll('[data-premium-level]'))b.onclick=()=>this.run({type:'claimSeasonPremium',level:Number(b.dataset.premiumLevel)});this.node('#season-shop')?.addEventListener('click',()=>this.show('shop'));for(const b of document.querySelectorAll('[data-crucible]'))b.onclick=()=>this.run({type:'crucibleActivate',mode:b.dataset.crucible});
  }
  quests(){const p=this.c.own(),a=p.account;
    this.shell('Aufträge des Riftwacht',`<p class="modal-note">Kontoweiter Fortschritt bleibt nach dem Tod erhalten. Belohnungen können einmalig im Riftwacht abgeholt werden.</p><div class="contract-list">${CONTRACTS.map(q=>{const n=Math.min(q.goal,a.totals[q.key]||0),claimed=a.claims.includes(q.id);return `<article class="contract-card ${claimed?'complete':''}"><div><h3>${q.name}</h3><p>${q.description}</p><div class="contract-meter"><i style="width:${n/q.goal*100}%"></i></div><small>${n} / ${q.goal} · ◆ ${q.coins} · ✦ ${q.fame}</small></div><button data-contract="${q.id}" ${claimed||n<q.goal||p.dead||this.c.state().world.kind!=='nexus'?'disabled':''}>${claimed?'Erhalten':'Abholen'}</button></article>`;}).join('')}</div>`);
    for(const b of document.querySelectorAll('[data-contract]'))b.onclick=()=>this.run({type:'claimContract',contractId:b.dataset.contract});
  }
  pets(){const p=this.c.own(),a=p.account,atHome=!p.dead&&this.c.state().world.kind==='nexus',unlocked=a.unlocks?.pets;
    const pets=Object.entries(PETS).map(([id,pet])=>{const owned=a.petOwned.includes(id),tier=a.petTier?.[id]||0,rar=PET_RARITIES[tier],cap=rar?.cap||20,level=1+Math.min(cap-1,Math.floor(Math.sqrt((a.petXP[id]||0)/30))),dupes=a.petDuplicates?.[id]||0;return `<article class="pet-card"><canvas width="72" height="72" data-pet-portrait="${id}"></canvas><h3>${pet.name}</h3><p>${pet.description}</p><small>${owned?`${rar.name} · STUFE ${level}/${cap} · ${a.petXP[id]||0} EP · DUPLIKATE ${dupes}`:`◆ ${pet.cost} RIFTMARKEN`}</small><button data-pet="${id}" data-owned="${owned}" ${!unlocked||!atHome||a.petActive===id||!owned&&p.bank<pet.cost?'disabled':''}>${a.petActive===id?'Begleitet dich':owned?'Mitnehmen':'Adoptieren'}</button>${owned?`<div class="item-actions"><button data-feed="${id}" data-food="fruit" ${(a.petFood?.fruit||0)<1||!atHome?'disabled':''}>Frucht füttern</button><button data-fuse="${id}" ${dupes<1||tier>=PET_RARITIES.length-1||!atHome?'disabled':''}>Fusion</button></div>`:''}</article>`;}).join('');
    const eggs=Object.entries(PET_EGGS).map(([id,name])=>`<article class="progression-row"><strong>${name}</strong><span>${a.petEggs?.[id]||0}</span>${(a.petEggs?.[id]||0)>0?`<select data-hatch-pet="${id}">${Object.entries(PETS).map(([pid,v])=>`<option value="${pid}">${v.name}</option>`).join('')}</select><button data-hatch="${id}" ${!atHome||!unlocked?'disabled':''}>Ausbrüten</button>`:''}</article>`).join('');
    this.shell('Gefährtenhof',`<p class="modal-note">Ab Kontostufe ${SYSTEM_UNLOCKS.pets}. Eier können Gefährten oder Duplikate liefern. Füttern erhöht Erfahrung; Duplikate erlauben bei genügend EP eine Fusion in höhere Seltenheiten. Gefährten bleiben beim Charaktertod erhalten.</p>${!unlocked?`<div class="empty-state">Noch gesperrt · Kontostufe ${SYSTEM_UNLOCKS.pets} erforderlich.</div>`:`<div class="pet-grid">${pets}</div>${a.petActive?'<button id="pet-stay" class="secondary-button">Gefährten im Riftwacht lassen</button>':''}<div class="subheading">EIER & FUTTER</div><div class="systems-summary"><span>KRÜMEL ${a.petFood?.crumb||0}</span><span>FRÜCHTE ${a.petFood?.fruit||0}</span><span>FESTMAHL ${a.petFood?.feast||0}</span></div><div class="progression-list">${eggs}</div>`}`);
    for(const b of document.querySelectorAll('[data-pet]'))b.onclick=()=>this.run({type:b.dataset.owned==='true'?'petSelect':'petAdopt',petId:b.dataset.pet});for(const b of document.querySelectorAll('[data-feed]'))b.onclick=()=>this.run({type:'petFeed',petId:b.dataset.feed,food:b.dataset.food});for(const b of document.querySelectorAll('[data-fuse]'))b.onclick=()=>this.run({type:'petFuse',petId:b.dataset.fuse});for(const b of document.querySelectorAll('[data-hatch]'))b.onclick=()=>this.run({type:'petHatch',eggId:b.dataset.hatch,petId:document.querySelector(`[data-hatch-pet="${b.dataset.hatch}"]`).value});this.node('#pet-stay')?.addEventListener('click',()=>this.run({type:'petSelect',petId:null}));
  }
  mastery(){
    const p=this.c.own(),mastery=p.account?.mastery||{},total=p.account?.masteryStars||0,max=Object.keys(CLASSES).length*MASTERY_FAME_THRESHOLDS.length;
    const cards=Object.entries(CLASSES).map(([id,c])=>{const best=mastery[id]||0,rank=masteryRank(best),next=MASTERY_FAME_THRESHOLDS[rank];return `<article class="mastery-card ${id===p.classId?'active':''}"><canvas width="44" height="54" data-class-portrait="${id}"></canvas><div><strong>${this.esc(c.name)}</strong><small>Meisterschaft ${rank} / ${MASTERY_FAME_THRESHOLDS.length} · ${'★'.repeat(rank)}${'☆'.repeat(MASTERY_FAME_THRESHOLDS.length-rank)}</small><div class="mastery-meter"><i style="width:${next?Math.min(100,best/next*100):100}%"></i></div><small>Bester gefallener Ruhm: ${best}${next?' · nächster Rang bei '+next:' · MAXIMALRANG'}</small></div></article>`;}).join('');
    this.shell('Klassen-Meisterschaft',`<p class="modal-note">Dauerhafter Kontofortschritt für alle 19 Klassen. Beim Tod wird der höchste mit dieser Klasse erreichte Charakter-Ruhmwert gespeichert. Meisterschaft verleiht keine Kampfvorteile.</p><div class="mastery-total"><strong>${total} / ${max} ★</strong><small>KONTO-MEISTERSCHAFT</small></div><div class="mastery-grid">${cards}</div>`);
  }
  enchanter(){
    const p=this.c.own(),a=p.account,unlocked=a.unlocks?.enchanter,atHome=!p.dead&&this.c.state().world.kind==='nexus';
    const rows=p.inventory.filter(i=>EQUIP_SLOTS.includes(i.slot)).map(i=>`<article class="forge-row"><canvas width="44" height="44" data-slot="${i.slot}" data-tier="${i.tier}" data-rarity="${i.rarity}" data-item-class="${i.classId}"></canvas><div><h3>${this.esc(i.name)}</h3><small>${itemQualityName(i)} · ${i.enchantment?ENCHANTMENTS[i.enchantment]?.name+' · RANG '+['—','I','II','III'][enchantRank(i)]:'kein Effekt'} · Grüner Staub ${a.dust?.green||0}</small></div><select data-enchant-select="${i.id}">${Object.entries(ENCHANTMENTS).map(([id,e])=>`<option value="${id}" ${id===i.enchantment?'selected':''}>${e.name} · ${e.description}</option>`).join('')}</select><button data-enchant="${i.id}" ${!unlocked||!atHome?'disabled':''}>Verzaubern</button></article>`).join('');
    this.shell('Verzauberer',`<p class="modal-note">Ab Kontostufe ${SYSTEM_UNLOCKS.enchanter}. Verzauberungen verändern echte Kampfwerte und werden auf dem Gegenstand gespeichert. Derselbe Effekt kann bis Rang III verstärkt werden; höhere Ränge und Tierstufen kosten mehr Staub.</p><div class="systems-summary"><span>GRÜNER STAUB ${a.dust?.green||0}</span><span>VIOLETT ${a.dust?.violet||0}</span><span>GOLD ${a.dust?.gold||0}</span></div>${unlocked?`<div class="forge-list">${rows||'<div class="empty-state">Lege verzauberbare Ausrüstung in dein Gepäck.</div>'}</div>`:`<div class="empty-state">Noch gesperrt · Kontostufe ${SYSTEM_UNLOCKS.enchanter} erforderlich.</div>`}`);
    for(const b of document.querySelectorAll('[data-enchant]'))b.onclick=()=>this.run({type:'enchant',itemId:b.dataset.enchant,enchantment:document.querySelector(`[data-enchant-select="${b.dataset.enchant}"]`).value});
  }
  storage(){
    const p=this.c.own(),a=p.account,atHome=!p.dead&&this.c.state().world.kind==='nexus';
    const potionNames={atk:'Angriff',def:'Verteidigung',spd:'Tempo',dex:'Geschick',vit:'Vitalität',wis:'Weisheit',life:'Leben',mana:'Mana'};
    const potions=Object.entries(a.potionVault||{}).map(([k,n])=>`<article class="progression-row"><strong>${potionNames[k]||k}</strong><span>${n} / 99</span><button data-potion-take="${k}" ${!atHome||n<1||p.inventory.length>=8?'disabled':''}>Entnehmen</button></article>`).join('');
    const invPotions=p.inventory.filter(i=>i.slot==='potion').map(i=>`<button data-potion-store="${i.id}" ${!atHome?'disabled':''}>${this.esc(i.name)} einlagern</button>`).join('');
    const gift=a.giftChest?.map(i=>`<article class="forge-row"><canvas width="40" height="40" data-slot="${i.slot}" data-tier="${i.tier}" data-rarity="${i.rarity}" data-item-class="${i.classId}"></canvas><div><strong>${this.esc(i.name)}</strong><small>${itemQualityName(i)}</small></div><button data-gift="${i.id}" ${!atHome||p.inventory.length>=8?'disabled':''}>Abholen</button></article>`).join('')||'<p class="modal-note">Keine Geschenke vorhanden.</p>';
    const stash=a.seasonalStash?.map(i=>`<article class="forge-row"><canvas width="40" height="40" data-slot="${i.slot}" data-tier="${i.tier}" data-rarity="${i.rarity}" data-item-class="${i.classId}"></canvas><div><strong>${this.esc(i.name)}</strong></div><button data-season-withdraw="${i.id}" ${!atHome||!p.seasonal||p.inventory.length>=8?'disabled':''}>Entnehmen</button></article>`).join('')||'<p class="modal-note">Saisonlager leer.</p>';
    const seasonalDeposit=p.seasonal?p.inventory.filter(i=>i.slot!=='potion').map(i=>`<button data-season-deposit="${i.id}" ${!atHome||a.seasonalStash.length>=24?'disabled':''}>${this.esc(i.name)} → Saisonlager</button>`).join(''):'';
    this.shell('Lager & Geschenke',`<div class="subheading">TRANKLAGER</div><div class="progression-list">${potions}</div><div class="item-actions">${invPotions}</div><div class="subheading">GESCHENKTRUHE · ${a.giftChest?.length||0} / 24</div><div class="forge-list">${gift}</div><div class="subheading">SAISONLAGER · ${a.seasonalStash?.length||0} / 24</div><div class="forge-list">${stash}</div><div class="item-actions">${seasonalDeposit}</div>`);
    for(const b of document.querySelectorAll('[data-potion-take]'))b.onclick=()=>this.run({type:'potionTake',statKey:b.dataset.potionTake});for(const b of document.querySelectorAll('[data-potion-store]'))b.onclick=()=>this.run({type:'potionStore',itemId:b.dataset.potionStore});for(const b of document.querySelectorAll('[data-gift]'))b.onclick=()=>this.run({type:'giftClaim',itemId:b.dataset.gift});for(const b of document.querySelectorAll('[data-season-withdraw]'))b.onclick=()=>this.run({type:'seasonWithdraw',itemId:b.dataset.seasonWithdraw});for(const b of document.querySelectorAll('[data-season-deposit]'))b.onclick=()=>this.run({type:'seasonDeposit',itemId:b.dataset.seasonDeposit});
  }
  ranking(){
    const state=this.c.state(),board=state.leaderboard||[],speed=state.speedLeaderboard||[],event=state.eventLeaderboard||[],mine=this.c.own(),theme=state.speedLeaderboardTheme,eventInfo=state.progression?.liveEvent;
    const fameRows=board.map(entry=>`<article class="leaderboard-row ${entry.name===mine.name?'mine':''}"><b class="leaderboard-rank">#${entry.rank}</b><canvas width="34" height="42" data-class-portrait="${entry.classId}"></canvas><div class="leaderboard-main"><strong>${this.esc(entry.name)}</strong><small>${CLASSES[entry.classId]?.name||'Wanderer'} · Stufe ${entry.level} · beste Stufe ${entry.bestLevel}</small></div><div class="leaderboard-score"><strong>✦ ${entry.fame}</strong><small>${entry.dungeons} Dungeons · ${entry.kills} Siege · ${entry.masteryStars||0} ★</small></div></article>`).join('')||'<p class="modal-note">Noch keine Ruhmdaten.</p>';
    const speedRows=speed.map(entry=>`<article class="leaderboard-row ${entry.name===mine.name?'mine':''}"><b class="leaderboard-rank">#${entry.rank}</b><div class="leaderboard-main"><strong>${this.esc(entry.name)}</strong><small>${DUNGEONS[theme]?.name||theme}</small></div><div class="leaderboard-score"><strong>${Number(entry.time).toFixed(2)} s</strong><small>BESTZEIT</small></div></article>`).join('')||'<p class="modal-note">Noch keine Bestzeit für diesen Dungeon.</p>';
    const eventRows=event.map(entry=>`<article class="leaderboard-row ${entry.name===mine.name?'mine':''}"><b class="leaderboard-rank">#${entry.rank}</b><div class="leaderboard-main"><strong>${this.esc(entry.name)}</strong><small>${entry.completions} Abschlüsse · ${entry.echoCompletions} Echopfade</small></div><div class="leaderboard-score"><strong>${entry.score}</strong><small>EVENTPUNKTE</small></div></article>`).join('')||'<p class="modal-note">Noch keine Eventpunkte.</p>';
    this.shell('Ranglisten',`<div class="subheading">RUHM</div><div class="leaderboard-list">${fameRows}</div><div class="subheading">BESTZEIT · ${this.esc(DUNGEONS[theme]?.name||theme||'Rotation')}</div><div class="leaderboard-list">${speedRows}</div><div class="subheading">${this.esc(eventInfo?.name||'SCHLEIERROTATION')} · ${this.esc(DUNGEONS[eventInfo?.theme]?.name||'')}</div><div class="leaderboard-list">${eventRows}</div>`);
  }
  friends(){
    const state=this.c.state(),friends=state.friends||{contacts:[],incoming:[],outgoing:[],max:50};
    const row=(f,buttons='')=>`<article class="friend-row"><div><strong>${this.esc(f.name)}</strong><small>${f.online?'ONLINE · DIESE REGION':'OFFLINE / ANDERE REGION'}</small></div><div class="item-actions">${buttons}</div></article>`;
    this.shell('Freunde',`<p class="modal-note">Freunde werden kontoweit auf diesem Server gespeichert. Online bedeutet hier: aktuell in derselben Serverregion sichtbar.</p>${friends.incoming.length?`<div class="subheading">ANFRAGEN · ${friends.incoming.length}</div><div class="friend-list">${friends.incoming.map(f=>row(f,`<button data-friend-accept="${f.id}">Annehmen</button><button data-friend-decline="${f.id}">Ablehnen</button>`)).join('')}</div>`:''}<div class="subheading">FREUNDESLISTE · ${friends.contacts.length} / ${friends.max}</div><div class="friend-list">${friends.contacts.map(f=>row(f,`${f.online?`<button data-friend-chat="${f.id}">Nachricht</button>`:''}<button data-friend-remove="${f.id}" class="secondary-button">Entfernen</button>`)).join('')||'<p class="modal-note">Noch keine Freunde. Öffne „Spieler & Gruppe“ und sende einem sichtbaren Spieler eine Anfrage.</p>'}</div>${friends.outgoing.length?`<div class="subheading">AUSSTEHEND</div><div class="friend-list">${friends.outgoing.map(f=>row(f,`<button data-friend-decline="${f.id}" class="secondary-button">Zurückziehen</button>`)).join('')}</div>`:''}<button id="friend-open-players" class="primary-button">Spieler in meiner Welt anzeigen</button>`);
    for(const b of document.querySelectorAll('[data-friend-accept]'))b.onclick=()=>this.run({type:'friendAccept',playerId:b.dataset.friendAccept});
    for(const b of document.querySelectorAll('[data-friend-decline]'))b.onclick=()=>this.run({type:'friendDecline',playerId:b.dataset.friendDecline});
    for(const b of document.querySelectorAll('[data-friend-remove]'))b.onclick=()=>this.run({type:'friendRemove',playerId:b.dataset.friendRemove});
    for(const b of document.querySelectorAll('[data-friend-chat]'))b.onclick=()=>this.c.chat('friend',b.dataset.friendChat);
    this.node('#friend-open-players').onclick=this.c.party;
  }
  guild(){const state=this.c.state(),p=this.c.own(),g=state.guild;this.lastGuild=JSON.stringify(g);
    if(!g){this.shell('Deine Gilde',`<p>Eine gemeinsame Heimat für bis zu 30 Mitglieder. Gilden und ihre Mitgliedschaften werden auf deinem Server gespeichert.</p><div class="guild-entry-grid"><form id="guild-create-form"><h3>Neue Gilde gründen</h3><label class="field"><span>GILDENNAME</span><input id="guild-name" maxlength="20" minlength="3" required></label><p class="modal-note">Kosten: 100 Riftmarken. Gründung im Riftwacht.</p><button type="submit" class="primary-button" ${p.bank<100||p.dead||state.world.kind!=='nexus'?'disabled':''}>Gilde gründen</button></form><form id="guild-request-form"><h3>Gilde beitreten</h3><label class="field"><span>GILDENCODE</span><input id="guild-code" maxlength="20" required autocapitalize="characters" placeholder="G…"></label><p class="modal-note">Die Gildenleitung bestätigt deinen Antrag.</p><button type="submit" class="secondary-button">Beitritt anfragen</button><p id="guild-request-status" class="modal-note"></p></form></div>`);
      this.node('#guild-create-form').onsubmit=async e=>{e.preventDefault();await this.run({type:'guildCreate',name:this.node('#guild-name').value});};this.node('#guild-request-form').onsubmit=async e=>{e.preventDefault();if(await this.run({type:'guildRequest',code:this.node('#guild-code').value},false))this.node('#guild-request-status').textContent='Anfrage wurde an die Gildenleitung gesendet.';};return;}
    const leader=g.leader===p.id;
    this.shell(g.name,`<div class="guild-banner"><span class="guild-emblem">⚑</span><div><h3>${this.esc(g.name)}</h3><p>${g.members.length} / 30 Mitglieder · Gildenstufe ${g.level}</p><strong>${g.code}</strong></div></div><p class="modal-note">Gildenmarken: ${g.bank}. Spenden erhöhen den gemeinsamen Gildenrang. Ein höherer Rang gibt derzeit keinen Kampfbonus.</p><div class="subheading">GILDEN-PINNWAND</div><p class="modal-note">${this.esc(g.board||'Noch keine Nachricht der Gildenleitung.')}</p>${leader?`<label class="field"><span>PINNWAND BEARBEITEN · MAX. 240 ZEICHEN</span><textarea id="guild-board-text" maxlength="240">${this.esc(g.board||'')}</textarea></label><button id="guild-board-save" class="secondary-button">Pinnwand speichern</button>`:''}${leader&&g.requests.length?`<div class="subheading">BEITRITTSANFRAGEN</div>${g.requests.map(r=>`<div class="guild-member"><b>${this.esc(r.name)}</b><button data-approve="${r.id}">Aufnehmen</button><button data-decline="${r.id}">Ablehnen</button></div>`).join('')}`:''}<div class="subheading">MITGLIEDER</div><div>${g.members.map(m=>`<div class="guild-member"><span class="online-led ${m.online?'online':''}"></span><div><b>${this.esc(m.name)}</b><small>${m.leader?'GILDENLEITUNG':m.online?'ONLINE':'OFFLINE'}</small></div>${leader&&m.id!==p.id?`<button data-promote="${m.id}" aria-label="${this.esc(m.name)} zur Leitung ernennen">Leitung</button><button data-kick="${m.id}">Entfernen</button>`:''}</div>`).join('')}</div><div class="item-actions"><button id="guild-donate" ${p.bank<50||p.dead||state.world.kind!=='nexus'?'disabled':''}>50 Riftmarken spenden</button><button id="guild-chat">Gildenchat öffnen</button><button id="guild-leave">Gilde verlassen</button></div>`);
    for(const [selector,type,attribute]of [['approve','guildApprove','approve'],['decline','guildDecline','decline'],['promote','guildPromote','promote'],['kick','guildKick','kick']])for(const b of document.querySelectorAll('[data-'+selector+']'))b.onclick=()=>this.run({type,playerId:b.dataset[attribute]});
    this.node('#guild-board-save')?.addEventListener('click',()=>this.run({type:'guildSetBoard',text:this.node('#guild-board-text').value}));this.node('#guild-donate').onclick=()=>this.run({type:'guildDonate',amount:50});this.node('#guild-leave').onclick=()=>{this.c.modal('confirm-guild','Gilde verlassen?',`<p>Die Mitgliedschaft endet. Gespendete Riftmarken bleiben in der Gilde. Beim Austritt der Leitung geht die Rolle an das nächste Mitglied.</p><button id="confirm-guild-leave" class="primary-button">Gilde verlassen</button><button id="cancel-guild-leave" class="secondary-button">Abbrechen</button>`);this.node('#confirm-guild-leave').onclick=async()=>{await this.run({type:'guildLeave'},false);this.show('guild');};this.node('#cancel-guild-leave').onclick=()=>this.show('guild');};this.node('#guild-chat').onclick=()=>this.c.chat('guild');
  }
  forge(){const p=this.c.own(),a=p.account,unlocked=a.unlocks?.forge===true,home=!p.dead&&this.c.state().world.kind==='nexus',items=p.inventory.filter(i=>EQUIP_SLOTS.includes(i.slot));
    const materials=`<div class="systems-summary"><span>◆ ${p.bank} RIFTMARKEN</span><span>⚒ ${a.forgeMaterials?.metal||0} METALL</span><span>✧ ${a.forgeMaterials?.essence||0} ESSENZ</span><span>BAUPLÄNE ${(a.blueprints||[]).length}/${Object.keys(FORGE_RECIPES).length}</span></div>`;
    const recipes=Object.entries(FORGE_RECIPES).map(([id,r])=>{const known=(a.blueprints||[]).includes(id),cost=Object.entries(r.materials).map(([k,n])=>`${n} ${k==='metal'?'Metall':'Essenz'}`).join(' · ');return `<article class="forge-recipe ${known?'known':''}"><div><h3>${r.name}</h3><p>${r.description}</p><small>${known?cost:'BAUPLAN NOCH NICHT GEFUNDEN'}</small></div><select data-recipe-item="${id}" ${!known||!unlocked||!home?'disabled':''}>${items.map(i=>`<option value="${i.id}">${this.esc(i.name)} · T${i.tier}</option>`).join('')}</select><button data-forge-recipe="${id}" ${!known||!unlocked||!home||!items.length?'disabled':''}>Herstellen</button></article>`;}).join('');
    this.shell('Die Schlackenschmiede',`${materials}${!unlocked?`<p class="modal-note">Die volle Schmiede wird auf Kontostufe ${SYSTEM_UNLOCKS.forge} freigeschaltet. Bis dahin kannst du Beute sammeln und zerlegen.</p>`:'<p class="modal-note">Zerlegte Gegenstände liefern Metall und Staub. Dungeonbosse können Essenz und Baupläne hinterlassen. Rezepte erhalten besondere Eigenschaften wie Verzauberungen und Schimmer.</p>'}<div class="subheading">KLASSISCHE TIER-VERBESSERUNG</div><div class="forge-list">${items.map(i=>`<article class="forge-row"><canvas width="44" height="44" data-slot="${i.slot}" data-tier="${i.tier}" data-rarity="${i.rarity}" data-item-class="${i.classId}"></canvas><div><h3>${this.esc(i.name)}</h3><small>${itemQualityName(i)} · ${RARITIES[i.rarity].name} · T${i.tier}${i.enchantment?' · '+ENCHANTMENTS[i.enchantment]?.name:''}${i.shiny?' · SCHIMMERND':''}</small></div><button data-forge="${i.id}" ${!unlocked||i.tier>=7||!home||p.bank<35*(i.tier+1)*(i.rarity+1)?'disabled':''}>${i.tier>=7?'Maximum':'◆ '+35*(i.tier+1)*(i.rarity+1)}</button></article>`).join('')||'<div class="empty-state">Keine schmiedbaren Gegenstände im Gepäck.</div>'}</div><div class="subheading">BAUPLAN-REZEPTE</div><div class="forge-recipes">${recipes}</div>`);
    for(const b of document.querySelectorAll('[data-forge]'))b.onclick=()=>this.run({type:'forge',itemId:b.dataset.forge});
    for(const b of document.querySelectorAll('[data-forge-recipe]'))b.onclick=()=>{const id=b.dataset.forgeRecipe,itemId=this.node(`[data-recipe-item="${id}"]`)?.value;if(itemId)this.run({type:'forgeRecipe',recipe:id,itemId});};
  }
  dungeons(){const p=this.c.own(),state=this.c.state(),event=state.progression?.liveEvent,home=state.world.kind==='nexus'&&!p.dead;this.shell('Wege in die Tiefe',`<p class="modal-note">Natürliche Portale entstehen durch besiegte Gegner. Schlüsselportale bleiben 90 Sekunden offen. Portale können Modifikatoren tragen. Die wöchentliche Schleierrotation erhöht Belohnungen; der Echopfad ist eine härtere Eventvariante mit drei garantierten Gefahrenmodifikatoren.</p>${event?`<div class="mastery-total"><strong>${this.esc(event.name)} · ${this.esc(DUNGEONS[event.theme]?.name||event.theme)}</strong><small>EVENTBONUS AKTIV · ENDET ${new Date(event.endsAt).toLocaleDateString(localeTag())}</small></div>`:''}<div class="dungeon-codex">${Object.entries(DUNGEONS).map(([id,d])=>{const active=event?.theme===id,cost=DUNGEON_KEYS[id],echoCost=Math.ceil(cost*1.5),locked=id==='void'&&!(p.account.totals['boss:sovereign']>0);return `<article class="dungeon-card ${active?'complete':''}" style="--dungeon-accent:${d.color}"><canvas width="60" height="68" data-class-portrait="${d.boss}"></canvas><div><h3>${d.name}${active?' · ROTATION':''}</h3><p>${d.subtitle}</p><small>${ENEMY_TYPES[d.boss].name}${p.account.bestTimes?.[id]?' · BESTZEIT '+Number(p.account.bestTimes[id]).toFixed(2)+' s':''}</small></div><div class="roster-actions"><button data-dungeon="${id}" ${!home||p.bank<cost||locked?'disabled':''}>Portal · ◆ ${cost}</button>${active?`<button data-echo-dungeon="${id}" ${!home||p.bank<echoCost||locked?'disabled':''}>Echopfad · ◆ ${echoCost}</button>`:''}</div></article>`;}).join('')}</div><p class="modal-note">18 originale Dungeons bilden den aktuellen Pool. Echopfade erscheinen nur für den aktiven Rotations-Dungeon.</p>`);for(const b of document.querySelectorAll('[data-dungeon]'))b.onclick=async()=>{if(await this.run({type:'openDungeon',theme:b.dataset.dungeon},false))this.c.close();};for(const b of document.querySelectorAll('[data-echo-dungeon]'))b.onclick=async()=>{if(await this.run({type:'openDungeon',theme:b.dataset.echoDungeon,echo:true},false))this.c.close();};}
  bestiary(){const p=this.c.own(),a=p.account;this.shell('Spuren & Erinnerungen',`<div class="systems-summary"><span>${a.totals.kills} SIEGE</span><span>${a.totals.dungeons} DUNGEONS</span><span>BESTE STUFE ${a.totals.bestLevel}</span></div><div class="bestiary-grid">${Object.entries(ENEMY_TYPES).filter(([id])=>id!=='boss').map(([id,e])=>`<article class="bestiary-card ${(a.totals['enemy:'+id]||0)>0?'discovered':''}"><canvas width="42" height="50" data-class-portrait="${id}"></canvas><b>${e.name}</b><small>${a.totals['enemy:'+id]||0} BESIEGT</small></article>`).join('')}</div><div class="subheading">GEFALLENE FIGUREN</div>${a.history.length?a.history.slice().reverse().map(h=>`<div class="grave-entry"><b>${this.esc(h.name)} · ${CLASSES[h.classId].name}</b><span>Stufe ${h.level} · ✦ ${h.fame}</span><small>${this.esc(h.killer)}</small></div>`).join(''):'<p class="modal-note">Noch kein Leben verloren.</p>'}`);}
  async shop(){
    if(this.c.mode()!=='online'||!this.c.shop){this.shell('Der Schwarze Tresen','<div class="shop-seal"><b>◇</b><strong>DER SCHWARZE TRESEN</strong><small>Nur auf einem verbundenen Nyrathen-Server verfügbar.</small></div>');return;}
    this.shell('Der Schwarze Tresen','<div class="shop-loading">Das Eisenbuch wird geöffnet …</div>');
    try{
      const state=await this.c.shop.state();if(this.c.modalKind()!=='systems'||this.section!=='shop')return;
      const p=this.c.own(),products=state.store||[],offers=state.offers||[],commerce=state.commerce||{},wishlistReturns=state.wishlistReturns||[],owned=new Set(commerce.owned||[]),wish=new Set(commerce.wishlist||[]),tabs=state.tabs||SHOP_TABS,variant=state.variant==='preview-first'?'preview-first':'ledger';
      if(!tabs.includes(this.shopTab))this.shopTab='featured';
      const priceMap=await this.c.shop.prices(products.map(p=>p.id));
      const price=p=>priceMap.get(p.id)?.price||priceMap.get(p.id)?.formattedPrice||p.priceHint||'Store';
      const verification=state.verification||{},nativeKind=this.c.shop.nativeKind(),storeReady=nativeKind==='ios'?verification.apple===true:nativeKind==='android'?verification.google===true:false;
      const verifierNote=storeReady?`${nativeKind==='ios'?'APPLE':'GOOGLE'} · SERVERPRÜFUNG AKTIV`:nativeKind==='dev'?'NUR IM SIGNIERTEN MOBILE-BUILD':'STORE-VERIFIZIERUNG NOCH NICHT PRODUKTIV';
      const all=[...products.map(x=>({...x,_source:'store'})),...offers.map(x=>({...x,_source:'shards'}))];
      const visible=x=>{if(this.shopTab==='wishlist')return wish.has(x.id);if(this.shopTab==='featured')return x.featured===true||x.group==='splitter'||(x._source==='shards'&&offers.slice(0,3).some(o=>o.id===x.id));return x.tab===this.shopTab;};
      let shown=all.filter(visible);if(variant==='preview-first'){const rank=x=>['character','weapon','pet','collection','bundle','cosmetic'].includes(x.preview||x.kind)?0:x.kind==='season'?1:2;shown=[...shown].sort((a,b)=>rank(a)-rank(b));}const preview=all.find(x=>x.id===this.shopPreview&&visible(x))||shown[0]||all[0]||null;this.shopPreview=preview?.id||null;
      const desc=x=>x.lore||(x.kind==='currency'?'Premiumwährung für Cosmetics, Seasons und Account-Komfort.':x.kind==='season'?'Zusätzlicher kosmetischer Season-Track. Keine Kampfwerte.':x.kind==='account'?'Permanente Account-Erweiterung ohne Kampfstärke.':x.kind==='bundle'?'Kuratiertes Account- und Cosmetic-Paket ohne Power.':'Kosmetischer Ausdruck ohne spielerischen Vorteil.');
      const tabLabel={featured:'Empfohlen',cosmetics:'Cosmetics',season:'Saison',account:'Konto',bundles:'Pakete',wishlist:'Wunschliste'};
      const productCard=x=>{const already=owned.has(x.id)&&!x.repeatable,disabled=x._source==='store'?(!storeReady||already):(owned.has(x.id)||commerce.shardDebt>0||commerce.shards<x.cost),label=already?'Im Besitz':x._source==='store'?(storeReady?'Kaufen':'Nicht verfügbar'):`◇ ${x.cost}`;return `<article class="counter-entry counter-${x._source} ${preview?.id===x.id?'selected':''} ${disabled?'locked':''}" data-shop-preview="${x.id}"><div class="counter-notch">${x.kind==='currency'?'◇':x.kind==='season'?'⌁':x.kind==='account'||x.kind==='slot'||x.kind==='vault'?'▣':'✦'}</div><div class="counter-entry-copy"><small>${this.esc((x.group||x.kind).toUpperCase())}</small><h3>${this.esc(x.title)}</h3><p>${this.esc(desc(x))}</p></div><div class="counter-entry-actions"><button class="counter-preview" data-preview-shop="${x.id}">Vorschau</button>${x._source==='store'?`<strong>${this.esc(price(x))}</strong><button class="counter-buy" data-store-buy="${x.id}" ${disabled?'disabled':''}>${label}</button>`:`<button class="counter-buy" data-shard-buy="${x.id}" ${disabled?'disabled':''}>${label}</button>`}<button class="store-wish ${wish.has(x.id)?'active':''}" data-store-wish="${x.id}" aria-label="Wunschliste">${wish.has(x.id)?'♥':'♡'}</button></div></article>`;};
      const previewKind=preview?.preview||preview?.kind||'cosmetic',previewValue=preview?.value||({
        'nyr.bundle.wanderer':'wayfarer','nyr.bundle.founder':'gravegold','nyr.collection.blackiron':'blackiron'
      }[preview?.id]||'default');
      const previewPrice=preview?preview._source==='store'?price(preview):`◇ ${preview.cost}`:'';
      const previewMarkup=preview?`<section class="counter-preview-stage"><div class="counter-preview-art"><canvas id="shop-preview-canvas" width="150" height="168" data-preview-kind="${this.esc(previewKind)}" data-preview-value="${this.esc(previewValue)}"></canvas><span>${this.esc((preview.group||preview.kind).toUpperCase())}</span></div><div class="counter-preview-copy"><small>AKTUELLE AUSWAHL</small><h2>${this.esc(preview.title)}</h2><p>${this.esc(desc(preview))}</p><div class="preview-contract"><span>KEINE KAMPFKRAFT</span><span>${preview._source==='store'?'STORE-VERIFIZIERT':'NYR-SPLITTER'}</span><strong>${this.esc(previewPrice)}</strong></div></div></section>`:'<div class="empty-state">In diesem Bereich ist aktuell nichts eingetragen.</div>';
      const returnNotice=wishlistReturns.length?`<div class="wishlist-return"><b>♥ WIEDER AM TRESEN</b><span>${this.esc(wishlistReturns.map(id=>all.find(x=>x.id===id)?.title||id).join(' · '))}</span><button data-shop-tab="wishlist">Wunschliste öffnen</button></div>`:'';
      const markup=`<div class="black-counter-layout variant-${variant}"><div class="black-counter-head"><div><span class="counter-kicker">RIFTWACHT · HINTERE GALERIE</span><h3>Der Schwarze Tresen</h3><p>Ausdruck, Sammlung und Komfort. Keine Stärke, kein Glücksrad, keine Wiederbelebung gegen Geld.</p></div><div class="premium-wallet ${commerce.shardDebt>0?'in-debt':''}"><small>DEIN GUTHABEN</small><strong>◇ ${commerce.shards||0}</strong><span>${PREMIUM_CURRENCY}</span>${commerce.shardDebt>0?`<em>RÜCKERSTATTUNGSSCHULD ◇ ${commerce.shardDebt}</em>`:''}</div></div>${returnNotice}<nav class="counter-tabs" aria-label="Shopbereiche">${tabs.map(id=>`<button data-shop-tab="${id}" class="${this.shopTab===id?'selected':''}">${tabLabel[id]||id}</button>`).join('')}</nav>${previewMarkup}<div class="shop-rule"><span>${this.esc((tabLabel[this.shopTab]||this.shopTab).toUpperCase())}</span><i></i><small>${this.esc(verifierNote)} · ${variant==='preview-first'?'VORSCHAU-FOKUS':'LEDGER'}</small></div><div class="counter-ledger">${shown.length?shown.map(productCard).join(''):'<div class="empty-state">Keine Einträge in diesem Bereich.</div>'}</div><div class="shop-foot"><button id="restore-purchases" class="secondary-button" ${!storeReady?'disabled':''}>Käufe wiederherstellen</button><p>Storekäufe werden erst nach serverseitiger Verifikation gutgeschrieben. Refunds und Chargebacks werden im Entitlement-Ledger gegengebucht.</p></div><p id="shop-status" class="form-error"></p></div>`;
      this.shell('Der Schwarze Tresen',markup);await this.c.shop.event('shop_open');
      const canvas=this.node('#shop-preview-canvas');if(canvas&&preview){const g=canvas.getContext('2d');g.imageSmoothingEnabled=false;g.clearRect(0,0,canvas.width,canvas.height);const art=this.c.renderer.art,kind=previewKind,value=previewValue;try{if(kind==='character'||kind==='collection'||kind==='bundle'||kind==='cosmetic'){const img=art.sprite(p.classId,0,value);g.drawImage(img,18,12,114,138);}else if(kind==='weapon'){const img=art.shot('wand',false,value);for(let i=0;i<4;i++)g.drawImage(img,26+i*25,58+(i%2)*8,32,32);}else if(kind==='pet'){const petId=p.account?.petActive||Object.keys(PETS)[0],img=art.pet(petId,0,value);g.drawImage(img,34,28,82,104);}else{g.fillStyle='#b28c51';g.font='56px Georgia';g.textAlign='center';g.fillText(kind==='shards'?'◇':'✦',75,105);}}catch{g.fillStyle='#b28c51';g.font='48px Georgia';g.textAlign='center';g.fillText('◇',75,104);}}
      for(const b of document.querySelectorAll('[data-shop-tab]'))b.onclick=async()=>{this.shopTab=b.dataset.shopTab;this.shopPreview=null;await this.c.shop.event('shop_tab',this.shopTab);this.shop();};
      for(const b of document.querySelectorAll('[data-preview-shop]'))b.onclick=async e=>{e.stopPropagation();this.shopPreview=b.dataset.previewShop;await this.c.shop.event('preview_start',this.shopPreview);this.shop();};
      for(const row of document.querySelectorAll('[data-shop-preview]'))row.onclick=e=>{if(e.target.closest('button'))return;this.shopPreview=row.dataset.shopPreview;this.c.shop.event('product_view',this.shopPreview);this.shop();};
      for(const b of document.querySelectorAll('[data-store-buy]'))b.onclick=async()=>{const id=b.dataset.storeBuy,status=this.node('#shop-status');b.disabled=true;status.textContent='Store wird geöffnet …';try{await this.c.shop.event('product_view',id);await this.c.shop.purchase(id);this.c.toast('Der Schwarze Tresen hat den Kauf bestätigt.');this.shop();}catch(e){status.textContent=e.message;b.disabled=false;}};
      for(const b of document.querySelectorAll('[data-store-wish]'))b.onclick=async e=>{e.stopPropagation();const id=b.dataset.storeWish,enabled=!wish.has(id);await this.c.shop.wishlist(id,enabled);await this.c.shop.event(enabled?'wishlist_add':'wishlist_remove',id);this.shop();};
      for(const b of document.querySelectorAll('[data-shard-buy]'))b.onclick=async()=>{const status=this.node('#shop-status');b.disabled=true;try{await this.c.shop.spend(b.dataset.shardBuy);this.c.toast('Angebot eingelöst.');this.shop();}catch(e){status.textContent=e.message;b.disabled=false;}};
      this.node('#restore-purchases').onclick=async()=>{const status=this.node('#shop-status');status.textContent='Käufe werden geprüft …';try{const rows=await this.c.shop.restore();status.textContent=`${rows.length} Käufe geprüft.`;this.shop();}catch(e){status.textContent=e.message;}};
    }catch(error){if(this.c.modalKind()==='systems'&&this.section==='shop')this.shell('Der Schwarze Tresen',`<p class="form-error">${this.esc(error.message)}</p>`);}
  }
  async account(){
    if(this.c.mode()!=='online'){this.shell('Dein Spielstand',`<h3>Lokaler Solo-Spielstand</h3><p>Charaktere und Welt werden gemeinsam in deinem Browserspeicher gesichert. Dieser Spielstand ist von Onlinekonten getrennt und lässt sich nicht in einen Multiplayer-Server importieren.</p><p>Für geräteübergreifendes Spielen verbinde dich im Hauptmenü mit einem eigenen Server. Dort kannst du deinen Gastzugang unter „Konto“ mit Kontoname und Passwort sichern.</p><button id="backup-offline" class="primary-button">Solo-Sicherung exportieren</button><label class="field"><span>SOLO-SICHERUNG WIEDERHERSTELLEN</span><input id="restore-offline" type="file" accept="application/json,.json"></label><p id="restore-status" class="form-error"></p><p class="modal-note">Ein Import ersetzt nur den lokalen Solo-Spielstand nach deiner Bestätigung.</p>`);this.node('#backup-offline').onclick=this.c.backup;this.node('#restore-offline').onchange=e=>this.c.restore(e.target.files?.[0]);return;}
    this.shell('Dein Onlinekonto','<p>Kontostatus wird geladen …</p>');
    try{const info=await this.c.api('/api/account','GET');if(this.c.modalKind()!=='systems'||this.section!=='account')return;this.accountInfo=info;
      if(info.registered){const unsafe=this.c.state().world.kind!=='nexus'&&!this.c.own().dead;this.shell('Dein Onlinekonto',`<h3>${this.esc(info.username)}</h3><p>Dieses Konto kann mit Kontoname und Passwort auf einem anderen Gerät auf demselben Server geöffnet werden. Ein neuer Login beendet die bisherige Sitzung.</p><p class="modal-note">Bewahre deinen Wiederherstellungscode getrennt vom Passwort auf. Der Server kann den Klartext-Code nicht erneut anzeigen.</p><button id="logout-account" class="secondary-button" ${unsafe?'disabled':''}>Sicher abmelden</button><button id="delete-online-account" class="danger-button" ${unsafe?'disabled':''}>Onlinekonto dauerhaft löschen</button><p class="modal-note">Die Löschung entfernt Figuren, Inventar, Tresor, soziale Verknüpfungen und den Login auf diesem Server. Sie kann nicht rückgängig gemacht werden.</p>`);this.node('#logout-account').onclick=async()=>{try{await this.c.api('/api/account/logout','POST',{});this.c.logout();}catch(e){this.c.toast(e.message);}};this.node('#delete-online-account').onclick=()=>{this.c.modal('delete-online-account','Onlinekonto dauerhaft löschen',`<p><strong>Diese Aktion ist endgültig.</strong> Alle Daten dieses Nyrathen-Kontos auf diesem Server werden gelöscht.</p><label class="field"><span>ZUR BESTÄTIGUNG DELETE EINGEBEN</span><input id="delete-account-confirm" autocomplete="off" autocapitalize="characters" spellcheck="false"></label><button id="confirm-delete-online" class="danger-button" disabled>Konto und Daten löschen</button><button id="cancel-delete-online" class="secondary-button">Abbrechen</button><p id="delete-account-error" class="form-error"></p>`);const input=this.node('#delete-account-confirm'),button=this.node('#confirm-delete-online');input.oninput=()=>{button.disabled=input.value.trim()!=='DELETE';};this.node('#cancel-delete-online').onclick=()=>this.show('account');button.onclick=async()=>{button.disabled=true;try{await this.c.api('/api/profile','DELETE',{confirm:'DELETE'});this.c.logout();}catch(error){this.node('#delete-account-error').textContent=error.message;button.disabled=false;}};};}
      else{this.shell('Gastkonto sichern',`<p>Verknüpfe deinen aktuellen Gast mit einem Kontonamen und Passwort. Alle Figuren, Gegenstände und Mitgliedschaften bleiben erhalten.</p><form id="register-account"><label class="field"><span>KONTONAME · 3–32 ZEICHEN</span><input id="register-name" minlength="3" maxlength="32" autocomplete="username" autocapitalize="off" spellcheck="false" required></label><label class="field"><span>PASSWORT · MINDESTENS 12 ZEICHEN</span><input id="register-password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><button type="submit" class="primary-button">Gastkonto dauerhaft sichern</button><p id="register-error" class="form-error"></p></form><p class="modal-note">Keine E-Mail erforderlich. Du erhältst einen einmal angezeigten Wiederherstellungscode. Ohne Passwort und Code ist keine automatische Wiederherstellung möglich.</p><button id="delete-guest-data" class="danger-button">Gastdaten dieses Servers löschen</button>`);this.node('#register-account').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await this.c.api('/api/account/register','POST',{username:this.node('#register-name').value,password:this.node('#register-password').value});this.showRecovery(r,()=>this.show('account'));}catch(error){this.node('#register-error').textContent=error.message;b.disabled=false;}};this.node('#delete-guest-data').onclick=()=>{this.c.modal('delete-guest-data','Gastdaten dauerhaft löschen',`<p>Alle Figuren, Gegenstände, sozialen Verknüpfungen und der Gastzugang dieses Servers werden gelöscht.</p><label class="field"><span>ZUR BESTÄTIGUNG DELETE EINGEBEN</span><input id="delete-guest-confirm" autocomplete="off" autocapitalize="characters" spellcheck="false"></label><button id="confirm-delete-guest" class="danger-button" disabled>Gastdaten löschen</button><button id="cancel-delete-guest" class="secondary-button">Abbrechen</button><p id="delete-guest-error" class="form-error"></p>`);const input=this.node('#delete-guest-confirm'),button=this.node('#confirm-delete-guest');input.oninput=()=>{button.disabled=input.value.trim()!=='DELETE';};this.node('#cancel-delete-guest').onclick=()=>this.show('account');button.onclick=async()=>{button.disabled=true;try{await this.c.api('/api/profile','DELETE',{confirm:'DELETE'});this.c.logout();}catch(error){this.node('#delete-guest-error').textContent=error.message;button.disabled=false;}};};}
    }catch(error){if(this.c.modalKind()==='systems'&&this.section==='account')this.shell('Kontostatus',`<p class="form-error">${this.esc(error.message)}</p>`);}
  }
  showRecovery(result,next){this.c.modal('recovery','Wiederherstellungscode sichern',`<p>Für das Konto <strong>${this.esc(result.username)}</strong>. Dieser Code wird nur jetzt angezeigt. Er ersetzt bei einer Wiederherstellung das Passwort und ist danach verbraucht.</p><code class="recovery-code">${this.esc(result.recoveryCode)}</code><button id="save-recovery" class="primary-button">Code als Textdatei speichern</button><button id="continue-recovery" class="secondary-button">Ich habe den Code sicher verwahrt</button>`);this.node('#save-recovery').onclick=()=>this.c.textFile('Nyrathen-Wiederherstellung.txt','NYRATHEN\nServer: '+this.c.base()+'\nKonto: '+result.username+'\nWiederherstellungscode: '+result.recoveryCode+'\nPrivat aufbewahren. Nicht an Mitspieler weitergeben.\n');this.node('#continue-recovery').onclick=next;}
  login(config,recovery=false){this.c.modal('account-login',recovery?'Konto wiederherstellen':'Mit Konto anmelden',`<p>Server: <strong>${this.esc(config.base)}</strong> · Region ${this.esc(config.room)}</p><form id="login-form"><label class="field"><span>KONTONAME</span><input id="login-name" autocomplete="username" autocapitalize="off" spellcheck="false" required minlength="3" maxlength="32"></label>${recovery?'<label class="field"><span>WIEDERHERSTELLUNGSCODE</span><input id="login-recovery" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="32" required></label>':''}<label class="field"><span>${recovery?'NEUES PASSWORT':'PASSWORT'}</span><input id="login-password" type="password" autocomplete="${recovery?'new-password':'current-password'}" minlength="12" maxlength="128" required></label><button class="primary-button" type="submit">${recovery?'Konto wiederherstellen':'Anmelden & Riftwacht betreten'}</button><p id="login-error" class="form-error"></p></form><button id="login-recovery-toggle" class="secondary-button">${recovery?'Zur normalen Anmeldung':'Mit Wiederherstellungscode fortfahren'}</button>`);
    this.node('#login-recovery-toggle').onclick=()=>this.login(config,!recovery);
    this.node('#login-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const result=await this.c.authenticate(config.base,{username:this.node('#login-name').value,password:this.node('#login-password').value,...(recovery?{recoveryCode:this.node('#login-recovery').value}:{})},recovery);const join=()=>this.c.join({...config,token:result.token});if(recovery)this.showRecovery(result,join);else await join();}catch(error){if(this.node('#login-error'))this.node('#login-error').textContent=error.message;button.disabled=false;}};
  }
  showTrade(){const state=this.c.state(),trade=state.trade,p=this.c.own();if(!trade){this.c.modal('trade','Spielerhandel',`<p>Im Riftwacht kannst du mit nahen Spielern handeln. Öffne „Spieler & Gruppe“ und wähle „Handeln“.</p><button id="trade-players" class="primary-button">Spielerliste öffnen</button>`);this.node('#trade-players').onclick=this.c.party;return;}
    this.lastTrade=JSON.stringify([trade.id,trade.state,trade.revision,trade.confirmed,trade.players]);const other=trade.players.find(q=>q.id!==p.id),mine=trade.players.find(q=>q.id===p.id);
    if(trade.state==='invited'){this.c.modal('trade','Handel mit '+other.name,`<p>${trade.inviter===p.id?'Deine Anfrage wartet auf eine Bestätigung.':this.esc(other.name)+' möchte mit dir handeln.'}</p><p class="modal-note">Gegenstände werden erst nach beiden Bestätigungen getauscht.</p>${trade.inviter!==p.id?'<button id="accept-trade" class="primary-button">Handelsfenster öffnen</button>':''}<button id="cancel-trade" class="secondary-button">Abbrechen</button>`);this.node('#accept-trade')?.addEventListener('click',()=>this.c.action({type:'tradeAccept',tradeId:trade.id}));}
    else{
      const item=i=>`<div class="trade-item"><canvas width="32" height="32" data-slot="${i.slot}" data-tier="${i.tier}" data-rarity="${i.rarity}" data-item-class="${i.classId}"></canvas><span>${this.esc(i.name)}</span></div>`;
      this.c.modal('trade','Handel mit '+other.name,`<p class="modal-note">Jede Änderung setzt beide Bestätigungen zurück. Tauschen ist nur im Riftwacht möglich. Es werden keine Splitter oder Kontodaten übertragen.</p><div class="trade-columns"><section><h3>Dein Angebot</h3>${mine.items.map(item).join('')||'<p class="modal-note">Noch kein Gegenstand gewählt.</p>'}<small>${trade.confirmed.includes(p.id)?'BESTÄTIGT':'NICHT BESTÄTIGT'}</small></section><section><h3>${this.esc(other.name)}</h3>${other.items.map(item).join('')||'<p class="modal-note">Noch kein Gegenstand gewählt.</p>'}<small>${trade.confirmed.includes(other.id)?'BESTÄTIGT':'NICHT BESTÄTIGT'}</small></section></div><div class="subheading">DEIN GEPÄCK · GEGENSTÄNDE ANBIETEN</div><div class="trade-selection">${p.inventory.map(i=>`<label><input type="checkbox" data-trade-item="${i.id}" ${mine.items.some(m=>m.id===i.id)?'checked':''}>${item(i)}</label>`).join('')||'<p class="modal-note">Dein Gepäck ist leer. Du kannst trotzdem Gegenstände empfangen.</p>'}</div><button id="confirm-trade" class="primary-button" ${trade.confirmed.includes(p.id)||!mine.items.length&&!other.items.length?'disabled':''}>${trade.confirmed.includes(p.id)?'Warte auf zweite Bestätigung':'Dieses Angebot verbindlich bestätigen'}</button><button id="cancel-trade" class="secondary-button">Handel abbrechen</button>`);
      for(const box of document.querySelectorAll('[data-trade-item]'))box.onchange=()=>this.c.action({type:'tradeOffer',tradeId:trade.id,itemIds:[...document.querySelectorAll('[data-trade-item]:checked')].map(b=>b.dataset.tradeItem)});
      this.node('#confirm-trade').onclick=()=>this.c.action({type:'tradeConfirm',tradeId:trade.id,revision:trade.revision});this.draw();
    }
    this.node('#cancel-trade').onclick=async()=>{await this.c.action({type:'tradeCancel'});this.c.close();};
  }
  update(){const state=this.c.state();if(!state)return;
    if(state.trade&&state.trade.id!==this.notifiedTrade&&state.trade.inviter!==this.c.own()?.id){this.notifiedTrade=state.trade.id;this.c.toast('Neue Handelsanfrage. Öffne das Handelsfenster (T).');if(!this.c.modalKind())this.showTrade();}
    if(this.c.modalKind()==='trade'){const signature=state.trade?JSON.stringify([state.trade.id,state.trade.state,state.trade.revision,state.trade.confirmed,state.trade.players]):'';if(signature!==this.lastTrade){if(!state.trade){this.lastTrade='';this.c.close();}else this.showTrade();}}
    if(this.c.modalKind()==='systems'&&this.section==='guild'&&JSON.stringify(state.guild)!==this.lastGuild)this.guild();
  }
}
