// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createGameServer } from '../server/server.mjs';
import { ProfileStore } from '../server/store.mjs';
import { makeItem } from '../shared/realm-data.mjs';
const password='Rune-Lake-2026-Cedar';
async function serve(t,options={}){
  const app=createGameServer({dataPath:':memory:',...options});app.server.listen(0,'127.0.0.1');await once(app.server,'listening');
  const base='http://127.0.0.1:'+app.server.address().port;if(t)t.after(()=>app.close());
  const request=async(path,{token='',value,method=value===undefined?'GET':'POST'}={})=>{const r=await fetch(base+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(value!==undefined?{'Content-Type':'application/json'}:{})},body:value===undefined?undefined:JSON.stringify(value)});return{status:r.status,data:await r.json()};};
  const login=async(name='Alpha',token='',room='PUBLIC')=>(await request('/api/session',{token,value:{protocol:2,name,classId:'weaver',room}})).data;
  const action=async(account,value)=>request('/api/action',{token:account.token,value});
  return{app,base,request,login,action};
}
async function stream(base,token){const stop=new AbortController(),r=await fetch(base+'/api/stream',{headers:{Authorization:'Bearer '+token},signal:stop.signal});assert.equal(r.status,200);const reader=r.body.getReader(),decoder=new TextDecoder();let pending='';return{stop(){stop.abort();reader.cancel().catch(()=>{});},async next(){while(true){const i=pending.indexOf('\n\n');if(i>=0){const text=pending.slice(0,i);pending=pending.slice(i+2);const line=text.split('\n').find(l=>l.startsWith('data: '));if(line)return JSON.parse(line.slice(6));}const chunk=await reader.read();if(chunk.done)throw Error('Stream ended');pending+=decoder.decode(chunk.value,{stream:true});}}};}

test('Named account registration secures existing guest and never returns password hashes',async t=>{const{app,request,login}=await serve(t);const p=await login();const created=await request('/api/account/register',{token:p.token,value:{username:'RuneKnight',password}});assert.equal(created.status,200);assert.equal(created.data.username,'runeknight');assert.equal(created.data.recoveryCode.length,32);assert.equal((await request('/api/account',{token:p.token})).data.registered,true);const row=app.store.db.prepare('SELECT * FROM credentials').get();assert.notEqual(row.password_hash,password);assert.notEqual(row.recovery_hash,created.data.recoveryCode);assert.equal(row.password_hash.length,64);assert(!JSON.stringify(created.data).includes(row.password_hash));assert.equal((await request('/api/account')).status,401);});
test('Password login replaces token while retaining active roster, inventory and profile identity',async t=>{const{request,login,action}=await serve(t);const p=await login();await request('/api/account/register',{token:p.token,value:{username:'roster',password}});assert((await action(p,{type:'characterCreate',classId:'ninja',name:'Ninja'})).data.accepted);const result=await request('/api/account/login',{value:{username:'ROSTER',password}});assert.equal(result.status,200);assert.notEqual(result.data.token,p.token);assert.equal((await request('/api/profile',{token:p.token})).status,401);const resumed=await login('Ignored',result.data.token);assert.equal(resumed.playerId,p.playerId);const own=resumed.snapshot.players.find(q=>q.id===p.playerId);assert.equal(own.classId,'ninja');assert.equal(own.account.characters.length,2);});
test('Logging in during combat does not remove an avatar, heal it or reset cooldowns',async t=>{const{app,request,login,action}=await serve(t);const p=await login();await request('/api/account/register',{token:p.token,value:{username:'combat',password}});await action(p,{type:'realm',target:'realm-1'});const engine=app.rooms.get('PUBLIC').engine,avatar=engine.players.get(p.playerId);avatar.x=2860;avatar.y=3450;engine.world(avatar).enemies=[];avatar.hp=40;avatar.abilityCd=7;const signed=(await request('/api/account/login',{value:{username:'combat',password}})).data;assert(engine.players.has(p.playerId));assert.equal(avatar.worldId,'realm-1');assert(avatar.hp<45);assert(avatar.abilityCd>5);const other=await request('/api/session',{token:signed.token,value:{protocol:2,name:'Combat',classId:'weaver',room:'OTHER'}});assert.equal(other.status,409);const current=await login('Combat',signed.token);assert.equal(current.snapshot.world.id,'realm-1');assert.equal((await request('/api/account/logout',{token:signed.token,value:{}})).status,409);});
test('A second account login terminates the old SSE stream and preserves the body',async t=>{const{request,login,base,app}=await serve(t);const p=await login();await request('/api/account/register',{token:p.token,value:{username:'streamswap',password}});const events=await stream(base,p.token);t.after(()=>events.stop());assert.equal((await events.next()).type,'snapshot');const next=await request('/api/account/login',{value:{username:'streamswap',password}});assert.equal(next.status,200);let replaced=false;for(let i=0;i<20;i++){const event=await events.next();if(event.type==='replaced'){replaced=true;break;}}assert(replaced);assert.equal(app.rooms.get('PUBLIC').engine.players.size,1);});
test('Recovery code changes password once, rotates token, and cannot be reused',async t=>{const{request,login}=await serve(t);const p=await login();const registration=(await request('/api/account/register',{token:p.token,value:{username:'recovery',password}})).data;const newPassword=password+'-new';const recovered=await request('/api/account/recover',{value:{username:'recovery',recoveryCode:registration.recoveryCode,password:newPassword}});assert.equal(recovered.status,200);assert.notEqual(recovered.data.recoveryCode,registration.recoveryCode);assert.notEqual(recovered.data.token,p.token);assert.equal((await request('/api/account/login',{value:{username:'recovery',password}})).status,401);assert.equal((await request('/api/account/recover',{value:{username:'recovery',recoveryCode:registration.recoveryCode,password:newPassword}})).status,401);assert.equal((await request('/api/account/login',{value:{username:'recovery',password:newPassword}})).status,200);});
test('Invalid credentials, duplicate names, weak passwords and input types are rejected',async t=>{const{request,login}=await serve(t);const a=await login(),b=await login('Beta');assert.equal((await request('/api/account/register',{token:a.token,value:{username:'name',password:'short'}})).status,400);assert.equal((await request('/api/account/register',{token:a.token,value:{username:'name',password}})).status,200);assert.equal((await request('/api/account/register',{token:b.token,value:{username:'NAME',password}})).status,409);assert.equal((await request('/api/account/login',{value:{username:'name',password:password+'wrong'}})).status,401);assert.equal((await request('/api/account/login',{value:{username:{value:'name'},password}})).status,401);assert.equal((await request('/api/account/login',{value:{username:'missing',password}})).status,401);assert.equal((await request('/api/account/recover',{value:{username:'name',recoveryCode:'x'.repeat(32),password}})).status,401);});
test('Authentication rate limits block repeated attempts instead of unlimited password jobs',async t=>{const{request}=await serve(t);for(let i=0;i<8;i++)assert.equal((await request('/api/account/login',{value:{username:'test',password:'invalid'}})).status,401);assert.equal((await request('/api/account/login',{value:{username:'test',password:'invalid'}})).status,429);});
test('Account logout rotates its credential and account deletion removes login and guild membership',async t=>{const{request,login,app,action}=await serve(t);const p=await login();await request('/api/account/register',{token:p.token,value:{username:'erase',password}});const avatar=app.rooms.get('PUBLIC').engine.players.get(p.playerId);avatar.bank=500;await action(p,{type:'guildCreate',name:'Delete Me'});assert(app.social.get(p.playerId));assert.equal((await request('/api/account/logout',{token:p.token,value:{}})).status,200);assert.equal((await request('/api/profile',{token:p.token})).status,401);const auth=(await request('/api/account/login',{value:{username:'erase',password}})).data;await login('Erase',auth.token);assert.equal((await request('/api/profile',{token:auth.token,method:'DELETE',value:{confirm:'DELETE'}})).status,200);assert(!app.social.get(p.playerId));assert.equal((await request('/api/account/login',{value:{username:'erase',password}})).status,401);});
test('Two HTTP clients exchange items; third-party snapshots stay private; both profiles commit',async t=>{const{app,login,action,request,base}=await serve(t);const a=await login('Alpha'),b=await login('Beta'),c=await login('Observer');const engine=app.rooms.get('PUBLIC').engine,p=engine.players.get(a.playerId),q=engine.players.get(b.playerId);p.inventory=[makeItem('owned-alpha','weaver','weapon',2,1)];q.inventory=[makeItem('owned-beta','weaver','charm',3,2)];const sa=await stream(base,a.token),sb=await stream(base,b.token);t.after(()=>{sa.stop();sb.stop();});await sa.next();await sb.next();assert((await action(a,{type:'tradeInvite',playerId:b.playerId})).data.accepted);const trade=engine.tradeFor(a.playerId);assert((await action(b,{type:'tradeAccept',tradeId:trade.id})).data.accepted);await action(a,{type:'tradeOffer',tradeId:trade.id,itemIds:['owned-alpha']});await action(b,{type:'tradeOffer',tradeId:trade.id,itemIds:['owned-beta']});const observation=await action(c,{type:'nonsense'});assert.equal(observation.data.snapshot.trade,null);assert(!JSON.stringify(observation.data.snapshot).includes('owned-alpha'));assert((await action(a,{type:'tradeConfirm',tradeId:trade.id,revision:trade.revision})).data.accepted);assert.equal(p.inventory[0].id,'owned-alpha');assert((await action(b,{type:'tradeConfirm',tradeId:trade.id,revision:trade.revision})).data.accepted);assert.equal(app.store.find(a.token).profile.inventory[0].id,'owned-beta');assert.equal(app.store.find(b.token).profile.inventory[0].id,'owned-alpha');assert.equal((await request('/api/profile',{token:a.token})).data.profile.inventory[0].id,'owned-beta');});
test('Trade storage failure rolls back SQLite and freezes all world actions until restart',async t=>{const{app,login,action,request}=await serve(t);const a=await login('Alpha'),b=await login('Beta'),engine=app.rooms.get('PUBLIC').engine,p=engine.players.get(a.playerId),q=engine.players.get(b.playerId);p.inventory=[makeItem('before-a','weaver')];q.inventory=[makeItem('before-b','weaver')];await action(a,{type:'tradeInvite',playerId:b.playerId});const trade=engine.tradeFor(a.playerId);await action(b,{type:'tradeAccept',tradeId:trade.id});await action(a,{type:'tradeOffer',tradeId:trade.id,itemIds:['before-a']});await action(b,{type:'tradeOffer',tradeId:trade.id,itemIds:['before-b']});await action(a,{type:'tradeConfirm',tradeId:trade.id,revision:trade.revision});const save=app.store.save.bind(app.store);app.store.save=(id,profile)=>{if(id===b.playerId)throw Error('simulated disk full');return save(id,profile);};assert.equal((await action(b,{type:'tradeConfirm',tradeId:trade.id,revision:trade.revision})).status,503);assert.equal(app.store.find(a.token).profile.inventory[0].id,'before-a');assert.equal(app.store.find(b.token).profile.inventory[0].id,'before-b');assert.equal((await request('/health')).status,503);assert.equal((await action(a,{type:'nexus'})).status,503);const before=engine.time;await new Promise(r=>setTimeout(r,130));assert.equal(engine.time,before);});
test('Named credentials, four-slot roster and guild survive actual server close and restart',async()=>{const dir=mkdtempSync(join(tmpdir(),'nyrathen-v03-')),db=join(dir,'state.sqlite');let first,second;try{first=await serve(null,{dataPath:db});const p=await first.login();await first.request('/api/account/register',{token:p.token,value:{username:'durable',password}});const avatar=first.app.rooms.get('PUBLIC').engine.players.get(p.playerId);avatar.bank=200;await first.action(p,{type:'guildCreate',name:'Durable Guild'});await first.action(p,{type:'characterCreate',classId:'kensei',name:'Durable'});await first.app.close();first=null;second=await serve(null,{dataPath:db});const auth=await second.request('/api/account/login',{value:{username:'durable',password}});assert.equal(auth.status,200);const joined=await second.login('Ignored',auth.data.token),own=joined.snapshot.players.find(q=>q.id===joined.playerId);assert.equal(own.classId,'kensei');assert.equal(own.account.characters.length,2);assert.equal(joined.snapshot.guild.name,'Durable Guild');assert.equal(own.bank,100);}finally{if(first)await first.app.close();if(second)await second.app.close();rmSync(dir,{recursive:true,force:true});}});
test('Friend links persist through an actual server close and restart',async()=>{const dir=mkdtempSync(join(tmpdir(),'nyrathen-v06-friends-')),db=join(dir,'state.sqlite');let first,second;try{first=await serve(null,{dataPath:db});const a=await first.login('Alpha'),b=await first.login('Beta');assert((await first.action(a,{type:'friendRequest',playerId:b.playerId})).data.accepted);assert((await first.action(b,{type:'friendAccept',playerId:a.playerId})).data.accepted);assert.equal(first.app.social.friendView(a.playerId).contacts[0].id,b.playerId);await first.app.close();first=null;second=await serve(null,{dataPath:db});const ra=await second.login('Alpha',a.token),rb=await second.login('Beta',b.token);const sa=ra.snapshot.friends,sb=rb.snapshot.friends;assert.equal(sa.contacts[0].id,b.playerId);assert.equal(sb.contacts[0].id,a.playerId);}finally{if(first)await first.app.close();if(second)await second.app.close();rmSync(dir,{recursive:true,force:true});}});
