// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import test from 'node:test';
import assert from 'node:assert/strict';
import { AdventureEngine, cleanAdventureProfile } from '../shared/adventure.mjs';
import { GuildService } from '../shared/social.mjs';
import { CLASSES, ENEMY_TYPES, walkable, TILE, dist } from '../shared/data.mjs';
import { makeItem, DUNGEONS, makeRealmMap, canEquip, EQUIP_SLOTS } from '../shared/realm-data.mjs';
import { CONTRACTS } from '../shared/adventure-data.mjs';
import { accountXPForLevel } from '../shared/endgame-data.mjs';
function fixture(cls='weaver',options={}){const e=new AdventureEngine(options),p=e.addPlayer('a','Alpha',cls);p.account.accountXP=accountXPForLevel(50);return{e,p};}
function field(cls='weaver'){const{e,p}=fixture(cls);assert(e.action(p.id,{type:'realm',target:'realm-1'}));p.x=2860;p.y=3450;p.invulnerable=0;const w=e.world(p);w.enemies=[];w.bullets=[];return{e,p,w};}
const tick=(e,n)=>{for(let i=0;i<n;i++)e.step(.05);};
const item=(id,cls='weaver',slot='weapon',tier=1)=>makeItem(id,cls,slot,tier,1);
function trader(){const{e,p}=fixture();const q=e.addPlayer('b','Beta','weaver');p.inventory=[item('alpha')];q.inventory=[item('beta')];assert(e.action(p.id,{type:'tradeInvite',playerId:q.id}));const t=e.tradeFor(p.id);assert(e.action(q.id,{type:'tradeAccept',tradeId:t.id}));return{e,p,q,t};}
const offer=(e,p,t,ids)=>e.action(p.id,{type:'tradeOffer',tradeId:t.id,itemIds:ids});
const confirm=(e,p,t,revision=t.revision)=>e.action(p.id,{type:'tradeConfirm',tradeId:t.id,revision});

test('V5 migrates V2 saves without losing vault, items, health or active character',()=>{const raw={version:2,started:true,name:'Legacy',classId:'warden',hp:80,level:8,bank:22,vault:[item('legacy')],equipment:{weapon:item('blade','warden')}};const p=cleanAdventureProfile(raw);assert.equal(p.version,6);assert.equal(p.account.characters.length,1);assert.equal(p.account.characters[0].profile.level,8);assert.equal(p.hp,80);assert.equal(p.vault[0].id,'legacy');assert.equal(p.bank,22);});
for(const cls of Object.keys(CLASSES))test(`${cls}: actual Adventure ability executes, costs mana, enforces cooldown and round-trips`,()=>{const{e,p,w}=field(cls);p.hp=80;const enemy=w.spawnEnemy('brute',p.x+100,p.y);enemy.hp=enemy.maxHP=5000;const mp=p.mp;assert(e.action(p.id,{type:'ability'}));assert(p.mp<mp);assert(p.abilityCd>0);assert(!e.action(p.id,{type:'ability'}));tick(e,4);assert(Number.isFinite(p.x)&&Number.isFinite(p.hp));assert.equal(cleanAdventureProfile(e.profile(p.id)).classId,cls);if(cls==='summoner')assert.equal(e.effects.filter(f=>f.kind==='summon').length,2);if(cls==='paladin')assert(p.empowered>0);if(cls==='bard')assert(p.inspired>0);if(cls==='assassin')assert(e.effects.some(f=>f.kind==='poison'));if(cls==='mystic')assert(enemy.stun>0);if(cls==='samurai')assert(enemy.exposed>0);if(cls==='ninja')assert(p.haste>0);if(cls==='trickster'||cls==='kensei')assert(p.x>2860);});
test('Every additional dungeon has different connected geometry and distinct content',()=>{assert.equal(Object.keys(DUNGEONS).length,18);const layouts=Object.keys(DUNGEONS).slice(4).map(theme=>JSON.stringify(makeRealmMap('dungeon',30,theme).rooms));assert.equal(new Set(layouts).size,14);for(const theme of Object.keys(DUNGEONS)){const{e,p}=fixture();p.bank=5000;p.account.totals['boss:sovereign']=1;assert(e.action(p.id,{type:'openDungeon',theme}),theme);const portal=e.world(p).portals.find(q=>q.owner===p.id);p.x=portal.x;p.y=portal.y;assert(e.action(p.id,{type:'portal',portalId:portal.id}));const w=e.world(p);assert.equal(w.theme,theme);assert(w.enemies.some(m=>m.dungeonBoss));for(const m of w.enemies)assert(walkable(w.map,m.x,m.y,m.radius),theme+' '+m.kind);}});
test('The new six bosses produce six distinct real projectile and hazard patterns',()=>{const signatures=[];for(const kind of ['plague','queen','smith','frostking','oracle','voidheart']){const{e,p,w}=field();const b=w.spawnEnemy(kind,p.x+200,p.y);b.phase=3;b.pattern=2;b.angle=0;b.spin=.2;assert(e.bossPattern(w,b,p,ENEMY_TYPES[kind]));signatures.push(JSON.stringify([w.bullets.length,e.effects.length,w.bullets.map(b=>Math.round(b.angle*100))]));assert(w.bullets.length||e.effects.length);for(const effect of e.effects)if(effect.kind==='danger')assert(effect.warn>=1);}assert.equal(new Set(signatures).size,6);});
test('Danger fields warn before damage, then expire instead of persisting forever',()=>{const{e,p,w}=field();e.effects.push({id:'danger',kind:'danger',worldId:p.worldId,owner:'enemy',x:p.x,y:p.y,radius:100,life:2,warn:1,tick:0,damage:30});const hp=p.hp;tick(e,10);assert(p.hp>=hp);tick(e,11);assert(p.hp<hp);tick(e,21);assert(!e.effects.length);});
test('Characters keep separate gear/levels while sharing bank, vault and fame',()=>{const{e,p}=fixture();p.level=9;p.inventory=[item('original')];p.vault=[item('vault')];p.bank=100;p.fame=200;const old=p.account.activeId;assert(e.action(p.id,{type:'characterCreate',name:'Second',classId:'paladin'}));const next=p.account.activeId;assert.equal(p.classId,'paladin');assert.equal(p.level,1);assert.equal(p.inventory.length,0);assert.equal(p.bank,100);p.level=5;p.inventory=[item('paladinbag','paladin')];p.bank=123;assert(e.action(p.id,{type:'characterSwitch',characterId:old}));assert.equal(p.level,9);assert.equal(p.inventory[0].id,'original');assert.equal(p.bank,123);assert.equal(p.vault[0].id,'vault');assert.equal(p.fame,200);const profile=JSON.parse(JSON.stringify(e.profile(p.id)));const r=new AdventureEngine();const restored=r.addPlayer('a',profile.name,profile.classId,profile);assert(r.action('a',{type:'characterSwitch',characterId:next}));assert.equal(restored.level,5);assert.equal(restored.inventory[0].id,'paladinbag');assert.equal(restored.bank,123);});
test('Four character cap, safe-zone switching, explicit deletion and active-slot protection',()=>{const{e,p}=fixture();for(let i=0;i<3;i++)assert(e.action(p.id,{type:'characterCreate',classId:'ninja',name:'N'+i}));assert.equal(p.account.characters.length,4);assert(!e.action(p.id,{type:'characterCreate',classId:'bard'}));const old=p.account.characters[0].id;assert(!e.action(p.id,{type:'characterDelete',characterId:old}));assert(!e.action(p.id,{type:'characterDelete',characterId:p.account.activeId,confirm:'DELETE'}));assert(e.action(p.id,{type:'realm',target:'realm-1'}));assert(!e.action(p.id,{type:'characterSwitch',characterId:old}));assert(!e.action(p.id,{type:'characterDelete',characterId:old,confirm:'DELETE'}));assert(e.action(p.id,{type:'nexus'}));assert(e.action(p.id,{type:'characterDelete',characterId:old,confirm:'DELETE'}));assert.equal(p.account.characters.length,3);});
test('Death history and a second living character survive permadeath and serialization',()=>{const{e,p}=fixture();p.inventory=[item('firstlife')];const first=p.account.activeId;e.action(p.id,{type:'characterCreate',classId:'bard',name:'Musician'});const second=p.account.activeId;e.action(p.id,{type:'realm',target:'realm-1'});p.x=2860;p.y=3450;p.invulnerable=0;p.level=7;p.bank=100;p.vault=[item('safe')];p.inventory=[item('lost')];e.world(p).damagePlayer(p,100000,'Test Boss');assert(p.dead);assert.equal(p.mp,0);assert.equal(p.account.history.length,1);assert.equal(p.account.history[0].level,7);assert(e.action(p.id,{type:'characterSwitch',characterId:first}));assert(!p.dead);assert.equal(p.inventory[0].id,'firstlife');assert.equal(p.bank,100);assert(p.account.characters.find(c=>c.id===second).profile.dead);assert.equal(cleanAdventureProfile(e.profile(p.id)).account.history.length,1);});
test('Profile sanitizer removes duplicate item IDs across active character, vault and inactive slots',()=>{const p=cleanAdventureProfile({started:true,classId:'weaver',inventory:[item('shared')],vault:[item('vault')],account:{activeId:'a',characters:[{id:'a'},{id:'b',profile:{started:true,classId:'bard',inventory:[item('shared'),item('own','bard')],equipment:{weapon:item('vault','bard')}}}]}});const inactive=p.account.characters.find(c=>c.id==='b').profile;assert.equal(inactive.inventory.length,1);assert.equal(inactive.inventory[0].id,'own');assert(!inactive.equipment.weapon);});
test('Shared weapon and armour families equip correctly but class abilities stay exclusive',()=>{assert(canEquip(item('sword','warden'),'paladin'));assert(canEquip(item('bow','ranger'),'bard'));assert(canEquip(item('katana','ninja'),'samurai'));assert(!canEquip(item('wrong','warden'),'weaver'));assert(!canEquip(item('shield','warden','ability'),'paladin'));const{e,p}=fixture('paladin');p.inventory=[item('sword','warden')];assert(e.action(p.id,{type:'equip',itemId:'sword'}));});
test('Earned contracts credit once only, persist through death, and cannot be forged remotely',()=>{const{e,p,w}=field();for(let i=0;i<10;i++){const m=w.spawnEnemy('crab',p.x+30,p.y);w.damageEnemy(m,1000,p.id);}assert.equal(p.account.totals.kills,10);assert(!e.action(p.id,{type:'claimContract',contractId:'first10'}));e.action(p.id,{type:'nexus'});const before=p.bank;assert(e.action(p.id,{type:'claimContract',contractId:'first10'}));assert.equal(p.bank,before+55);assert(!e.action(p.id,{type:'claimContract',contractId:'first10'}));assert(!e.action(p.id,{type:'claimContract',contractId:'void'}));assert(cleanAdventureProfile(e.profile(p.id)).account.claims.includes('first10'));});
test('Personal quest/character history is not disclosed in another player snapshot',()=>{const{e,p}=fixture();p.account.totals.kills=100;p.account.history.push({name:'Secret'});e.addPlayer('b','Beta','warden');const s=e.snapshot('b');assert(!s.players.find(q=>q.id===p.id).account);assert(!JSON.stringify(s).includes('Secret'));});
test('Pet adoption charges earned currency and passive benefits stay owned across characters',()=>{const{e,p}=fixture();assert(!e.action(p.id,{type:'petAdopt',petId:'fox'}));p.bank=250;assert(e.action(p.id,{type:'petAdopt',petId:'fox'}));assert.equal(p.bank,100);assert(!e.action(p.id,{type:'petAdopt',petId:'fox'}));assert(e.action(p.id,{type:'characterCreate',classId:'bard'}));assert.equal(p.account.petActive,'fox');assert.equal(e.snapshot(p.id).pets.length,1);assert(e.action(p.id,{type:'petSelect',petId:null}));assert(!e.snapshot(p.id).pets.length);assert(!e.action(p.id,{type:'petSelect',petId:'drake'}));});
test('Pets accumulate XP from contributed kills and fire actual server-owned projectiles',()=>{const{e,p,w}=field();p.account.petOwned=['drake'];p.account.petActive='drake';p.account.petXP={drake:0};const m=w.spawnEnemy('brute',p.x+100,p.y);m.hp=m.maxHP=5000;tick(e,2);assert(w.bullets.some(b=>b.team==='player'));w.damageEnemy(m,10000,p.id);assert.equal(p.account.petXP.drake,3);});
test('Forge keeps item identity, increments real tier and enforces costs and cap',()=>{const{e,p}=fixture();p.inventory=[item('forge')];p.bank=1000;const before=p.inventory[0].stat;assert(e.action(p.id,{type:'forge',itemId:'forge'}));assert.equal(p.inventory[0].id,'forge');assert.equal(p.inventory[0].tier,2);assert(p.inventory[0].stat>before);assert.equal(p.bank,860);p.inventory[0].tier=7;assert(!e.action(p.id,{type:'forge',itemId:'forge'}));assert(!e.action(p.id,{type:'forge',itemId:'not-owned'}));});
test('Purchased dungeon portals are shared, paid once, limited and endgame-gated',()=>{const{e,p}=fixture();const q=e.addPlayer('b','Beta','warden');p.bank=500;assert(!e.action(p.id,{type:'openDungeon',theme:'void'}));assert(e.action(p.id,{type:'openDungeon',theme:'hive'}));assert.equal(p.bank,380);assert(!e.action(p.id,{type:'openDungeon',theme:'forge'}));const portal=e.world(p).portals.find(q=>q.owner===p.id);p.x=q.x=portal.x;p.y=q.y=portal.y;assert(e.action(p.id,{type:'portal',portalId:portal.id}));assert(e.action(q.id,{type:'portal',portalId:portal.id}));assert.equal(p.worldId,q.worldId);assert.equal(e.world(p).theme,'hive');});
test('Final citadel victory opens the shared void gateway and awards real boss credit',()=>{const{e,p}=fixture();p.bank=1000;e.action(p.id,{type:'openDungeon',theme:'citadel'});const door=e.world(p).portals.find(q=>q.owner===p.id);p.x=door.x;p.y=door.y;e.action(p.id,{type:'portal',portalId:door.id});const w=e.world(p),b=w.enemies.find(q=>q.dungeonBoss);p.x=b.x-40;p.y=b.y;w.damageEnemy(b,100000,p.id);assert.equal(p.account.totals['boss:sovereign'],1);assert.equal(p.account.totals.dungeons,1);const portal=w.portals.find(q=>q.theme==='void');assert(portal);p.x=portal.x;p.y=portal.y;assert(e.action(p.id,{type:'portal',portalId:portal.id}));assert.equal(e.world(p).theme,'void');});
test('Trade swaps real items only after both confirmations and leaves no duplicate',()=>{const{e,p,q,t}=trader();assert(offer(e,p,t,['alpha']));assert(offer(e,q,t,['beta']));assert(confirm(e,p,t));assert.equal(p.inventory[0].id,'alpha');assert(confirm(e,q,t));assert.equal(p.inventory[0].id,'beta');assert.equal(q.inventory[0].id,'alpha');assert(!e.tradeFor(p.id));assert.equal(new Set([...p.inventory,...q.inventory].map(i=>i.id)).size,2);});
test('Changed trade offer clears all confirmations and rejects stale revision packets',()=>{const{e,p,q,t}=trader();offer(e,p,t,['alpha']);offer(e,q,t,['beta']);const old=t.revision;assert(confirm(e,p,t));assert(offer(e,q,t,[]));assert.deepEqual(t.confirmed,[]);assert(!confirm(e,p,t,old));assert(!confirm(e,q,t,old));assert.equal(p.inventory[0].id,'alpha');});
test('Trade rejects forged or duplicate IDs and blocks competing inventory mutations',()=>{const{e,p,q,t}=trader();assert(!offer(e,p,t,['beta']));assert(!offer(e,p,t,['alpha','alpha']));for(const type of ['equip','consume','salvage','forge','deposit'])assert(!e.action(p.id,{type,itemId:'alpha'}));assert(!e.action(p.id,{type:'characterCreate',classId:'bard'}));assert.equal(p.inventory[0].id,'alpha');});
test('Trade enforces capacity, proximity, safe zone, timeout and recipient acceptance',()=>{const{e,p,q,t}=trader();p.inventory=Array.from({length:8},(_,i)=>item('full'+i));offer(e,q,t,['beta']);assert(!confirm(e,p,t));p.inventory=[];assert(confirm(e,p,t));q.x+=400;assert(!confirm(e,q,t));assert(!e.tradeFor(p.id));q.x=p.x;assert(e.action(p.id,{type:'tradeInvite',playerId:q.id}));const invite=e.tradeFor(p.id);assert(!e.action(p.id,{type:'tradeAccept',tradeId:invite.id}));tick(e,1801);assert(!e.tradeFor(p.id));});
test('A third party can neither see negotiated inventories nor join the trade',()=>{const{e,p,q,t}=trader();e.addPlayer('c','Observer','bard');offer(e,p,t,['alpha']);assert.equal(e.snapshot('c').trade,null);assert(!JSON.stringify(e.snapshot('c')).includes('alpha'));assert(!e.action('c',{type:'tradeInvite',playerId:p.id}));assert(!e.action('c',{type:'tradeConfirm',tradeId:t.id,revision:t.revision}));});
test('Leaving Nexus or disconnecting cancels any pending trade',()=>{const{e,p,q,t}=trader();assert(e.action(p.id,{type:'realm',target:'realm-1'}));assert(!e.tradeFor(p.id));e.action(p.id,{type:'nexus'});assert(e.action(p.id,{type:'tradeInvite',playerId:q.id}));q.connected=false;tick(e,1);assert(!e.tradeFor(p.id));});
test('Guild membership requires leader approval; permission checks reject spoofed promotions/kicks',()=>{const{e,p}=fixture();p.bank=200;const q=e.addPlayer('b','Beta','warden');assert(e.action(p.id,{type:'guildCreate',name:'Aschenwacht'}));const g=e.guildService.get(p.id);assert.equal(p.bank,100);assert(e.action(q.id,{type:'guildRequest',code:g.code}));assert(!e.guildService.get(q.id));assert(!e.action(q.id,{type:'guildApprove',playerId:q.id}));assert(e.action(p.id,{type:'guildApprove',playerId:q.id}));assert(!e.action(q.id,{type:'guildKick',playerId:p.id}));assert(!e.action(q.id,{type:'guildPromote',playerId:q.id}));assert(e.action(p.id,{type:'guildPromote',playerId:q.id}));assert.equal(g.leader,q.id);assert(e.action(q.id,{type:'guildLeave'}));assert.equal(g.leader,p.id);});
test('Guild donation, name uniqueness, private chat and saved membership work across regions',()=>{const social=new GuildService(),a=new AdventureEngine({social}),b=new AdventureEngine({social});const p=a.addPlayer('p','One','bard'),q=b.addPlayer('q','Two','bard'),z=b.addPlayer('z','Observer','bard');p.bank=1000;assert(a.action(p.id,{type:'guildCreate',name:'Gildenbund'}));const guild=social.get(p.id);q.bank=1000;assert(!b.action(q.id,{type:'guildCreate',name:'Gildenbund'}));assert(b.action(q.id,{type:'guildRequest',code:guild.code}));assert(a.action(p.id,{type:'guildApprove',playerId:q.id}));assert(b.action(q.id,{type:'guildDonate',amount:500}));assert.equal(social.view(q.id).level,2);assert.equal(q.bank,500);assert(!b.action(q.id,{type:'guildDonate',amount:-1}));assert(a.action(p.id,{type:'chat',channel:'guild',text:'Across regions'}));assert(b.snapshot(q.id).chat.some(m=>m.text==='Across regions'));assert(!b.snapshot(z.id).chat.some(m=>m.text==='Across regions'));const restored=new GuildService(JSON.parse(JSON.stringify(social.export())));assert.equal(restored.get(q.id).id,guild.id);assert.equal(restored.get(p.id).bank,500);assert.equal(restored.messages.length,0);});
test('Guild maximum 30 members is enforced and deleted accounts are removed',()=>{const{e,p}=fixture();p.bank=200;e.action(p.id,{type:'guildCreate',name:'Thirty'});const g=e.guildService.get(p.id);for(let i=0;i<29;i++){const q=e.addPlayer('g'+i,'Member','bard');assert(e.action(q.id,{type:'guildRequest',code:g.code}));assert(e.action(p.id,{type:'guildApprove',playerId:q.id}));}const overflow=e.addPlayer('overflow','Overflow','bard');assert(!e.action(overflow.id,{type:'guildRequest',code:g.code}));assert.equal(g.members.length,30);e.guildService.removeAccount(p.id);assert.equal(g.members.length,29);assert(!e.guildService.get(p.id));assert.notEqual(g.leader,p.id);});
test('Whole adventure roundtrip preserves roster, contracts, pets, guild and dungeon progress',()=>{const{e,p}=fixture();p.bank=5000;p.account.claims=['first10'];p.account.totals.kills=12;e.action(p.id,{type:'petAdopt',petId:'moth'});e.action(p.id,{type:'guildCreate',name:'Persistent'});e.action(p.id,{type:'characterCreate',classId:'summoner'});e.action(p.id,{type:'openDungeon',theme:'frost'});const d=e.world(p).portals.find(q=>q.owner===p.id);p.x=d.x;p.y=d.y;e.action(p.id,{type:'portal',portalId:d.id});const boss=e.world(p).enemies.find(q=>q.dungeonBoss);boss.hp-=300;const profile=e.profile(p.id),worlds=e.exportWorlds();const r=new AdventureEngine({savedWorld:JSON.parse(JSON.stringify(worlds))});const q=r.addPlayer(p.id,p.name,p.classId,JSON.parse(JSON.stringify(profile)));assert.equal(q.account.characters.length,2);assert.equal(q.account.petActive,'moth');assert(q.account.claims.includes('first10'));assert.equal(q.account.totals.kills,12);assert.equal(r.guildService.get(q.id).name,'Persistent');assert.equal(r.world(q).theme,'frost');assert.equal(r.world(q).enemies.find(x=>x.dungeonBoss).hp,boss.hp);});
test('Guild and realm messages use a comparable clock even when regions have different ages',()=>{const social=new GuildService(),a=new AdventureEngine({social}),b=new AdventureEngine({social});a.time=80000;b.time=3;const p=a.addPlayer('clockA','Alpha','bard'),q=b.addPlayer('clockB','Beta','bard');p.bank=200;a.action(p.id,{type:'guildCreate',name:'Clockwatch'});const g=social.get(p.id);b.action(q.id,{type:'guildRequest',code:g.code});a.action(p.id,{type:'guildApprove',playerId:q.id});const start=Date.now();assert(a.action(p.id,{type:'chat',channel:'guild',text:'From older region'}));assert(b.action(q.id,{type:'chat',channel:'realm',text:'From new region'}));for(const m of b.snapshot(q.id).chat.filter(m=>m.text.startsWith('From ')))assert(m.time>=start&&m.time<=Date.now());assert.equal(b.snapshot(q.id).chat.filter(m=>m.text.startsWith('From ')).length,2);});
test('Deleting an account with only a pending guild request removes the request as well',()=>{const{e,p}=fixture();p.bank=200;const q=e.addPlayer('pending','Pending','bard');e.action(p.id,{type:'guildCreate',name:'Pendingwatch'});const g=e.guildService.get(p.id);e.action(q.id,{type:'guildRequest',code:g.code});assert.equal(g.requests.length,1);e.guildService.removeAccount(q.id);assert.equal(g.requests.length,0);assert.equal(g.members.length,1);});
test('Friend requests are reciprocal, private and survive social export/import',()=>{const social=new GuildService(),e=new AdventureEngine({social}),p=e.addPlayer('fa','Alpha','warden'),q=e.addPlayer('fb','Beta','bard'),z=e.addPlayer('fc','Gamma','ninja');assert(e.action(p.id,{type:'friendRequest',playerId:q.id}));let ps=e.snapshot(p.id),qs=e.snapshot(q.id),zs=e.snapshot(z.id);assert.equal(ps.friends.outgoing[0].id,q.id);assert.equal(qs.friends.incoming[0].id,p.id);assert.equal(zs.friends.contacts.length,0);assert(e.action(q.id,{type:'friendAccept',playerId:p.id}));ps=e.snapshot(p.id);qs=e.snapshot(q.id);assert.equal(ps.friends.contacts[0].id,q.id);assert.equal(qs.friends.contacts[0].id,p.id);assert(ps.friends.contacts[0].online);const restored=new GuildService(JSON.parse(JSON.stringify(social.export())));assert.equal(restored.friendView(p.id).contacts[0].id,q.id);assert.equal(restored.friendView(q.id).contacts[0].id,p.id);});
test('Reciprocal friend requests auto-accept and removal is symmetric',()=>{const{e,p}=fixture();const q=e.addPlayer('friend-b','Beta','bard');assert(e.action(p.id,{type:'friendRequest',playerId:q.id}));assert(e.action(q.id,{type:'friendRequest',playerId:p.id}));assert.equal(e.snapshot(p.id).friends.contacts.length,1);assert.equal(e.snapshot(q.id).friends.contacts.length,1);assert(e.action(p.id,{type:'friendRemove',playerId:q.id}));assert.equal(e.snapshot(p.id).friends.contacts.length,0);assert.equal(e.snapshot(q.id).friends.contacts.length,0);});
test('Friend actions reject spoofing, self requests and unavailable targets',()=>{const{e,p}=fixture();const q=e.addPlayer('friend-c','Beta','bard');assert(!e.action(p.id,{type:'friendRequest',playerId:p.id}));assert(!e.action(p.id,{type:'friendRequest',playerId:'missing'}));q.connected=false;assert(!e.action(p.id,{type:'friendRequest',playerId:q.id}));q.connected=true;assert(e.action(p.id,{type:'friendRequest',playerId:q.id}));assert(!e.action(p.id,{type:'friendAccept',playerId:q.id}));assert(e.action(p.id,{type:'friendDecline',playerId:q.id}));assert.equal(e.snapshot(p.id).friends.outgoing.length,0);});
test('Deleting an account removes pending requests and established friend links',()=>{const social=new GuildService(),e=new AdventureEngine({social}),p=e.addPlayer('friend-delete-a','Alpha','warden'),q=e.addPlayer('friend-delete-b','Beta','bard'),z=e.addPlayer('friend-delete-c','Gamma','ninja');assert(e.action(p.id,{type:'friendRequest',playerId:q.id}));assert(e.action(q.id,{type:'friendAccept',playerId:p.id}));assert(e.action(z.id,{type:'friendRequest',playerId:p.id}));social.removeAccount(p.id);assert.equal(social.friendView(q.id).contacts.length,0);assert.equal(social.friendView(z.id).outgoing.length,0);});
test('Direct friend chat is private to both participants and works across worlds in one region',()=>{const{e,p}=fixture();const q=e.addPlayer('direct-b','Beta','bard'),z=e.addPlayer('direct-c','Gamma','ninja');assert(e.action(p.id,{type:'friendRequest',playerId:q.id}));assert(e.action(q.id,{type:'friendAccept',playerId:p.id}));assert(e.action(q.id,{type:'realm',target:'realm-1'}));e.time+=1;assert(e.action(p.id,{type:'chat',channel:'friend',playerId:q.id,text:'Nur für Beta'}));assert(e.snapshot(p.id).chat.some(m=>m.text==='Nur für Beta'&&m.directTo===q.id));assert(e.snapshot(q.id).chat.some(m=>m.text==='Nur für Beta'&&m.directTo===q.id));assert(!e.snapshot(z.id).chat.some(m=>m.text==='Nur für Beta'));assert(!e.action(p.id,{type:'chat',channel:'friend',playerId:z.id,text:'nicht erlaubt'}));});
