// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';
import {createStateAuthority} from '../server/state-authority.mjs';import {createGameServer} from '../server/server.mjs';import {PROTOCOL} from '../shared/data.mjs';
const secret='d'.repeat(48),jsonHeaders={'Content-Type':'application/json'};
async function listen(server){server.listen(0,'127.0.0.1');await once(server,'listening');return `http://127.0.0.1:${server.address().port}`;}
async function setup(t){const state=createStateAuthority({dataPath:':memory:',secret,leaseTtlMs:1000}),stateBase=await listen(state.server);const a=createGameServer({stateAuthorityUrl:stateBase,stateAuthoritySecret:secret,nodeId:'game-a',worldNamespace:'shard-main'}),b=createGameServer({stateAuthorityUrl:stateBase,stateAuthoritySecret:secret,nodeId:'game-b',worldNamespace:'shard-main'}),baseA=await listen(a.server),baseB=await listen(b.server);t.after(async()=>{await a.close();await b.close();await state.close();});return{state,a,b,baseA,baseB};}
async function session(base,{token=null,name='Distributed',room='PUBLIC'}={}){const r=await fetch(base+'/api/session',{method:'POST',headers:{...jsonHeaders,...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({protocol:PROTOCOL,name,classId:'ranger',room})});return{r,j:await r.json()};}
const auth=token=>({Authorization:'Bearer '+token});

test('v5.5 two GameServers share one authoritative profile and reject split-brain login',async t=>{const{a,baseA,baseB}=await setup(t);const first=await session(baseA);assert.equal(first.r.status,200);const token=first.j.token,id=first.j.playerId;const denied=await session(baseB,{token});assert.equal(denied.r.status,409);assert.match(denied.j.error,/anderen Spielknoten/);const p=a.rooms.get('PUBLIC').engine.players.get(id);p.fame=777;await a.close();const moved=await session(baseB,{token});assert.equal(moved.r.status,200,moved.j.error);const profile=await(await fetch(baseB+'/api/profile',{headers:auth(token)})).json();assert.equal(profile.profile.fame,777);});

test('v5.5 named account credentials live in State Authority and work after node failover',async t=>{const{a,baseA,baseB}=await setup(t);const s=await session(baseA);const token=s.j.token;const reg=await fetch(baseA+'/api/account/register',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({username:'cluster-user',password:'a-very-long-password-55'})});assert.equal(reg.status,200);await a.close();const login=await fetch(baseB+'/api/account/login',{method:'POST',headers:jsonHeaders,body:JSON.stringify({username:'cluster-user',password:'a-very-long-password-55'})});const lj=await login.json();assert.equal(login.status,200,lj.error);assert.equal(lj.playerId,s.j.playerId);const opened=await session(baseB,{token:lj.token});assert.equal(opened.r.status,200,opened.j.error);});

test('v5.5 request receipts survive GameServer replacement',async t=>{const{a,baseA,baseB}=await setup(t);const s=await session(baseA),token=s.j.token,requestId='receipt_failover_0001';const action=await fetch(baseA+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'notARealAction',requestId})});const aj=await action.json();assert.equal(action.status,200);assert.equal(aj.accepted,false);assert.equal(aj.replayed,false);await a.close();const moved=await session(baseB,{token});assert.equal(moved.r.status,200);const replay=await fetch(baseB+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'notARealAction',requestId})});const rj=await replay.json();assert.equal(replay.status,200);assert.equal(rj.accepted,false);assert.equal(rj.replayed,true);});

test('v5.7 distributed action receipts do not depend on the worker-local profile cache',async t=>{const{a,baseA}=await setup(t);const s=await session(baseA),token=s.j.token,id=s.j.playerId,requestId='receipt_cache_race_0001';a.store.delete(id);assert.equal(a.store.profileById(id),null);const action=await fetch(baseA+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'notARealAction',requestId})});const aj=await action.json();assert.equal(action.status,200,aj.error);assert.equal(aj.accepted,false);assert.equal(aj.replayed,false);assert.equal(a.readiness().storageHealthy,true);assert.equal(a.store.db.prepare('SELECT COUNT(*) n FROM action_receipts').get().n,0);const replay=await fetch(baseA+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'notARealAction',requestId})});const rj=await replay.json();assert.equal(replay.status,200,rj.error);assert.equal(rj.accepted,false);assert.equal(rj.replayed,true);});

test('v5.5 guild/social state persists centrally across GameServer replacement',async t=>{const{a,baseA,baseB}=await setup(t);const s=await session(baseA),token=s.j.token,id=s.j.playerId,p=a.rooms.get('PUBLIC').engine.players.get(id);p.bank=500;const r=await fetch(baseA+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'guildCreate',name:'Veilguard',requestId:'guild_create_0001'})});const j=await r.json();assert.equal(r.status,200,j.error);assert.equal(j.accepted,true);await a.close();const moved=await session(baseB,{token});assert.equal(moved.r.status,200,moved.j.error);assert.equal(moved.j.snapshot.guild.name,'Veilguard');});

test('v5.7 fresh distributed guests use local receipt cache and skip non-social safety refresh',async t=>{const{a,baseA}=await setup(t);const s=await session(baseA),token=s.j.token;let receipts=0,safetyRefreshes=0;const receipt=a.stateClient.receipt.bind(a.stateClient),refresh=a.safety.refreshIfStale.bind(a.safety);a.stateClient.receipt=async(...args)=>{receipts++;return receipt(...args)};a.safety.refreshIfStale=async(...args)=>{safetyRefreshes++;return refresh(...args)};const requestId='fresh_cache_fastpath_0001';const first=await fetch(baseA+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'notARealAction',requestId})});const fj=await first.json();assert.equal(first.status,200,fj.error);assert.equal(fj.replayed,false);const replay=await fetch(baseA+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'notARealAction',requestId})});const rj=await replay.json();assert.equal(replay.status,200,rj.error);assert.equal(rj.replayed,true);assert.equal(receipts,0);assert.equal(safetyRefreshes,0);});

test('v5.7 transient central-state timeout does not permanently poison worker storage',async t=>{const{a,baseA}=await setup(t);const s=await session(baseA),token=s.j.token;const original=a.stateClient.persistBatch.bind(a.stateClient);a.stateClient.persistBatch=async()=>{throw Object.assign(new Error('State authority unavailable: The operation was aborted due to timeout'),{status:503})};const r=await fetch(baseA+'/api/action',{method:'POST',headers:{...jsonHeaders,...auth(token)},body:JSON.stringify({type:'notARealAction',requestId:'transient_state_timeout_0001'})});const j=await r.json();assert.equal(r.status,503,j.error);assert.equal(a.readiness().storageHealthy,true);assert.equal(a.readiness().stateBackendHealthy,false);a.stateClient.persistBatch=original;});
