import test from 'node:test';import assert from 'node:assert/strict';
import {ClusterBus,AccountLeaseRegistry,NodeDirectory} from '../server/cluster.mjs';
import {GameNetwork} from '../client/network.mjs';
test('cluster bus registers, heartbeats and removes game nodes',()=>{const b=new ClusterBus();b.register({id:'a',role:'game',base:'http://a',load:2});b.register({id:'b',role:'game',base:'http://b',load:1});assert.deepEqual(b.healthy('game').map(x=>x.id),['b','a']);assert.equal(b.heartbeat('a',{load:0}),true);assert.equal(b.healthy('game')[0].id,'a');assert.equal(b.unregister('a'),true)});
test('account lease prevents split brain ownership',()=>{let now=100;const r=new AccountLeaseRegistry({ttlMs:50,now:()=>now});const a=r.acquire('u','a');assert.ok(a);assert.equal(r.acquire('u','b'),null);assert.equal(r.owner('u').nodeId,'a')});
test('expired account lease can fail over with a higher epoch',()=>{let now=100;const r=new AccountLeaseRegistry({ttlMs:50,now:()=>now});const a=r.acquire('u','a');now=151;const b=r.acquire('u','b');assert.equal(b.nodeId,'b');assert.equal(b.epoch,a.epoch+1)});
test('stale lease holder cannot renew or release replacement lease',()=>{let now=100;const r=new AccountLeaseRegistry({ttlMs:50,now:()=>now});const a=r.acquire('u','a');now=151;const b=r.acquire('u','b');assert.equal(r.renew('u','a',a.epoch),null);assert.equal(r.release('u','a',a.epoch),false);assert.equal(r.owner('u').epoch,b.epoch)});
test('node directory chooses least loaded healthy replacement',()=>{const bus=new ClusterBus();bus.register({id:'a',role:'game',base:'http://a',load:9});bus.register({id:'b',role:'game',base:'http://b',load:1});const d=new NodeDirectory(bus);assert.equal(d.choose('game').id,'b');assert.deepEqual(d.candidates(),['http://b','http://a'])});
test('mobile network rotates to replacement base without changing token or generation',async()=>{const n=new GameNetwork(()=>{},()=>{},{retryDelays:[0]});n.closed=false;n.generation=7;n.base='http://a';n.bases=['http://a','http://b'];n.baseIndex=0;n.token='same-token';n.config={name:'x',classId:'ranger',room:'PUBLIC'};n.readStream=async()=>{throw new Error('down')};let opened='';n.openSession=async g=>{opened=n.base;n.connected=true;n.closed=true;return{}};await n.streamLoop(7);assert.equal(opened,'http://b');assert.equal(n.token,'same-token');assert.equal(n.generation,7)});
test('mobile initial connect falls through unreachable primary to replacement base',async()=>{
 const calls=[];const n=new GameNetwork(()=>{},()=>{},{fetch:async url=>{calls.push(url);if(url.startsWith('http://127.0.0.1:3001'))throw new Error('offline');return new Response(JSON.stringify({protocol:2,token:'x',playerId:'p',room:'PUBLIC',nextSequence:0,snapshot:{version:2,players:[],enemies:[]}}),{status:200,headers:{'Content-Type':'application/json'}});}});n.streamLoop=async()=>{};
 const r=await n.connect({base:'http://127.0.0.1:3001',bases:['http://127.0.0.1:3002'],name:'x',classId:'ranger',room:'PUBLIC'});assert.equal(r.playerId,'p');assert.equal(n.base,'http://127.0.0.1:3002');assert.equal(calls.length,2);n.disconnect();
});
test('mobile treats retryable lease-busy as transient during failover',async()=>{
 let attempts=0;const n=new GameNetwork(()=>{},()=>{},{fetch:async()=>{attempts++;if(attempts===1)return new Response(JSON.stringify({error:'busy',retryable:true}),{status:409,headers:{'Content-Type':'application/json'}});return new Response(JSON.stringify({protocol:2,token:'same',playerId:'p',room:'PUBLIC',nextSequence:0,snapshot:{version:2,players:[],enemies:[]}}),{status:200,headers:{'Content-Type':'application/json'}});}});n.streamLoop=async()=>{};
 const r=await n.connect({base:'http://127.0.0.1:3001',bases:['http://127.0.0.1:3002'],name:'x',classId:'ranger',room:'PUBLIC',token:'same'});assert.equal(r.playerId,'p');assert.equal(n.base,'http://127.0.0.1:3002');assert.equal(attempts,2);n.disconnect();
});
