// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtempSync, rmSync, readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { normalizeServerAddress, normalizeRegion, makeInvitation, parseInvitation, SnapshotDecoder } from '../client/protocol.mjs';
import { cleanDisplaySettings, selectObjective, edgeMarker } from '../client/presentation.mjs';
import { GameNetwork } from '../client/network.mjs';
import { createGameServer } from '../server/server.mjs';
import { ProfileStore } from '../server/store.mjs';
import { createBackup, inspectDatabase, restoreBackup, acquireDataLock } from '../server/operations.mjs';
import { clientAddress } from '../server/addresses.mjs';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,ms=2500){const end=Date.now()+ms;while(!fn()){if(Date.now()>end)throw new Error('Condition timed out');await wait(15);}}
async function serve(t,options={}){const app=createGameServer({dataPath:':memory:',...options});app.server.listen(0,'127.0.0.1');await once(app.server,'listening');if(t)t.after(()=>app.close());return{app,base:'http://127.0.0.1:'+app.server.address().port};}
function dir(t){const d=mkdtempSync(join(tmpdir(),'nyrathen-v04-'));t.after(()=>rmSync(d,{recursive:true,force:true}));return d;}
async function post(base,path,value,token=''){const response=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(value)});return{status:response.status,data:await response.json()};}
for(const bad of ['ftp://example.com','http://example.com','https://u:p@example.com','https://example.com/game','https://example.com/?token=x','https://example.com/#x','javascript:alert(1)','not a url'])test('server address rejects '+bad,()=>assert.throws(()=>normalizeServerAddress(bad)));
for(const good of ['https://game.example','http://localhost:3000','http://127.0.0.1:3000','http://192.168.1.2:3000','http://[::1]:3000'])test('server address accepts '+good,()=>assert.equal(normalizeServerAddress(good),good));
test('invite is credential-free and round trips region',()=>{const link=makeInvitation('https://game.example',' party01 ');assert.equal(link,'https://game.example/#join=PARTY01');assert.deepEqual(parseInvitation(link),{base:'https://game.example',room:'PARTY01'});assert.throws(()=>parseInvitation('https://game.example/#join=PUBLIC&token=secret'));assert.throws(()=>parseInvitation('https://game.example/?token=x#join=PUBLIC'));assert.throws(()=>normalizeRegion('abc/def'));});
test('SSE parser supports split CRLF, multiline data and multibyte text',()=>{const got=[],d=new SnapshotDecoder(m=>got.push(m));const text=':keepalive\r\n\r\ndata: {"name":\r\ndata: "Glut 🔥"}\r\n\r\n';for(const byte of new TextEncoder().encode(text))d.push(new Uint8Array([byte]));assert.deepEqual(got,[{name:'Glut 🔥'}]);assert.equal(d.pending,'');});
test('SSE parser rejects overlong and malformed messages',()=>{assert.throws(()=>new SnapshotDecoder(()=>{},8).push(new TextEncoder().encode('data: 0123456789')));assert.throws(()=>new SnapshotDecoder(()=>{}).push(new TextEncoder().encode('data: }\n\n')));});
test('settings constrain zoom and opacity and keep enemy cues independent',()=>{const s=cleanDisplaySettings({zoom:1e9,allyOpacity:-100,volume:12,quality:'unknown'});assert.equal(s.zoom,1);assert.equal(s.allyOpacity,1);assert.equal(s.volume,1);assert.equal(s.quality,'high');assert.equal(cleanDisplaySettings({zoom:.8,allyOpacity:.35,objectives:false}).zoom,.8);assert.equal(cleanDisplaySettings(null).damageNumbers,true);});
test('objective ignores dead enemies and directs dungeon players to living boss',()=>{const own={x:0,y:0,level:1,dead:false};const s={world:{kind:'dungeon'},enemies:[{id:'a',kind:'captain',x:500,y:0,hp:10,maxHP:100},{id:'b',kind:'captain',x:1,y:0,hp:0},{id:'c',kind:'slime',x:10,y:0,hp:4,maxHP:4}]};assert.equal(selectObjective(s,own).id,'a');s.world.kind='nexus';assert.equal(selectObjective(s,own),null);});
test('quest indicator respects bounds and has no NaN at screen center',()=>{const bounds={cx:200,cy:300,left:30,right:370,top:150,bottom:550};assert.deepEqual(edgeMarker(800,0,bounds),{x:370,y:300,angle:0});assert.equal(edgeMarker(0,0,bounds),null);assert.equal(edgeMarker(10,10,bounds),null);assert.equal(edgeMarker(NaN,1,bounds),null);});
test('untrusted forwarding headers cannot alter rate-limit identity',()=>{const r={socket:{remoteAddress:'::ffff:127.0.0.1'},headers:{'x-real-ip':'203.0.113.9'}};assert.equal(clientAddress(r),'127.0.0.1');assert.equal(clientAddress(r,new Set(['127.0.0.1'])),'203.0.113.9');r.headers['x-real-ip']='1.2.3.4, 5.6.7.8';assert.equal(clientAddress(r,new Set(['127.0.0.1'])),'127.0.0.1');});
test('out-of-order snapshots and retired generations never roll back view',()=>{const got=[],n=new GameNetwork(s=>got.push(s),()=>{});n.closed=false;n.generation=7;const s={version:2,players:[],enemies:[],wireEpoch:'epoch',revision:3};assert(n.acceptSnapshot(s,7));assert.equal(n.acceptSnapshot({...s,revision:2},7),false);assert.equal(n.acceptSnapshot({...s,revision:4},6),false);assert.equal(n.acceptSnapshot({...s,wireEpoch:'other',revision:4},7),false);assert.equal(got.length,1);n.disconnect();});
test('live networking reconnects the SAME avatar after stream loss',async t=>{const{app,base}=await serve(t);const statuses=[],n=new GameNetwork(()=>{},(s)=>statuses.push(s),{retryDelays:[10,20,30]});t.after(()=>n.disconnect());const login=await n.connect({base,name:'Ali',classId:'warden',room:'NET04'});await until(()=>n.connected);const s=[...app.sessions.values()][0],p=s.room.engine.players.get(login.playerId);p.mp=1;p.abilityCd=7;p.invulnerable=0;s.stream.destroy();await until(()=>n.metrics.reconnects===1&&n.connected);assert.equal(n.id,login.playerId);assert.equal(app.sessions.size,1);assert(p.abilityCd>5&&p.abilityCd<7);assert.equal(p.invulnerable,0);assert(statuses.includes('reconnecting'));});
test('replaced stream does NOT auto-reconnect and kick the new client',async t=>{const{base}=await serve(t);const events=[],a=new GameNetwork(()=>{},(s,m)=>events.push([s,m]),{retryDelays:[5]}),b=new GameNetwork(()=>{},()=>{});t.after(()=>{a.disconnect();b.disconnect();});const data=await a.connect({base,name:'Ali',classId:'warden',room:'DUP04'});await until(()=>a.connected);await b.connect({base,name:'Ali',classId:'warden',room:'DUP04',token:data.token});await until(()=>events.some(e=>e[0]==='disconnected'));await wait(70);assert(b.connected);assert.equal(a.metrics.reconnects,0);assert(!a.connected);});
test('lost action response retries same receipt without double consuming potion',async t=>{const{app,base}=await serve(t);let lost=false;const n=new GameNetwork(()=>{},()=>{},{fetch:async(url,options)=>{const r=await fetch(url,options);if(url.endsWith('/api/action')&&!lost){lost=true;await r.text();throw new Error('Simulated response lost after commit');}return r;}});t.after(()=>n.disconnect());const a=await n.connect({base,name:'Retry',classId:'weaver',room:'RETRY'});await until(()=>n.connected);const s=[...app.sessions.values()][0],p=s.room.engine.players.get(a.playerId);p.mp=0;assert(await n.action({type:'mana'}));assert.equal(p.manaPotions,2);assert.equal(app.store.db.prepare('SELECT COUNT(*) AS n FROM action_receipts').get().n,1);});
test('late action response cannot overwrite a new screen after disconnect',async()=>{let release;const got=[];const n=new GameNetwork(s=>got.push(s),()=>{},{fetch:()=>new Promise(r=>release=r)});n.closed=false;n.connected=true;n.generation=1;const action=n.action({type:'heal'});n.disconnect();release(new Response(JSON.stringify({accepted:true,snapshot:{version:2,players:[],enemies:[]}}),{status:200}));assert.equal(await action,false);assert.equal(got.length,0);});
test('disconnect cancels scheduled retry without another login attempt',async()=>{let calls=0;const n=new GameNetwork(()=>{},()=>{},{retryDelays:[100],fetch:async()=>{calls++;throw new Error('offline');}});n.closed=false;n.generation=1;n.readStream=async()=>{throw new Error('lost');};const loop=n.streamLoop(1);await wait(10);n.disconnect();await loop;assert.equal(calls,0);});
test('bounded reconnect attempts finish instead of spinning indefinitely',async()=>{let calls=0;const statuses=[];const n=new GameNetwork(()=>{},s=>statuses.push(s),{retryDelays:[1,1],fetch:async()=>{calls++;throw new Error('offline');}});n.closed=false;n.generation=1;n.readStream=async()=>{throw new Error('lost');};await assert.rejects(n.streamLoop(1),/Wiederverbindung beendet/);assert.equal(calls,2);n.disconnect();});
test('receipt persists across server restart and rejects payload substitution',async t=>{const path=join(dir(t),'server.sqlite');let{app,base}=await serve(null,{dataPath:path});let a;const action={type:'mana',requestId:'receipt-stable-0001'};try{a=(await post(base,'/api/session',{name:'Durable',classId:'weaver',room:'REST04',protocol:2})).data;const p=app.rooms.get('REST04').engine.players.get(a.playerId);p.mp=0;assert.equal((await post(base,'/api/action',action,a.token)).data.accepted,true);assert.equal((await post(base,'/api/action',{...action,type:'heal'},a.token)).status,409);}finally{await app.close();}({app,base}=await serve(null,{dataPath:path}));try{await post(base,'/api/session',{name:'Durable',classId:'weaver',room:'REST04',protocol:2},a.token);const duplicate=await post(base,'/api/action',action,a.token);assert(duplicate.data.replayed);assert(duplicate.data.accepted);assert.equal(app.rooms.get('REST04').engine.players.get(a.playerId).manaPotions,2);}finally{await app.close();}});
test('receipt commit failure pauses simulation rather than silently replaying',async t=>{const{app,base}=await serve(t);const a=(await post(base,'/api/session',{name:'Fail',classId:'weaver',room:'FAIL04',protocol:2})).data;app.rooms.get('FAIL04').engine.players.get(a.playerId).mp=0;app.store.saveReceipt=()=>{throw new Error('injected disk failure');};const action=await post(base,'/api/action',{type:'mana',requestId:'broken-receipt-01'},a.token);assert.equal(action.status,503);assert.equal((await fetch(base+'/health')).status,503);assert.equal(app.store.db.prepare('SELECT COUNT(*) AS n FROM action_receipts').get().n,0);});
test('database lock rejects concurrent writers and releases on shutdown',async t=>{const path=join(dir(t),'game.sqlite');const{app}=await serve(null,{dataPath:path});assert.throws(()=>createGameServer({dataPath:path}),/gesperrt/);await app.close();assert(!existsSync(path+'.lock'));const release=acquireDataLock(path);release();});
test('online WAL backup includes profile, world and credentials tables',async t=>{const root=dir(t),path=join(root,'game.sqlite'),store=new ProfileStore(path);t.after(()=>store.close());const a=store.create('Backup','warden');a.profile.bank=333;store.save(a.id,a.profile);store.saveWorld('PUBLIC',{version:2,worlds:[]});const report=await createBackup(store.db,join(root,'backups'));assert.equal(report.integrity,'ok');assert.equal(report.counts.players,1);assert.equal(report.counts.realms,1);assert.equal(report.sha256.length,64);assert.equal(inspectDatabase(join(root,'backups',report.file)).counts.credentials,0);});
test('backup retention keeps only newest verified snapshots',async t=>{const root=dir(t),store=new ProfileStore(join(root,'db.sqlite'));t.after(()=>store.close());store.create('Keep','warden');for(let i=0;i<4;i++)await createBackup(store.db,join(root,'backups'),{retain:2,now:new Date(1700000000000+i*1000)});assert.equal(readdirSync(join(root,'backups')).filter(f=>f.endsWith('.sqlite')).length,2);assert.equal(readdirSync(join(root,'backups')).length,4);});
test('restore requires confirmation, respects writer lock and preserves previous DB',async t=>{const root=dir(t),path=join(root,'db.sqlite'),store=new ProfileStore(path),a=store.create('Restore','warden');a.profile.bank=123;store.save(a.id,a.profile);const b=await createBackup(store.db,join(root,'backups'));a.profile.bank=987;store.save(a.id,a.profile);store.close();const source=join(root,'backups',b.file);await assert.rejects(restoreBackup(source,path),/confirm/);const release=acquireDataLock(path);await assert.rejects(restoreBackup(source,path,{confirm:true}),/gesperrt/);release();const result=await restoreBackup(source,path,{confirm:true});assert(result.previous);const restored=new ProfileStore(path);try{assert.equal(restored.find(a.token).profile.bank,123);}finally{restored.close();}assert.equal(inspectDatabase(join(path+'.before-restore',result.previous.file)).counts.players,1);});
test('corrupted backup checksum prevents touching current database',async t=>{const root=dir(t),path=join(root,'db.sqlite'),store=new ProfileStore(path);store.create('Safe','warden');const b=await createBackup(store.db,join(root,'backups'));store.close();const source=join(root,'backups',b.file);writeFileSync(source+'.sha256','0'.repeat(64));const before=readFileSync(path);await assert.rejects(restoreBackup(source,path,{confirm:true}),/SHA-256/);assert.deepEqual(readFileSync(path),before);});
test('server health exposes operational state, not credentials or inventory',async t=>{const{base}=await serve(t);const h=await(await fetch(base+'/health')).json();assert.equal(h.version,'5.7.0');assert.equal(h.players,0);assert.equal(h.backups.enabled,false);assert(!JSON.stringify(h).includes('token'));});
