import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {SecurityGuard,EconomyLedger,AdminAudit,LiveOpsConfig,ClusterDirector,Telemetry,PushOutbox,EntitlementService} from '../server/production.mjs';
test('v5.2 anti-cheat detects impossible movement, fire rate and damage envelopes',()=>{const g=new SecurityGuard();g.inspect('p',{kind:'move',seq:1,x:0,y:0,maxSpeed:10},1000);assert.equal(g.inspect('p',{kind:'move',seq:2,x:100,y:0,maxSpeed:10},1100).reason,'movement-impossible');assert.equal(g.inspect('p',{kind:'fire',seq:3,intervalMs:500,sinceLastMs:50},1200).reason,'fire-rate');assert.equal(g.inspect('p',{kind:'damage',seq:4,amount:999,maxDamage:100},1300).action,'quarantine');});
test('v5.2 economy ledger is atomic and idempotent',()=>{const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE wallet(id TEXT PRIMARY KEY, n INTEGER);INSERT INTO wallet VALUES('p',10)");const l=new EconomyLedger(db);l.run({txId:'x',playerId:'p',kind:'forge',payload:{cost:3}},()=>db.prepare("UPDATE wallet SET n=n-3 WHERE id='p'").run());assert.equal(db.prepare('SELECT n FROM wallet').get().n,7);assert.equal(l.run({txId:'x',playerId:'p',kind:'forge',payload:{cost:3}},()=>{throw Error('must not run')}).duplicate,true);assert.throws(()=>l.run({txId:'x',playerId:'p',kind:'forge',payload:{cost:4}},()=>{}));db.close();});
test('v5.2 admin writes are attributable and auditable',()=>{const db=new DatabaseSync(':memory:');const a=new AdminAudit(db);a.record('gm:ali','mute','p1','verified abuse report');assert.equal(a.list()[0].target,'p1');assert.throws(()=>a.record('gm','ban','p',''));db.close();});
test('v5.2 signed LiveOps only accepts monotonic authenticated revisions',()=>{const l=new LiveOpsConfig({secret:'x'.repeat(40)}),c={revision:1,seasons:['s2'],events:['e'],crucible:['iron'],missions:['m'],rewards:['r']};assert.equal(l.apply(c,l.sign(c)).revision,1);assert.throws(()=>l.apply(c,l.sign(c)));assert.throws(()=>l.apply({...c,revision:2},'bad'));});
test('v5.2 cluster director drains nodes and chooses least-loaded healthy node',()=>{const c=new ClusterDirector({maxPlayers:250});c.heartbeat('a',{players:200});c.heartbeat('b',{players:20});assert.equal(c.place().id,'b');c.drain('b');assert.equal(c.place().id,'a');c.heartbeat('a',{players:250});assert.equal(c.place(),null);});
test('v5.2 telemetry is bounded and privacy-neutral',()=>{const t=new Telemetry();t.inc('reconnect');for(let i=0;i<600;i++)t.observe('latency',i);const s=t.snapshot();assert.equal(s.counters.reconnect,1);assert.equal(s.gauges.latency.count,512);assert(!JSON.stringify(s).includes('player'));});
test('v5.2 push outbox retries and acknowledges operational messages',()=>{const p=new PushOutbox(),m=p.enqueue('p','maintenance',{at:123});assert.equal(p.take()[0].attempts,1);p.ack(m.id);assert.equal(p.queue.length,0);assert.throws(()=>p.enqueue('p','marketing',{}));});
test('v5.2 store entitlements require provider verification and reject cross-account replay',async()=>{const e=new EntitlementService({verifyApple:async()=>({valid:true,productId:'supporter',transactionId:'t1'})});assert.equal((await e.verify({playerId:'a',provider:'apple',receipt:'signed'})).productId,'supporter');await assert.rejects(()=>e.verify({playerId:'b',provider:'apple',receipt:'same'}));assert.equal(e.forPlayer('a').length,1);});
