// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import test from 'node:test';
import assert from 'node:assert/strict';
import { RealmEngine,cleanRealmProfile } from '../shared/realm.mjs';
import { makeRealmMap,makeItem,STAT_CAPS,EQUIP_SLOTS,DUNGEONS } from '../shared/realm-data.mjs';
import { CLASSES,ENEMY_TYPES,walkable,dist,TILE } from '../shared/data.mjs';
function fixture(cls='weaver'){const e=new RealmEngine();const p=e.addPlayer('a','Alpha',cls);return{e,p};}
function field(cls='weaver'){const {e,p}=fixture(cls);e.action(p.id,{type:'realm',target:'realm-1'});p.x=2860;p.y=3450;p.invulnerable=0;const w=e.world(p);w.enemies=[];w.bullets=[];return{e,p,w};}
function steps(e,n=20){for(let i=0;i<n;i++)e.step(.05);}
function item(id,cls='weaver',slot='weapon',tier=1){return makeItem(id,cls,slot,tier,1);}
function dungeonFixture(theme='tide'){const{e,p,w}=field();w.portals.push({id:'test-door',name:'Door',x:p.x,y:p.y,theme,kind:'dungeon',target:null,life:100});assert(e.action(p.id,{type:'portal',portalId:'test-door'}));return{e,p,w:e.world(p)};}
function flood(map){const start=Math.floor(map.spawn.y/TILE)*map.width+Math.floor(map.spawn.x/TILE),seen=new Set([start]),queue=[start];for(let k=0;k<queue.length;k++){const v=queue[k],x=v%map.width,y=Math.floor(v/map.width);for(const [nx,ny]of [[x+1,y],[x-1,y],[x,y+1],[x,y-1]]){const id=ny*map.width+nx;if(nx>=0&&ny>=0&&nx<map.width&&ny<map.height&&!seen.has(id)&&map.tiles[id].type<2){seen.add(id);queue.push(id);}}}return seen;}
test('Realm maps are deterministic, distinct from Nexus, and substantially larger',()=>{const a=makeRealmMap('realm',20),b=makeRealmMap('realm',20);assert.deepEqual(a.tiles,b.tiles);assert(a.width*a.height>12000);assert.equal(makeRealmMap('nexus',20).kind,'nexus');assert(walkable(a,a.spawn.x,a.spawn.y));});
for(const theme of Object.keys(DUNGEONS))test(`${theme}: dungeon entrance, six rooms and boss are connected`,()=>{const m=makeRealmMap('dungeon',33,theme),seen=flood(m);assert(walkable(m,m.spawn.x,m.spawn.y));assert(walkable(m,m.boss.x,m.boss.y,48));assert(seen.has(Math.floor(m.boss.y/TILE)*m.width+Math.floor(m.boss.x/TILE)));assert.equal(m.rooms.length,6);});
test('New account starts in a safe Nexus with all four equipment slots and no paid gate',()=>{const{e,p}=fixture();assert.equal(p.worldId,'nexus');assert(e.safe(p));assert.equal(Object.keys(p.equipment).length,4);assert.equal(p.level,1);assert.equal(p.bank,0);assert.equal(p.vault.length,0);assert.equal(p.inventory.length,0);});
test('All six classes can cast their distinct ability; cooldown and mana are enforced',()=>{for(const cls of Object.keys(CLASSES)){const{e,p,w}=field(cls);const mp=p.mp;assert(e.action(p.id,{type:'ability'}),cls);assert(p.mp<mp);assert(!e.action(p.id,{type:'ability'}));assert(p.abilityCd>0);if(cls==='weaver')assert.equal(w.bullets.length,16);if(cls==='ranger')assert.equal(w.bullets.length,7);if(cls==='warden')assert(p.shield>0);if(cls==='shade')assert(p.invisible>0);if(cls==='warrior')assert(p.berserk>0);}});
test('Priest heals nearby living allies, not other worlds',()=>{const{e,p,w}=field('cleric');const q=e.addPlayer('b','Beta','warden');e.action(q.id,{type:'realm',target:'realm-1'});q.x=p.x+50;q.y=p.y;q.hp=20;p.hp=20;const n=e.addPlayer('c','Other','warden');n.hp=20;assert(e.action(p.id,{type:'ability'}));assert(q.hp>20);assert(p.hp>20);assert.equal(n.hp,20);});
test('Warrior grants an actual attack-speed buff to nearby allies',()=>{const{e,p,w}=field('warrior');const q=e.addPlayer('b','Beta','ranger');e.action('b',{type:'realm',target:'realm-1'});q.x=p.x;q.y=p.y;const before=e.stats(q).interval;assert(e.action('a',{type:'ability'}));assert(e.stats(q).interval<before);});
test('Rogue invisibility suppresses new targeting but does not make existing bullets harmless',()=>{const{e,p,w}=field('shade');w.spawnEnemy('cultist',p.x+150,p.y);e.action(p.id,{type:'ability'});steps(e,50);assert.equal(w.bullets.filter(b=>b.team==='enemy').length,0);const before=p.hp;p.invulnerable=0;w.damagePlayer(p,40);assert(p.hp<before);});
test('Instant Nexus return deposits only carried currency and preserves health/cooldowns',()=>{const{e,p}=field();p.runCoins=45;p.bank=7;p.hp=31;p.abilityCd=4;assert(e.action(p.id,{type:'nexus'}));assert.equal(p.worldId,'nexus');assert.equal(p.bank,52);assert.equal(p.runCoins,0);assert.equal(p.hp,31);assert.equal(p.abilityCd,4);assert(e.safe(p));});
test('Universal dash removed; mana potions are a real separate consumable',()=>{const{e,p}=field();assert(!e.action(p.id,{type:'dash'}));p.mp=0;assert(e.action(p.id,{type:'mana'}));assert.equal(p.manaPotions,2);assert(p.mp>0);});
test('Realm changes cannot be forged from combat or to nonexistent targets',()=>{const{e,p}=field();assert(!e.action(p.id,{type:'realm',target:'realm-2'}));assert(!e.action(p.id,{type:'realm',target:'evil'}));assert(!e.action(p.id,{type:'portal',portalId:'unknown'}));});
test('Actual portals enforce distance; two players enter the same dungeon instance',()=>{const{e,p,w}=field();const q=e.addPlayer('b','Beta','warden');e.action(q.id,{type:'realm',target:'realm-1'});w.portals.push({id:'door',x:p.x,y:p.y,life:50,theme:'tide',target:null,kind:'dungeon'});assert(!e.action(q.id,{type:'portal',portalId:'door'}));q.x=p.x;q.y=p.y;assert(e.action(p.id,{type:'portal',portalId:'door'}));assert(e.action(q.id,{type:'portal',portalId:'door'}));assert.equal(p.worldId,q.worldId);assert.equal(e.world(p).players.size,2);assert.equal(e.world(p).kind,'dungeon');});
test('Public realms enforce 40 inhabitants without dropping the 41st player from Nexus',()=>{const e=new RealmEngine();for(let i=0;i<40;i++){const p=e.addPlayer('p'+i,'P'+i,'ranger');assert(e.action(p.id,{type:'realm',target:'realm-1'}));}const q=e.addPlayer('overflow','Overflow','ranger');assert(!e.action(q.id,{type:'realm',target:'realm-1'}));assert.equal(q.worldId,'nexus');assert(e.action(q.id,{type:'realm',target:'realm-2'}));});
test('Realm entities, chat and bullets are isolated between worlds',()=>{const{e,p,w}=field();const q=e.addPlayer('b','Beta','weaver');e.action('b',{type:'realm',target:'realm-2'});e.action(p.id,{type:'chat',text:'Private to world one'});w.spawnEnemy('crab',p.x+50,p.y);w.projectile(p,0,'player',20,200,2);const s=e.snapshot('b');assert(!s.players.some(v=>v.id==='a'));assert(!s.chat.some(v=>v.text==='Private to world one'));assert(!s.bullets.some(v=>v.owner==='a'));});
test('One complete XP reward is given to each nearby ally, never divided',()=>{const{e,p,w}=field();const q=e.addPlayer('b','Beta','ranger');e.action('b',{type:'realm',target:'realm-1'});q.x=p.x;q.y=p.y;const z=e.addPlayer('c','Far','weaver');e.action('c',{type:'realm',target:'realm-1'});z.x=600;z.y=700;const enemy=w.spawnEnemy('crab',p.x+60,p.y);w.damageEnemy(enemy,1000,'a');assert.equal(p.xp,q.xp);assert.equal(p.xp,ENEMY_TYPES.crab.xp);assert.equal(z.xp,0);});
test('Loot belongs to contributing players; bystanders cannot see or steal it',()=>{const{e,p,w}=field();const q=e.addPlayer('b','Beta','warden');e.action('b',{type:'realm',target:'realm-1'});q.x=p.x;q.y=p.y;const b=w.spawnEnemy('captain',p.x+20,p.y);w.damageEnemy(b,100000,p.id);const drop=w.loot.find(l=>l.kind==='item');assert(drop);assert.equal(drop.owner,p.id);q.x=drop.x;q.y=drop.y;assert(!e.snapshot(q.id).loot.length);assert(!e.action(q.id,{type:'interact'}));p.x=drop.x;p.y=drop.y;assert(e.action(p.id,{type:'interact'}));assert(p.inventory.some(v=>v.id===drop.item.id));assert(!w.loot.some(l=>l.id===drop.id));});
test('Two contributors get distinct personally owned boss drops',()=>{const{e,p,w}=field();const q=e.addPlayer('b','Beta','warden');e.action('b',{type:'realm',target:'realm-1'});q.x=p.x;q.y=p.y;const b=w.spawnEnemy('captain',p.x+20,p.y);w.damageEnemy(b,20,'b');w.damageEnemy(b,100000,'a');assert(w.loot.some(l=>l.owner==='a'&&l.kind==='item'));assert(w.loot.some(l=>l.owner==='b'&&l.kind==='item'));const ids=w.loot.filter(l=>l.item).map(l=>l.item.id);assert.equal(new Set(ids).size,ids.length);});
test('All four equipment slots swap atomically even with a full eight-slot backpack',()=>{const{e,p}=fixture();for(const slot of EQUIP_SLOTS){p.inventory=Array.from({length:8},(_,i)=>item(slot+'-'+i,p.classId,slot));const ids=new Set([...p.inventory.map(i=>i.id),p.equipment[slot].id]);assert(e.action('a',{type:'equip',itemId:p.inventory[0].id}));assert.equal(p.inventory.length,8);assert.deepEqual(new Set([...p.inventory.map(i=>i.id),p.equipment[slot].id]),ids);}});
test('Class-incompatible equipment is rejected, rings are shared across classes',()=>{const{e,p}=fixture();p.inventory=[item('wrong','warden'),makeItem('ring','warden','charm',2)];assert(!e.action('a',{type:'equip',itemId:'wrong'}));assert(e.action('a',{type:'equip',itemId:'ring'}));});
test('Stat potions increment a real stat, are consumed once and stop at the cap',()=>{const{e,p}=fixture();p.inventory=[{id:'pot',slot:'potion',statKey:'atk',stat:1,name:'Angriff-Trank',rarity:1}];const d=e.stats(p).damage;assert(e.action('a',{type:'consume',itemId:'pot'}));assert.equal(p.bonuses.atk,1);assert(e.stats(p).damage>d);assert(!e.action('a',{type:'consume',itemId:'pot'}));p.bonuses.atk=20;p.inventory=[{id:'pot2',slot:'potion',statKey:'atk',stat:1,name:'Angriff-Trank',rarity:1}];assert(!e.action('a',{type:'consume',itemId:'pot2'}));assert.equal(p.inventory.length,1);});
test('Leveling caps at 20 while character fame continues to accumulate',()=>{const{e,p}=fixture();e.world(p).giveXP(p,1e9);assert.equal(p.level,20);assert.equal(p.xp,0);const fame=p.characterFame;e.world(p).giveXP(p,100);assert(p.characterFame>fame);});
test('Vault transfer requires the Nexus chest; capacities and item identity are preserved',()=>{const{e,p}=fixture();p.inventory=[item('loot')];assert(!e.action('a',{type:'deposit',itemId:'loot'}));p.x=500;p.y=790;assert(e.action('a',{type:'deposit',itemId:'loot'}));assert.equal(p.inventory.length,0);assert.equal(p.vault.length,1);assert(!e.action('a',{type:'deposit',itemId:'loot'}));assert(e.action('a',{type:'withdraw',itemId:'loot'}));p.vault=Array.from({length:16},(_,i)=>item('v'+i));assert(!e.action('a',{type:'deposit',itemId:'loot'}));assert.equal(p.inventory[0].id,'loot');});
test('Permadeath destroys carried gear and potion bonuses, preserving vault/bank/fame',()=>{const{e,p,w}=field();p.vault=[item('safe')];p.inventory=[item('lost')];p.bank=99;p.runCoins=15;p.bonuses.atk=7;p.level=12;p.characterFame=30;w.damagePlayer(p,100000,'Golem');assert(p.dead);assert.equal(p.inventory.length,0);assert.equal(Object.keys(p.equipment).length,0);assert.equal(p.bonuses.atk,0);assert.equal(p.vault[0].id,'safe');assert.equal(p.bank,99);assert.equal(p.fame,30);assert.equal(p.runCoins,0);assert.equal(p.deathRecord.level,12);assert(w.graves.some(g=>g.name===p.name));assert(!e.action('a',{type:'nexus'}));assert(e.action('a',{type:'rebirth',classId:'cleric'}));assert.equal(p.worldId,'nexus');assert.equal(p.classId,'cleric');assert.equal(p.level,1);assert.equal(Object.keys(p.equipment).length,4);assert.equal(p.vault[0].id,'safe');});
test('Enemy attacks are telegraphed; boss phases progress with health',()=>{const{e,p,w}=field();const b=w.spawnEnemy('sovereign',p.x+200,p.y);b.cooldown=0;b.hp=b.maxHP*.2;steps(e,1);assert.equal(b.phase,3);assert(b.telegraph>0);assert.equal(w.bullets.length,0);steps(e,14);assert(w.bullets.some(b=>b.team==='enemy'));});
test('Event bosses drop real dungeon portals instead of a fake visual marker',()=>{const{e,p,w}=field();const b=w.spawnEnemy('captain',p.x+25,p.y);b.eventBoss=true;b.dungeon='tide';w.damageEnemy(b,100000,'a');const q=w.portals.find(q=>q.theme==='tide');assert(q);assert.equal(w.score,25);assert(e.action('a',{type:'portal',portalId:q.id}));assert.equal(e.world(p).theme,'tide');});
test('Dungeon boss completion opens a real exit and guaranteed stat potion',()=>{const{e,p,w}=dungeonFixture('crypt');const b=w.enemies.find(b=>b.dungeonBoss);p.x=b.x-40;p.y=b.y;w.damageEnemy(b,100000,'a');assert(w.completed);assert.equal(w.bossState,'defeated');assert(w.loot.some(l=>l.item?.slot==='potion'&&l.item.statKey==='wis'));const q=w.portals.at(-1);p.x=q.x;p.y=q.y;assert(e.action('a',{type:'portal',portalId:q.id}));assert.equal(p.worldId,'nexus');});
test('Realm closure moves living players to a shared raid and does not strand dead players',()=>{const{e,p,w}=field();const q=e.addPlayer('b','Beta','weaver');e.action('b',{type:'realm',target:'realm-1'});q.dead=true;q.hp=0;w.score=w.scoreTarget-1;const c=w.spawnEnemy('crab',p.x+10,p.y);w.damageEnemy(c,1000,'a');assert(w.closingAt>0);steps(e,405);assert.equal(e.world(p).theme,'citadel');assert.equal(q.worldId,'nexus');assert(q.dead);assert.equal(e.worlds.get('realm-1').score,0);});
test('Expired dungeon portals disappear; empty instances are eventually collected',()=>{const{e,p,w}=dungeonFixture();const id=p.worldId;e.action('a',{type:'nexus'});w.ageEmpty=181;steps(e,1);assert(!e.worlds.has(id));for(const z of e.worlds.values())assert(!z.portals.some(q=>q.target===id));});
test('Teleport enforces same world, living target and ten-second cooldown',()=>{const{e,p}=field();const q=e.addPlayer('b','Beta','ranger');assert(!e.action('a',{type:'teleport',playerId:'b'}));e.action('b',{type:'realm',target:'realm-1'});assert(e.action('a',{type:'teleport',playerId:'b'}));assert(dist(p,q)<1);assert.equal(p.teleportCd,10);assert(!e.action('a',{type:'teleport',playerId:'b'}));});
test('Groups have an eight-player cap, private chat and leader succession',()=>{const{e,p}=fixture();assert(e.action('a',{type:'partyCreate'}));const code=p.partyId;for(let i=0;i<8;i++){const q=e.addPlayer('q'+i,'Q'+i,'ranger');assert.equal(e.action(q.id,{type:'partyJoin',code}),i<7);}assert(e.action('a',{type:'chat',channel:'party',text:'Only our party'}));assert(e.snapshot('q0').chat.some(v=>v.text==='Only our party'));assert(!e.snapshot('q7').chat.some(v=>v.text==='Only our party'));assert(e.action('a',{type:'partyLeave'}));assert.equal(e.groups.get(code).leader,'q0');});
test('Chat is bounded, rate limited, retains text rather than interpreting markup',()=>{const{e,p}=fixture();assert(e.action('a',{type:'chat',text:'<img src=x onerror=evil()>'.repeat(20)}));assert.equal(e.snapshot('a').chat.at(-1).text.length,180);assert(!e.action('a',{type:'chat',text:'flood'}));steps(e,18);assert(e.action('a',{type:'chat',text:'Again'}));});
test('Snapshot ownership hides other backpacks, vaults and private bags',()=>{const{e,p}=fixture();const q=e.addPlayer('b','Beta','weaver');q.vault=[item('secret')];q.inventory=[item('secret2')];const s=e.snapshot('a'),other=s.players.find(x=>x.id==='b');assert.equal(other.inventory,undefined);assert.equal(other.vault,undefined);s.players[0].equipment.weapon.name='modified';assert.notEqual(p.equipment.weapon.name,'modified');});
test('Realm profile sanitizer deduplicates item IDs and preserves valid fourth slot/stats',()=>{const raw={classId:'weaver',started:true,inventory:[item('dup'),{}],vault:[item('dup'),item('valid')],equipment:{ability:item('ability','weaver','ability')},bonuses:{atk:Infinity,spd:500},x:4900,y:3700};const p=cleanRealmProfile(raw);assert.equal(p.inventory.length,1);assert.equal(p.vault.length,1);assert(p.equipment.ability);assert.equal(p.bonuses.atk,0);assert.equal(p.bonuses.spd,20);assert.equal(p.x,4900);});
test('Profile and world serialization restore dungeon identity, boss damage, vault and personal loot',()=>{const{e,p,w}=dungeonFixture('grove');const b=w.enemies.find(b=>b.dungeonBoss);b.hp=777;p.vault=[item('saved')];p.abilityCd=3;p.x=900;p.y=1420;w.loot.push({id:'bag',owner:p.id,kind:'item',item:item('dropped'),x:p.x,y:p.y,life:70});const profile=e.profile('a'),world=e.exportWorlds();const r=new RealmEngine({savedWorld:JSON.parse(JSON.stringify(world))});r.addPlayer('a','Alpha','weaver',profile);const s=r.snapshot('a');assert.equal(s.world.id,w.worldId);assert.equal(s.enemies.find(b=>b.dungeonBoss).hp,777);assert.equal(s.players[0].vault[0].id,'saved');assert.equal(s.players[0].abilityCd,3);assert(s.loot.some(l=>l.item.id==='dropped'));});
test('Invalid input cannot move, heal or alter the server-owned bank',()=>{const{e,p}=fixture();const x=p.x;e.setInput('a',{dx:NaN,dy:Infinity,x:9000,bank:999999,hp:999999,fire:'yes'});e.step(.05);assert.equal(p.x,x);assert.equal(p.bank,0);assert(p.hp<1000);assert(!e.action('a',{type:'giveGold',amount:999999}));});
test('All generated ordinary and boss spawn points are physically walkable',()=>{const e=new RealmEngine();for(const w of e.worlds.values())for(const m of w.enemies)assert(walkable(w.map,m.x,m.y,m.radius),`${w.worldId} ${m.kind} ${m.x},${m.y}`);});
