// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import test from 'node:test';import assert from 'node:assert/strict';
import { once } from 'node:events';import { mkdtempSync,rmSync } from 'node:fs';import { join } from 'node:path';import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { ProfileStore } from '../server/store.mjs';import { SafetyStore } from '../server/safety.mjs';import { createGameServer } from '../server/server.mjs';
import { compareEquipment } from '../client/presentation.mjs';import { makeItem } from '../shared/realm-data.mjs';
async function fixture(t){const app=createGameServer({dataPath:':memory:'});app.server.listen(0,'127.0.0.1');await once(app.server,'listening');t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port;
 const request=async(path,b,token,method='POST')=>{const r=await fetch(base+path,{method,headers:{...(b?{'content-type':'application/json'}:{}),...(token?{authorization:'Bearer '+token}:{})},...(b?{body:JSON.stringify(b)}:{})});return {status:r.status,data:await r.json()};};
 const login=async name=>(await request('/api/session',{protocol:2,name,classId:'ranger',room:'PUBLIC'})).data;return {app,request,login};}
function stores(t){const store=new ProfileStore(':memory:');t.after(()=>store.close());const safety=new SafetyStore(store.db);const a=store.create('Ali','ranger'),b=store.create('Other','weaver');return {store,safety,a,b};}
test('account blocks persist, filter chat and never hide combat state',async t=>{const {app,request,login}=await fixture(t),a=await login('Ali'),b=await login('Other');assert.equal((await request('/api/safety/block',{playerId:b.playerId,enabled:true},a.token)).status,200);assert.equal((await request('/api/action',{type:'chat',text:'Blocked message'},b.token)).status,200);const result=await request('/api/action',{type:'noop'},a.token);assert(!result.data.snapshot.chat.some(m=>m.text==='Blocked message'));assert(result.data.snapshot.players.some(p=>p.id===b.playerId));assert.equal(result.data.snapshot.safety.blocked[0].id,b.playerId);assert.equal((await request('/api/action',{type:'tradeInvite',playerId:a.playerId},b.token)).data.accepted,false);assert.equal((await request('/api/safety/block',{playerId:b.playerId,enabled:false},a.token)).status,200);assert(app.safety.canTrade(a.playerId,b.playerId));});
test('self-blocks, unknown accounts and missing confirmation are rejected',async t=>{const {request,login}=await fixture(t),a=await login('A');for(const body of [{playerId:a.playerId,enabled:true},{playerId:'invented',enabled:true},{playerId:a.playerId}])assert.equal((await request('/api/safety/block',body,a.token)).status,400);});
test('a report contains only visible server evidence, not fabricated client text',async t=>{const {app,request,login}=await fixture(t),a=await login('Ali'),b=await login('Other');await request('/api/action',{type:'chat',text:'Known message'},b.token);const r=await request('/api/safety/report',{playerId:b.playerId,reason:'spam',quote:'fabricated',password:'must not save'},a.token);assert.equal(r.status,200);const row=app.store.db.prepare('SELECT * FROM player_reports WHERE id=?').get(r.data.reference);assert.equal(row.quote,'Known message');assert(!JSON.stringify(row).includes('fabricated'));assert(!JSON.stringify(row).includes('must not save'));const dup=await request('/api/safety/report',{playerId:b.playerId,reason:'spam'},a.token);assert.equal(dup.data.reference,r.data.reference);assert(dup.data.duplicate);});
test('reports are private; reporters cannot fetch or resolve anyone’s report',async t=>{const {request,login}=await fixture(t),a=await login('A'),b=await login('B');const r=await request('/api/safety/report',{playerId:b.playerId,reason:'other'},a.token);assert.equal(r.status,200);assert.equal((await request('/api/safety/reports',null,a.token,'GET')).status,404);assert.equal((await request('/api/safety/review',{reference:r.data.reference},b.token)).status,404);assert.equal((await request('/api/safety',null,null,'GET')).status,401);});
test('reports from invisible accounts or invalid reasons are rejected',async t=>{const {app,request,login}=await fixture(t),a=await login('A');const hidden=app.store.create('Hidden','weaver');assert.equal((await request('/api/safety/report',{playerId:hidden.id,reason:'other'},a.token)).status,400);const b=await login('B');assert.equal((await request('/api/safety/report',{playerId:b.playerId,reason:'invalid'},a.token)).status,400);});
test('operator chat mute is enforced by HTTP API and can expire or be lifted',async t=>{const {app,request,login}=await fixture(t),a=await login('A');app.safety.mute(a.playerId,5,'Spam review');assert.equal((await request('/api/action',{type:'chat',text:'No'},a.token)).data.accepted,false);assert((await request('/api/safety',null,a.token,'GET')).data.chatMutedUntil>Date.now());app.safety.mute(a.playerId,0,'Review completed');assert.equal((await request('/api/action',{type:'chat',text:'Allowed'},a.token)).data.accepted,true);});
test('deleting an account removes blocks and reports through foreign keys',t=>{const {store,safety,a,b}=stores(t);safety.setBlock(a.id,b.id,true);safety.report(a.id,b.id,'other');store.delete(b.id);safety.clearCache();assert.equal(safety.blocked(a.id).size,0);assert.equal(store.db.prepare('SELECT COUNT(*) n FROM player_reports').get().n,0);});
test('report retention removes old evidence without touching profiles',t=>{const {store,safety,a,b}=stores(t);const r=safety.report(a.id,b.id,'other');store.db.prepare('UPDATE player_reports SET created_at=? WHERE id=?').run(Date.now()-31*86400000,r.reference);safety.report(a.id,b.id,'spam');assert.equal(store.db.prepare('SELECT COUNT(*) n FROM player_reports').get().n,1);assert(store.find(a.token));});
test('safety migrations reopen a pre-existing database and keep blocks',()=>{const dir=mkdtempSync(join(tmpdir(),'safety-'));let s;try{s=new ProfileStore(join(dir,'x.sqlite'));const a=s.create('A','ranger'),b=s.create('B','weaver');const safety=new SafetyStore(s.db);safety.setBlock(a.id,b.id,true);s.close();s=new ProfileStore(join(dir,'x.sqlite'));const restored=new SafetyStore(s.db);assert(restored.blocked(a.id).has(b.id));assert(s.find(a.token));}finally{s?.close();rmSync(dir,{recursive:true,force:true});}});
test('operator CLI requires explicit write confirmation and reviews actual stored report',()=>{const dir=mkdtempSync(join(tmpdir(),'moderation-cli-')),file=join(dir,'x.sqlite');try{const s=new ProfileStore(file),a=s.create('A','ranger'),b=s.create('B','weaver'),safety=new SafetyStore(s.db),r=safety.report(a.id,b.id,'other');s.close();const run=args=>spawnSync(process.execPath,['tools/moderate.mjs',...args],{env:{...process.env,DATA_PATH:file},encoding:'utf8'});assert.equal(run(['review',r.reference,'dismissed','Checked']).status,1);assert.equal(run(['review',r.reference,'dismissed','Checked','--confirm']).status,0);const list=run(['list']);assert.equal(list.status,0);assert.equal(JSON.parse(list.stdout)[0].status,'dismissed');assert.equal(run(['mute',b.id,'5','Operator review','--confirm']).status,0);}finally{rmSync(dir,{recursive:true,force:true});}});
test('equipment comparison is derived from real values and respects weapon family',()=>{const item=makeItem('upgrade','ranger','weapon',4),current=makeItem('current','ranger','weapon',0),p={classId:'ranger',equipment:{weapon:current}};const compared=compareEquipment(item,p);assert.equal(compared.delta,item.stat-current.stat);assert(compared.compatible);assert.equal(compareEquipment(current,p).same,true);assert.equal(compareEquipment(makeItem('foreign','weaver','weapon',4),p).compatible,false);assert.equal(compareEquipment({slot:'potion'},p),null);});

test('retention works at restart and without receiving new reports',t=>{const {store,safety,a,b}=stores(t);const r=safety.report(a.id,b.id,'spam');store.db.prepare('UPDATE player_reports SET created_at=? WHERE id=?').run(Date.now()-31*86400000,r.reference);safety.prune();assert.equal(store.db.prepare('SELECT COUNT(*) n FROM player_reports').get().n,0);safety.mute(b.id,5,'Temporary restriction');store.db.prepare('UPDATE chat_restrictions SET until=1').run();new SafetyStore(store.db);assert.equal(store.db.prepare('SELECT COUNT(*) n FROM chat_restrictions').get().n,0);});
test('malformed trade target is rejected rather than failing as a server error',async t=>{const {request,login}=await fixture(t),a=await login('A');for(const body of [{type:'tradeInvite'},{type:'tradeInvite',playerId:7},{type:'tradeInvite',playerId:a.playerId}]){const r=await request('/api/action',body,a.token);assert.equal(r.status,200);assert.equal(r.data.accepted,false);}});
test('blocking prevents direct friend messages even when friendship already exists',async t=>{const {request,login}=await fixture(t),a=await login('Ali'),b=await login('Other');assert.equal((await request('/api/action',{type:'friendRequest',playerId:b.playerId},a.token)).data.accepted,true);assert.equal((await request('/api/action',{type:'friendAccept',playerId:a.playerId},b.token)).data.accepted,true);assert.equal((await request('/api/safety/block',{playerId:b.playerId,enabled:true},a.token)).status,200);const denied=await request('/api/action',{type:'chat',channel:'friend',playerId:a.playerId,text:'Should not arrive'},b.token);assert.equal(denied.data.accepted,false);const view=await request('/api/action',{type:'noop'},a.token);assert(!view.data.snapshot.chat.some(m=>m.text==='Should not arrive'));});
