// SPDX-License-Identifier: LicenseRef-Nyrathen-Proprietary
import {createHash,createSign,X509Certificate,createPublicKey,verify as verifySignature} from 'node:crypto';
import {STORE_PRODUCTS,SHOP_EVENT_NAMES,applyStoreGrant,reverseStoreGrant,storeGrantRecord,spendShardOffer,SHARD_OFFERS,isShardOfferActive} from '../shared/monetization-data.mjs';
const b64url=s=>Buffer.from(String(s).replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(String(s).length/4)*4,'='),'base64');
const sha=v=>createHash('sha256').update(String(v)).digest('hex');
const derEcdsa=raw=>{if(raw.length!==64)throw new Error('Invalid ES256 signature');const enc=x=>{let b=Buffer.from(x);while(b.length>1&&b[0]===0)b=b.subarray(1);if(b[0]&0x80)b=Buffer.concat([Buffer.from([0]),b]);return Buffer.concat([Buffer.from([2,b.length]),b]);};const r=enc(raw.subarray(0,32)),s=enc(raw.subarray(32));return Buffer.concat([Buffer.from([0x30,r.length+s.length]),r,s]);};
export function grantVerifiedProduct(profile,productId){const product=STORE_PRODUCTS[productId];if(!product)throw Object.assign(new Error('Unknown store product'),{status:400});applyStoreGrant(profile,product);return{profile,grant:storeGrantRecord(product)};}
export function revokeVerifiedProduct(profile,grant){return reverseStoreGrant(profile,grant);}
export function spendPremium(profile,offerId,now=Date.now(),rotationIds=null){const offer=SHARD_OFFERS[offerId];if(!offer)throw Object.assign(new Error('Unknown premium offer'),{status:400});if(!isShardOfferActive(offerId,now,rotationIds))throw Object.assign(new Error('Dieses Angebot ist nicht in der aktuellen Rotation.'),{status:409});if(!spendShardOffer(profile,offer))throw Object.assign(new Error(profile.account?.commerce?.shardDebt>0?'Premiumkonto wegen Rückerstattung gesperrt, bis die Splitter-Schuld ausgeglichen ist.':'Offer unavailable or insufficient Nyr-Splitter'),{status:409});return offer;}
export function commerceAccountHash(playerId){return sha(playerId);}
export function createStoreVerifier(env=process.env){
 const packageName=env.GOOGLE_PLAY_PACKAGE||'game.nyrathen.mobile',bundleId=env.APPLE_BUNDLE_ID||'game.nyrathen.mobile';
 let googleToken=null,googleTokenUntil=0;
 const googleCreds=()=>{if(!env.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON)return null;try{return JSON.parse(env.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON);}catch{throw new Error('GOOGLE_PLAY_SERVICE_ACCOUNT_JSON invalid');}};
 async function googleAccessToken(){if(googleToken&&Date.now()<googleTokenUntil-60000)return googleToken;const c=googleCreds();if(!c?.client_email||!c?.private_key)throw new Error('Google Play verifier not configured');const now=Math.floor(Date.now()/1000),head=Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT'})).toString('base64url'),body=Buffer.from(JSON.stringify({iss:c.client_email,scope:'https://www.googleapis.com/auth/androidpublisher',aud:c.token_uri||'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})).toString('base64url'),unsigned=`${head}.${body}`,sig=createSign('RSA-SHA256').update(unsigned).end().sign(c.private_key).toString('base64url'),assertion=`${unsigned}.${sig}`;const r=await fetch(c.token_uri||'https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion}),signal:AbortSignal.timeout(10000)});const j=await r.json();if(!r.ok||!j.access_token)throw new Error('Google OAuth failed');googleToken=j.access_token;googleTokenUntil=Date.now()+Number(j.expires_in||3600)*1000;return googleToken;}
 async function verifyGoogle({receipt,productId,playerId}){if(typeof receipt!=='string'||receipt.length<20)throw Object.assign(new Error('Invalid Google purchase token'),{status:400});const token=await googleAccessToken();const url=`https://androidpublisher.googleapis.com/androidpublisher/v3/applications/${encodeURIComponent(packageName)}/purchases/productsv2/tokens/${encodeURIComponent(receipt)}`;const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(10000)});const j=await r.json();if(!r.ok)throw Object.assign(new Error('Google Play verification failed'),{status:400});const state=j.purchaseStateContext?.purchaseState||j.purchaseStateContext?.purchaseState?.purchaseState,items=j.productLineItem||[],actual=items[0]?.productId;if(state!=='PURCHASED'||actual!==productId)throw Object.assign(new Error('Google Play purchase not completed'),{status:400});if(!j.obfuscatedExternalAccountId||j.obfuscatedExternalAccountId!==commerceAccountHash(playerId))throw Object.assign(new Error('Google Play account mismatch'),{status:409});return{valid:true,productId:actual,transactionId:'gp:'+sha(receipt),purchaseToken:receipt,orderId:j.orderId||null};}
 function verifyApple({receipt,productId,playerId}){if(typeof receipt!=='string'||receipt.split('.').length!==3)throw Object.assign(new Error('Invalid App Store JWS'),{status:400});const [h,p,s]=receipt.split('.'),header=JSON.parse(b64url(h)),payload=JSON.parse(b64url(p));if(header.alg!=='ES256'||!Array.isArray(header.x5c)||!header.x5c.length)throw Object.assign(new Error('Invalid App Store signature header'),{status:400});const certs=header.x5c.map(x=>new X509Certificate(Buffer.from(x,'base64')));for(let i=0;i<certs.length-1;i++)if(!certs[i].verify(certs[i+1].publicKey))throw Object.assign(new Error('Invalid App Store certificate chain'),{status:400});const rootPem=env.APPLE_ROOT_CA_PEM;if(!rootPem)throw Object.assign(new Error('Apple verifier not configured'),{status:503});const root=new X509Certificate(rootPem);if(!certs.at(-1).verify(root.publicKey)&&certs.at(-1).fingerprint256!==root.fingerprint256)throw Object.assign(new Error('Untrusted App Store certificate chain'),{status:400});if(!verifySignature('sha256',Buffer.from(`${h}.${p}`),certs[0].publicKey,derEcdsa(b64url(s))))throw Object.assign(new Error('Invalid App Store JWS signature'),{status:400});if(payload.bundleId!==bundleId||payload.productId!==productId)throw Object.assign(new Error('App Store product mismatch'),{status:400});if(!payload.transactionId)throw Object.assign(new Error('Missing App Store transaction'),{status:400});const appToken=payload.appAccountToken||payload.appaccounttoken;if(!appToken)throw Object.assign(new Error('Missing App Store appAccountToken'),{status:400});if(appToken!==playerId)throw Object.assign(new Error('App Store account mismatch'),{status:409});return{valid:true,productId:payload.productId,transactionId:'as:'+payload.transactionId,originalTransactionId:payload.originalTransactionId||payload.transactionId,environment:payload.environment||null,appAccountToken:appToken};}
 return{configured:{apple:!!env.APPLE_ROOT_CA_PEM,google:!!env.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON},verify:async args=>args.provider==='apple'?verifyApple(args):args.provider==='google'?verifyGoogle(args):Promise.reject(Object.assign(new Error('Unsupported store provider'),{status:400}))};
}
