#!/usr/bin/env node
import {once} from 'node:events';import {mkdtempSync,rmSync,mkdirSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {performance} from 'node:perf_hooks';import {createGameServer} from '../server/server.mjs';import {PROTOCOL} from '../shared/data.mjs';
const count=Number(process.env.LOAD_CLIENTS||100);if(![100,250,500,1000].includes(count))throw new Error('LOAD_CLIENTS must be 100, 250, 500 or 1000');
const roomCount=Math.max(2,Math.ceil(count/60));const tmp=mkdtempSync(join(tmpdir(),'nyrathen-load-'));const app=createGameServer({dataPath:join(tmp,'db.sqlite'),backupSeconds:30,backupDirectory:join(tmp,'b'),maxRooms:Math.min(64,roomCount+2),maxPlayers:64,maxSessions:Math.max(1024,count+64),sessionRateLimit:Math.min(10000,Math.max(2000,count*3))});const lat=[],tokens=[];let failures=0;const start=performance.now();
try{app.server.listen(0,'127.0.0.1');await once(app.server,'listening');const base='http://127.0.0.1:'+app.server.address().port;
 for(let start=0;start<count;start+=25)await Promise.all(Array.from({length:Math.min(25,count-start)},async(_,j)=>{const i=start+j,t=performance.now();try{const r=await fetch(base+'/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({protocol:PROTOCOL,name:'Load'+i,classId:i%2?'ranger':'weaver',room:'L'+String(i%roomCount).padStart(2,'0')})});const x=await r.json();if(!r.ok)throw new Error(x.error);tokens[i]=x.token;lat.push(performance.now()-t)}catch{failures++}}));
 const inputStart=performance.now();for(let start=0;start<count;start+=50)await Promise.all(tokens.slice(start,start+50).map((token,j)=>{const i=start+j;return fetch(base+'/api/input',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify({sequence:1,input:{dx:i%2?1:-1,dy:0,angle:0,fire:false,auto:false}})}).then(r=>{if(!r.ok)failures++}).catch(()=>failures++)}));
 const sorted=lat.sort((a,b)=>a-b),pct=p=>+(sorted[Math.min(sorted.length-1,Math.floor(sorted.length*p))]||0).toFixed(2);const report={status:failures?'failed':'passed',clients:count,created:tokens.filter(Boolean).length,failures,sessionLatencyMs:{p50:pct(.5),p95:pct(.95),p99:pct(.99),max:+(sorted.at(-1)||0).toFixed(2)},inputBurstMs:+(performance.now()-inputStart).toFixed(2),totalMs:+(performance.now()-start).toFixed(2),rss:process.memoryUsage().rss,transport:app.transport,kind:'real local HTTP session + authoritative input burst; 100-client SSE soak is separate'};const dir=resolve(process.env.NYRATHEN_TEST_REPORT_DIR||'release/verification/load-'+count);mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'load.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(failures)process.exitCode=1;
}finally{await app.close();rmSync(tmp,{recursive:true,force:true})}
