#!/usr/bin/env python3
"""Exercise the real v4.0 embedded mobile runtime through DOM, keyboard and two-finger input.
No mocked engine state or injected artwork. Playwright/Chromium are optional QA tools.
set_content is used for managed environments: storage and native builds are NOT certified.
"""
from pathlib import Path
import json, os, shutil, time
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'artifacts'/'v31';ART.mkdir(parents=True,exist_ok=True)
HTML=(ROOT/'dist/Nyrathen-offline.html').read_text()
checks=[]
def check(name,condition,detail=''):
    checks.append({'name':name,'pass':bool(condition),'detail':detail})
    if not condition: print('FAIL:',name,detail,flush=True)
def box(page,selector):return page.locator(selector).bounding_box()
def within(r,w,h):return r and r['x']>=-.5 and r['y']>=-.5 and r['x']+r['width']<=w+.5 and r['y']+r['height']<=h+.5
def overlaps(a,b):return bool(a and b and min(a['x']+a['width'],b['x']+b['width'])-max(a['x'],b['x'])>2 and min(a['y']+a['height'],b['y']+b['height'])-max(a['y'],b['y'])>2)
def state(page):return page.evaluate('window.__nyrathen.state()')
def own(page):return next(p for p in state(page)['players'] if p['id']=='local')
def close(page):page.locator('#modal-close').click();page.wait_for_timeout(120)
start=time.monotonic()
with sync_playwright() as w:
    executable=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('chromium-browser')
    browser=w.chromium.launch(**({'executable_path':executable} if executable else {}),headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
    for name,width,height,mobile in [('desktop',1440,900,False),('portrait',390,844,True),('landscape',844,390,True),('compact',360,640,True)]:
        print('Testing',name,flush=True)
        context=browser.new_context(viewport={'width':width,'height':height},device_scale_factor=1,is_mobile=mobile,has_touch=mobile)
        page=context.new_page();errors=[];page.on('pageerror',lambda error:errors.append(str(error)))
        page.set_content(HTML,wait_until='load');page.wait_for_selector('#menu-screen:not(.hidden)')
        check(name+': boot completes',page.locator('#fatal').is_hidden() and page.locator('#boot-status').is_hidden())
        check(name+': actual client version 5.7.0',page.evaluate('window.__nyrathen.version')=='5.7.0')
        check(name+': 19 playable class cards',page.locator('[data-class]').count()==19)
        check(name+': no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
        for cls in ['warden','ranger','weaver','cleric','shade','warrior']:
            page.locator('[data-class="'+cls+'"]').click()
            check(name+': choose '+cls,page.locator('[data-class="'+cls+'"]').get_attribute('aria-pressed')=='true')
        page.locator('[data-class="ranger"]').click();page.locator('#player-name').fill('Ali')
        page.locator('#menu-screen').evaluate('(e)=>e.scrollTop=0')
        page.screenshot(path=str(ART/f'menu-{name}.png'))
        page.locator('#play-online').click();page.wait_for_selector('#modal[open]')
        if page.locator('#community-rules-accept').count():
            check(name+': online gated by community rules',page.locator('#community-rules-continue').is_disabled())
            page.locator('#community-rules-accept').check();page.locator('#community-rules-continue').click();page.wait_for_selector('#room-code')
        check(name+': online dialog has region PUBLIC',page.locator('#room-code').input_value()=='PUBLIC')
        check(name+': no fictitious public server',page.locator('#server-url').input_value()=='')
        page.locator('#server-url').fill('javascript:alert(1)');page.locator('#connect-button').click();page.wait_for_timeout(150)
        check(name+': invalid URL rejected visibly',bool(page.locator('#connect-error').inner_text()))
        close(page)
        page.locator('#play-offline').click();page.wait_for_selector('#hud:not(.hidden)');page.wait_for_timeout(150)
        check(name+': actual solo Nexus starts',page.evaluate('window.__nyrathen.mode()')=='offline' and state(page)['world']['id']=='nexus')
        check(name+': Nexus has no enemies',len(state(page)['enemies'])==0)
        check(name+': Nexus has two realm portals',len([q for q in state(page)['portals'] if q['kind']=='realm'])==2)
        check(name+': own four equipment slots',len(own(page)['equipment'])==4)
        selectors=['#inventory-btn','#nexus-btn','#auto-btn','#heal-btn','#dash-btn','#ability-btn','#party-btn','#atlas-btn','#chat-btn', '#journal-btn' if mobile else '#side-journal', '#mobile-settings' if mobile else '#hud-settings']
        for selector in selectors:check(name+': control in viewport '+selector,within(box(page,selector),width,height),str(box(page,selector)))
        for i,a in enumerate(selectors):
            for b in selectors[i+1:]:check(name+': no button overlap '+a+' '+b,not overlaps(box(page,a),box(page,b)))
        if mobile:
            for selector in ['#heal-btn','#dash-btn','#ability-btn']:
                r=box(page,selector);check(name+': ability touch target >=44 '+selector,r['width']>=44 and r['height']>=44)
        page.wait_for_timeout(3650)
        page.screenshot(path=str(ART/f'nexus-{name}.png'))
        page.locator('#inventory-btn').click();page.wait_for_selector('#modal[open]');before=state(page)['time'];page.wait_for_timeout(180)
        check(name+': inventory pauses solo',state(page)['time']==before)
        check(name+': four visible equipped items',page.locator('.equipment-grid [data-item]').count()==4)
        check(name+': eight bag cells',page.locator('.item-grid .item-cell').count()==8)
        check(name+': close control visible',within(box(page,'#modal-close'),width,height))
        page.locator('.equipment-grid [data-item]').first.click()
        check(name+': equipment details open',page.locator('.item-detail h3').is_visible())
        page.screenshot(path=str(ART/f'inventory-{name}.png'))
        close(page);check(name+': inventory closes',not page.locator('#modal').is_visible())
        page.locator('#party-btn').click();page.locator('#create-party').click();page.wait_for_selector('#leave-party')
        check(name+': creates actual group',state(page)['party'] is not None and len(state(page)['party']['members'])==1)
        close(page);page.locator('#chat-btn').click();page.locator('#chat-channel').select_option('party')
        payload='<img src=x onerror=alert(1)> Hallo Gruppe'
        page.locator('#chat-input').fill(payload);page.locator('#chat-form button').click();page.wait_for_timeout(180)
        check(name+': chat text rendered literally',payload in page.locator('#chat-history').inner_text())
        check(name+': chat does not inject HTML',page.locator('#chat-history img').count()==0)
        close(page)
        page.locator('#mobile-settings' if mobile else '#hud-settings').click();page.locator('#quality-setting').select_option('low');page.locator('#motion-setting').check()
        check(name+': settings selectable',page.locator('#quality-setting').input_value()=='low' and page.locator('#motion-setting').is_checked());page.locator('#quality-setting').select_option('high');close(page)
        page.locator('#journal-btn' if mobile else '#side-journal').click()
        check(name+': journal opens on character roster',page.locator('.roster-card').count()==1)
        check(name+': 19 classes in new-character selector',page.locator('#new-character-class option').count()==19)
        for section,count,selector in [('quests',18,'.contract-card'),('pets',0,'.pet-card'),('mastery',19,'.mastery-card'),('friends',0,'.friend-row'),('guild',2,'.guild-entry-grid form'),('forge',0,'[data-forge]'),('dungeons',14,'[data-dungeon]'),('bestiary',None,'.bestiary-card'),('account',None,'.system-body')]:
            page.locator('[data-system="'+section+'"]').click();page.wait_for_timeout(100)
            check(name+': section '+section+' opens',page.locator('.system-body').is_visible())
            if count is not None:check(name+': section '+section+' real entries',page.locator(selector).count()==count,str(page.locator(selector).count()))
            check(name+': section '+section+' no horizontal modal overflow',page.locator('#modal').evaluate('(e)=>e.scrollWidth<=e.clientWidth+1'))
            if section in ['dungeons','pets']:page.screenshot(path=str(ART/f'{section}-{name}.png'))
        page.locator('[data-system="characters"]').click();page.locator('#new-character-name').fill('RunenAli');page.locator('#new-character-class').select_option('summoner');page.locator('#new-character-form button[type="submit"]').click();page.wait_for_timeout(140)
        check(name+': creates actual second character',own(page)['classId']=='summoner' and len(own(page)['account']['characters'])==2)
        page.locator('[data-switch="character-1"]').click();page.wait_for_timeout(140)
        check(name+': original character survives switch',own(page)['classId']=='ranger' and own(page)['name']=='Ali')
        page.screenshot(path=str(ART/f'roster-{name}.png'));close(page)
        page.locator('#atlas-btn').click();check(name+': two selectable Realms',page.locator('[data-realm]').count()==2)
        page.locator('[data-realm="realm-1"]').click();page.wait_for_function("window.__nyrathen.state().world.id==='realm-1'")
        check(name+': enters real realm world',state(page)['world']['kind']=='realm' and state(page)['world']['width']==128)
        check(name+': hostile entities exist',len(state(page)['enemies'])>8)
        page.wait_for_timeout(3650);page.screenshot(path=str(ART/f'realm-{name}.png'))
        if name=='portrait':
            cdp=context.new_cdp_session(page);a=box(page,'#move-stick');b=box(page,'#aim-stick')
            ax=a['x']+a['width']/2;ay=a['y']+a['height']/2;bx=b['x']+b['width']/2;by=b['y']+b['height']/2
            before=own(page);points=[{'id':1,'x':ax,'y':ay},{'id':2,'x':bx,'y':by}]
            cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':points})
            points[0]['y']-=32;points[1]['x']+=32
            cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':points});page.wait_for_timeout(1500)
            s=state(page);p=own(page)
            check('portrait: simultaneous two-finger move and fire',p['y']<before['y']-130 and any(e['type']=='shoot' for e in s['events']),str({'from':before['y'],'to':p['y'],'events':[e['type'] for e in s['events'][-8:]]}))
            cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});page.wait_for_timeout(100)
            y=own(page)['y'];page.wait_for_timeout(170)
            check('portrait: releasing touch stops movement',abs(own(page)['y']-y)<1)
            page.screenshot(path=str(ART/'combat-portrait.png'))
        elif name=='desktop':
            before=own(page);page.keyboard.down('w');page.wait_for_timeout(1300);page.keyboard.up('w');page.wait_for_timeout(300)
            check('desktop: WASD moves player out of safety',own(page)['y']<before['y']-170 and not own(page)['safe'])
            page.mouse.move(170,780);page.keyboard.press('q');page.wait_for_timeout(100)
            check('desktop: actual class ability consumes mana and cooldown',own(page)['abilityCd']>0 and own(page)['mp']<own(page)['maxMP'])
            page.keyboard.press('g');page.wait_for_timeout(100)
            check('desktop: G consumes mana potion rather than dash',own(page)['manaPotions']==2)
            page.locator('#auto-btn').click();page.keyboard.down('s');page.wait_for_timeout(550);page.keyboard.up('s')
            check('desktop: actual autonomous projectiles fired',any(e['type']=='shoot' for e in state(page)['events']))
            page.screenshot(path=str(ART/'combat-desktop.png'))
        page.keyboard.press('r');page.wait_for_function("window.__nyrathen.state().world.id==='nexus'")
        check(name+': R returns instantly without channel',state(page)['world']['id']=='nexus')
        page.locator('#atlas-btn').click();page.locator('[data-realm="realm-2"]').click();page.wait_for_function("window.__nyrathen.state().world.id==='realm-2'")
        check(name+': second realm works independently',state(page)['world']['id']=='realm-2')
        page.locator('#atlas-btn').click();page.locator('[data-beacon="Hochlandlicht"]').click();page.wait_for_timeout(300)
        check(name+': beacon travel is functional',own(page)['y']<1600 and own(page)['teleportCd']>0)
        page.wait_for_timeout(3650);page.screenshot(path=str(ART/f'highland-{name}.png'))
        page.locator('#nexus-btn').click();page.wait_for_function("window.__nyrathen.state().world.id==='nexus'")
        page.locator('#mobile-settings' if mobile else '#hud-settings').click();page.locator('#reset-button').click()
        check(name+': destructive reset requires confirmation',page.locator('#confirm-delete').is_visible() and page.locator('#cancel-delete').is_visible())
        page.locator('#cancel-delete').click();page.locator('#resume-button').click()
        check(name+': reset cancellation preserves figure',own(page)['name']=='Ali')
        check(name+': no uncaught JavaScript errors',not errors,str(errors))
        check(name+': no fatal runtime overlay',page.locator('#fatal').is_hidden())
        context.close()
    fault_context=browser.new_context(viewport={'width':390,'height':844});fault_page=fault_context.new_page()
    fault_page.set_content(HTML.replace('<script>','<script>HTMLCanvasElement.prototype.getContext = function(){ return null; };',1),wait_until='load')
    fault_page.wait_for_selector('#fatal:not(.hidden)')
    check('boot guard: initialization failure is visible',fault_page.locator('#fatal').is_visible())
    check('boot guard: stuck loading is removed',fault_page.locator('#boot-status').is_hidden())
    check('boot guard: retry and error export exist',fault_page.locator('#reload-btn').is_visible() and fault_page.locator('#error-log-btn').is_visible())
    fault_context.close();browser.close()
report={'kind':'Actual Chromium DOM, rendering, keyboard and two-finger input tests','checks':len(checks),'passed':sum(c['pass'] for c in checks),'failed':sum(not c['pass'] for c in checks),'durationSeconds':round(time.monotonic()-start,2),'viewports':['1440x900','390x844','844x390','360x640'],'limitations':['Opaque set_content origin: persistent localStorage not verified. Expected save-denied message is handled, not hidden.','Local HTTP browser navigation blocked by environment policy; no policy overrides attempted.','No Safari, native emulator, physical iOS/Android, installed PWA or public HTTPS testing.','Actual multi-client networking tested separately with 24 real HTTP/SSE clients, not browser windows.'],'results':checks}
(ART/'ui-test-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print(json.dumps({k:v for k,v in report.items() if k!='results'},ensure_ascii=False,indent=2))
if report['failed']:raise SystemExit(1)
